/* GENERATED by tools/gen. DO NOT EDIT.
 * Source: shared/errors.json
 * Regenerate with: make gen
 */

#ifndef DAEMOON_ERROR_CODES_H
#define DAEMOON_ERROR_CODES_H

/* Values are frozen in shared/errors.json. Never renumber, never reuse. */
enum {
    DAEMOON_OK = 0,
    DAEMOON_ERR_INVALID_REQUEST      = 1,
    DAEMOON_ERR_INVALID_MANIFEST     = 2,
    DAEMOON_ERR_UNSUPPORTED_PLATFORM = 3,
    DAEMOON_ERR_UNAUTHORIZED         = 4,
    DAEMOON_ERR_DEVICE_REVOKED       = 5,
    DAEMOON_ERR_FORBIDDEN            = 6,
    DAEMOON_ERR_NOT_FOUND            = 7,
    DAEMOON_ERR_VERSION_CONFLICT     = 8,
    DAEMOON_ERR_SHARE_EXPIRED        = 9,
    DAEMOON_ERR_PAIRING_EXPIRED      = 10,
    DAEMOON_ERR_PAIRING_PENDING      = 11,
    DAEMOON_ERR_SAVE_TOO_LARGE       = 12,
    DAEMOON_ERR_CHECKSUM_MISMATCH    = 13,
    DAEMOON_ERR_RATE_LIMITED         = 14,
    DAEMOON_ERR_INTERNAL_ERROR       = 15,
    DAEMOON_ERR_IO_ERROR             = 16,
    DAEMOON_ERR_OUT_OF_MEMORY        = 17,
    DAEMOON_ERR_PARSE_ERROR          = 18,
    DAEMOON_ERR_NETWORK_ERROR        = 19,
    DAEMOON_ERR_TIMEOUT              = 20,
    DAEMOON_ERR_BACKEND_ERROR        = 21,
    DAEMOON_ERR_USER_CANCELLED       = 22,
    DAEMOON_ERR_NO_SPACE             = 23,
    DAEMOON_ERR_UNSUPPORTED          = 24,
    DAEMOON_ERR_ARCHIVE_ERROR        = 25,
    DAEMOON_ERR_BUFFER_TOO_SMALL     = 26,
    DAEMOON_ERR_EMPTY_SAVE           = 27,
    DAEMOON_ERR_TLS_ERROR            = 28,

    DAEMOON_ERR_COUNT_ = 29
};

#endif /* DAEMOON_ERROR_CODES_H */
