// Code generated by tools/gen from shared/errors.json. DO NOT EDIT.

package apierr

import "net/http"

// Code is a wire error code. The server never localizes: it returns one of
// these and the client renders the text from shared/lang/.
type Code string

const (
	InvalidRequest      Code = "invalid_request"
	InvalidManifest     Code = "invalid_manifest"
	UnsupportedPlatform Code = "unsupported_platform"
	Unauthorized        Code = "unauthorized"
	DeviceRevoked       Code = "device_revoked"
	Forbidden           Code = "forbidden"
	NotFound            Code = "not_found"
	VersionConflict     Code = "version_conflict"
	ShareExpired        Code = "share_expired"
	PairingExpired      Code = "pairing_expired"
	PairingPending      Code = "pairing_pending"
	SaveTooLarge        Code = "save_too_large"
	ChecksumMismatch    Code = "checksum_mismatch"
	RateLimited         Code = "rate_limited"
	InternalError       Code = "internal_error"
	IoError             Code = "io_error"
	OutOfMemory         Code = "out_of_memory"
	ParseError          Code = "parse_error"
	NetworkError        Code = "network_error"
	Timeout             Code = "timeout"
	BackendError        Code = "backend_error"
	UserCancelled       Code = "user_cancelled"
	NoSpace             Code = "no_space"
	Unsupported         Code = "unsupported"
	ArchiveError        Code = "archive_error"
	BufferTooSmall      Code = "buffer_too_small"
	EmptySave           Code = "empty_save"
	TlsError            Code = "tls_error"
)

// statusOf maps a code to its HTTP status. Codes that only ever happen on the
// client are absent and fall back to 500.
var statusOf = map[Code]int{
	InvalidRequest:      400,
	InvalidManifest:     400,
	UnsupportedPlatform: 400,
	Unauthorized:        401,
	DeviceRevoked:       401,
	Forbidden:           403,
	NotFound:            404,
	VersionConflict:     409,
	ShareExpired:        410,
	PairingExpired:      410,
	PairingPending:      400,
	SaveTooLarge:        413,
	ChecksumMismatch:    422,
	RateLimited:         429,
	InternalError:       500,
}

// Status returns the HTTP status for a code.
func (c Code) Status() int {
	if s, ok := statusOf[c]; ok {
		return s
	}
	return http.StatusInternalServerError
}

// Known reports whether c came from shared/errors.json.
func (c Code) Known() bool {
	_, ok := detailKeys[c]
	return ok
}

// detailKeys lists the detail fields each code is allowed to carry. Tests use
// it to keep handlers and shared/errors.json from drifting apart.
var detailKeys = map[Code][]string{
	InvalidRequest:      {"field"},
	InvalidManifest:     {"field"},
	UnsupportedPlatform: {"platform"},
	Unauthorized:        nil,
	DeviceRevoked:       {"device_id"},
	Forbidden:           nil,
	NotFound:            nil,
	VersionConflict:     {"server_version", "parent_version", "server_size", "server_device_label", "server_received_at"},
	ShareExpired:        {"expires_at"},
	PairingExpired:      nil,
	PairingPending:      {"interval"},
	SaveTooLarge:        {"size", "max_size"},
	ChecksumMismatch:    {"expected", "actual"},
	RateLimited:         {"retry_after"},
	InternalError:       nil,
	IoError:             {"path"},
	OutOfMemory:         {"size"},
	ParseError:          {"offset"},
	NetworkError:        nil,
	Timeout:             nil,
	BackendError:        {"result"},
	UserCancelled:       nil,
	NoSpace:             {"needed", "free"},
	Unsupported:         {"what"},
	ArchiveError:        {"entry"},
	BufferTooSmall:      {"needed"},
	EmptySave:           {"title"},
	TlsError:            {"host"},
}

// DetailKeys returns the declared detail fields for c.
func DetailKeys(c Code) []string { return detailKeys[c] }

// All returns every code, in the order declared in shared/errors.json.
func All() []Code {
	return []Code{
		InvalidRequest,
		InvalidManifest,
		UnsupportedPlatform,
		Unauthorized,
		DeviceRevoked,
		Forbidden,
		NotFound,
		VersionConflict,
		ShareExpired,
		PairingExpired,
		PairingPending,
		SaveTooLarge,
		ChecksumMismatch,
		RateLimited,
		InternalError,
		IoError,
		OutOfMemory,
		ParseError,
		NetworkError,
		Timeout,
		BackendError,
		UserCancelled,
		NoSpace,
		Unsupported,
		ArchiveError,
		BufferTooSmall,
		EmptySave,
		TlsError,
	}
}
