/* Switch entry point. Phase 6.
 *
 * Same shape as the 3DS entry point: assemble a daemoon_env_t out of libnx and hand
 * it to core. Two things have to happen before anything else, and both are checked
 * at startup rather than discovered halfway through a sync:
 *
 *   - an account has to be selected, because a save belongs to one AccountUid
 *   - applet mode has to be detected, because its memory limit will not fit a sync
 *
 * The interface is borealis. What it replaced was a text console, and the reason it
 * replaced it is in ui/dm_ui.hpp: the console could draw ASCII and no more, so this
 * build fell back to English on the only console anybody had run it on, and there was
 * nowhere to put a game's icon.
 *
 * borealis owns main's shape here - it supplies the entry point, brings the services
 * up before this function is entered, and runs the loop at the bottom. What it does
 * not own is any decision about save data, which is still core's and is still reached
 * through the same daemoon_env_t the 3DS build assembles.
 */
#include "ui/dm_ui.hpp"

#include <daemoon/util/strbuf.h>

#include <switch.h>

#include <cstdio>
#include <cstring>
#include <ctime>

/* Generated by bin2s from vendor/cacert/data/cacert.bin: the public root
 * certificates, in the binary. The Switch has no CA store this build can borrow
 * either, and the card is the override rather than the only source. */
#include "cacert_bin.h"

namespace dm
{

/* 256 KiB, statically. Core never sizes a buffer to a save - it streams through
 * this - and a fixed allocation is one fewer thing that can fail at the moment a
 * save is half written. */
static unsigned char g_scratch[256 * 1024];

App& app()
{
    static App instance;

    return instance;
}

daemoon_result_t App::reloadTitles()
{
    if (titles != nullptr)
    {
        env.save->free_titles(env.save_ctx, titles, count);
        titles = nullptr;
        count  = 0;
    }
    return env.save->list_titles(env.save_ctx, &titles, &count);
}

bool App::canSync() const
{
    return daemoon_nx_config_can_sync(&config) != 0;
}

} // namespace dm

/* ---------------------------------------------------------------------- clock */

/* Informational only, and labelled that way in the manifest. Nothing orders two
 * saves by it: the console clock is user settable, and the server issued version is
 * the only thing freshness is decided by. */
static daemoon_result_t clock_iso8601(void* ctx, char* buf, size_t cap)
{
    time_t now;
    struct tm tm;

    (void)ctx;
    now = time(NULL);
    if (now == (time_t)-1 || gmtime_r(&now, &tm) == NULL)
        return DAEMOON_ERR_UNSUPPORTED;
    if (strftime(buf, cap, "%Y-%m-%dT%H:%M:%SZ", &tm) == 0)
        return DAEMOON_ERR_BUFFER_TOO_SMALL;
    return DAEMOON_OK;
}

/* ------------------------------------------------------------------- language */

/* Which language this build speaks, and which one borealis speaks with it.
 *
 * There is no drawability check any more and that is the point of this rewrite. The
 * console's text console could not draw a byte above 0x7f, so the previous version
 * of this function walked the whole string table looking for one and fell back to
 * English when it found one - which on a Korean console meant every screen was in
 * English. borealis loads the shared fonts for Korean, both Chinese and the Nintendo
 * extended set and falls back per glyph, so the question the check existed to answer
 * no longer has a bad answer.
 */
static void select_language(void)
{
    daemoon_lang_t chosen = DAEMOON_LANG_EN;
    u64 code = 0;
    SetLanguage lang = SetLanguage_ENUS;

    /* A stored choice wins over the console's, the same way it does on the 3DS: a
     * person who picked one is not overruled by the system setting. */
    if (dm::app().config.language[0] != '\0' &&
        daemoon_i18n_language_from_code(dm::app().config.language, &chosen) == DAEMOON_OK)
    {
        daemoon_i18n_set_language(chosen);
        daemoon_nx_trace("lang/config", daemoon_lang_code(chosen));
        return;
    }

    if (R_SUCCEEDED(setGetSystemLanguage(&code)) && R_SUCCEEDED(setMakeLanguage(code, &lang)))
    {
        switch (lang)
        {
            case SetLanguage_JA:     (void)daemoon_i18n_language_from_code("ja", &chosen); break;
            case SetLanguage_FR:
            case SetLanguage_FRCA:   (void)daemoon_i18n_language_from_code("fr", &chosen); break;
            case SetLanguage_DE:     (void)daemoon_i18n_language_from_code("de", &chosen); break;
            case SetLanguage_ES:
            case SetLanguage_ES419:  (void)daemoon_i18n_language_from_code("es", &chosen); break;
            case SetLanguage_ZHCN:
            case SetLanguage_ZHHANS: (void)daemoon_i18n_language_from_code("zh-Hans", &chosen); break;
            case SetLanguage_ZHTW:
            case SetLanguage_ZHHANT: (void)daemoon_i18n_language_from_code("zh-Hant", &chosen); break;
            case SetLanguage_KO:     (void)daemoon_i18n_language_from_code("ko", &chosen); break;
            default: break;
        }
    }
    daemoon_i18n_set_language(chosen);
    daemoon_nx_trace("lang/system", daemoon_lang_code(chosen));
}

/* borealis keeps its own six hint strings, in a directory generated out of the same
 * language files as everything else. Pointing it at the language already chosen is
 * what stops the footer reading "OK" under a Korean question. */
static void select_borealis_locale(void)
{
    std::string code = daemoon_lang_code(daemoon_i18n_language());

    brls::Platform::APP_LOCALE_DEFAULT = (code == "en") ? brls::LOCALE_EN_US : code;
}

/* ---------------------------------------------------------------------- start */

/* A message on a screen that has no activity behind it yet.
 *
 * Startup can fail in three ways a person needs told about - applet mode, no account,
 * and a title list that could not be read - and all three happen before the main
 * screen exists. Each pushes a dialog whose only button quits, which is the whole of
 * this function. */
static void fatal(daemoon_str_id_t body)
{
    auto* dialog = new brls::Dialog(dm::str(body));

    dialog->addButton(dm::str(DAEMOON_STR_BTN_OK), []() { brls::Application::quit(); });
    dialog->setCancelable(false);
    dialog->open();
}

int main(int argc, char* argv[])
{
    (void)argc;
    (void)argv;

    /* Somewhere to put backups and staging, before anything needs it. */
    (void)daemoon_fs_newlib_backend.mkdir_p(NULL, DAEMOON_NX_WORK_DIR);
    daemoon_nx_trace("app/start", NULL);

    (void)daemoon_nx_config_load(DAEMOON_NX_CONFIG_PATH, &dm::app().config);
    select_language();
    select_borealis_locale();

    /* Read before the window is created rather than after, because applet mode is
     * also the case where creating one is most likely to fail: the trace then says
     * which of the two happened. */
    AppletType applet = appletGetAppletType();

    daemoon_nx_trace("app/applet-type",
                     (applet == AppletType_Application ||
                      applet == AppletType_SystemApplication)
                         ? "application"
                         : "applet");

    dm::applyTheme();

    if (!brls::Application::init())
    {
        daemoon_nx_trace("app/brls-init", "failed");
        return EXIT_FAILURE;
    }
    brls::Application::createWindow(dm::str(DAEMOON_STR_APP_TITLE));
    /* One palette, and it is a dark one. The console's own light theme would leave
     * every colour in ui/theme.cpp unreadable, and there is no second set of them. */
    brls::Application::getPlatform()->setThemeVariant(brls::ThemeVariant::DARK);
    /* + quits, and says so in the footer. */
    brls::Application::setGlobalQuit(true);
    daemoon_nx_trace("app/window", NULL);

    if (applet != AppletType_Application && applet != AppletType_SystemApplication)
    {
        /* Limited memory, and the account selector is a library applet that needs the
         * memory an application has. Said now rather than failing partway through. */
        fatal(DAEMOON_STR_WARN_APPLET_MODE);
        while (brls::Application::mainLoop())
            ;
        return EXIT_SUCCESS;
    }

    if (R_FAILED(nsInitialize()))
    {
        /* Names and icons come from here. Without it the list is hex, which is worse
         * and not fatal - exactly what the 3DS does when an SMDH cannot be read. */
        daemoon_nx_trace("app/ns", "failed");
        dm::app().save.names_available = 0;
    }
    else
    {
        dm::app().save.names_available = 1;
    }

    if (daemoon_nx_account_select(&dm::app().save.account) != DAEMOON_OK)
    {
        fatal(DAEMOON_STR_NX_NO_ACCOUNT);
        while (brls::Application::mainLoop())
            ;
        return EXIT_SUCCESS;
    }

    /* The card's bundle if there is one, the built in roots otherwise. */
    dm::app().net.ca_bundle   = dm::app().config.ca_bundle;
    dm::app().net.ca_blob     = cacert_bin;
    dm::app().net.ca_blob_len = cacert_bin_size;
    /* The Switch curl port is 7.69 and has no CURLOPT_CAINFO_BLOB, so the bundle has
     * to reach it as a file. The app writes it; nobody is asked to. */
    dm::app().net.ca_cache_path = DAEMOON_NX_CA_CACHE_PATH;
    if (dm::app().canSync())
        (void)daemoon_net_curl_init();

    daemoon_nx_ui_init(&dm::app().ui);
    dm::app().archive.count = 0;
    dm::app().scratch       = dm::g_scratch;
    dm::app().scratchLen    = sizeof(dm::g_scratch);

    daemoon_env_t& env = dm::app().env;

    std::memset(&env, 0, sizeof(env));
    env.save         = &daemoon_nx_save_backend;
    env.fs           = &daemoon_fs_newlib_backend;
    env.ui           = &daemoon_nx_ui_backend;
    env.net          = &daemoon_net_curl_backend;
    env.save_ctx     = &dm::app().save;
    env.net_ctx      = &dm::app().net;
    env.ui_ctx       = &dm::app().ui;
    env.device_label = dm::app().config.device_label;
    env.server_url   = dm::app().config.server_url;
    env.token        = dm::app().config.token[0] != '\0' ? dm::app().config.token : nullptr;
    env.work_dir     = DAEMOON_NX_WORK_DIR;
    env.clock_iso8601 = clock_iso8601;
    env.scratch      = dm::app().scratch;
    env.scratch_len  = dm::app().scratchLen;

    daemoon_nx_trace("app/ready", NULL);
    brls::Application::pushActivity(new dm::MainActivity());

    while (brls::Application::mainLoop())
        ;

    if (dm::app().titles != nullptr)
        env.save->free_titles(env.save_ctx, dm::app().titles, dm::app().count);

    daemoon_net_curl_exit();
    nsExit();
    accountExit();
    daemoon_nx_trace("app/exit", NULL);
    return EXIT_SUCCESS;
}
