/* GENERATED by tools/gen. DO NOT EDIT.
 * Source: shared/errors.json
 * Regenerate with: make gen
 */

#include <daemoon/result.h>
#include <daemoon/str_ids.h>

#include <string.h>

typedef struct {
    daemoon_result_t  result;
    const char       *code;
    daemoon_str_id_t  str_id;
    short             http;      /* 0 when the server never emits this code */
    unsigned char     retryable;
} daemoon_error_row_t;

static const daemoon_error_row_t k_errors[] = {
    { DAEMOON_ERR_INVALID_REQUEST, "invalid_request", DAEMOON_STR_ERR_INVALID_REQUEST, 400, 0 },
    { DAEMOON_ERR_INVALID_MANIFEST, "invalid_manifest", DAEMOON_STR_ERR_INVALID_MANIFEST, 400, 0 },
    { DAEMOON_ERR_UNSUPPORTED_PLATFORM, "unsupported_platform", DAEMOON_STR_ERR_UNSUPPORTED_PLATFORM, 400, 0 },
    { DAEMOON_ERR_UNAUTHORIZED, "unauthorized", DAEMOON_STR_ERR_UNAUTHORIZED, 401, 0 },
    { DAEMOON_ERR_DEVICE_REVOKED, "device_revoked", DAEMOON_STR_ERR_DEVICE_REVOKED, 401, 0 },
    { DAEMOON_ERR_FORBIDDEN, "forbidden", DAEMOON_STR_ERR_FORBIDDEN, 403, 0 },
    { DAEMOON_ERR_NOT_FOUND, "not_found", DAEMOON_STR_ERR_NOT_FOUND, 404, 0 },
    { DAEMOON_ERR_VERSION_CONFLICT, "version_conflict", DAEMOON_STR_ERR_VERSION_CONFLICT, 409, 0 },
    { DAEMOON_ERR_SHARE_EXPIRED, "share_expired", DAEMOON_STR_ERR_SHARE_EXPIRED, 410, 0 },
    { DAEMOON_ERR_PAIRING_EXPIRED, "pairing_expired", DAEMOON_STR_ERR_PAIRING_EXPIRED, 410, 0 },
    { DAEMOON_ERR_PAIRING_PENDING, "pairing_pending", DAEMOON_STR_ERR_PAIRING_PENDING, 400, 1 },
    { DAEMOON_ERR_SAVE_TOO_LARGE, "save_too_large", DAEMOON_STR_ERR_SAVE_TOO_LARGE, 413, 0 },
    { DAEMOON_ERR_CHECKSUM_MISMATCH, "checksum_mismatch", DAEMOON_STR_ERR_CHECKSUM_MISMATCH, 422, 0 },
    { DAEMOON_ERR_RATE_LIMITED, "rate_limited", DAEMOON_STR_ERR_RATE_LIMITED, 429, 1 },
    { DAEMOON_ERR_INTERNAL_ERROR, "internal_error", DAEMOON_STR_ERR_INTERNAL_ERROR, 500, 1 },
    { DAEMOON_ERR_IO_ERROR, "io_error", DAEMOON_STR_ERR_IO_ERROR, 0, 0 },
    { DAEMOON_ERR_OUT_OF_MEMORY, "out_of_memory", DAEMOON_STR_ERR_OUT_OF_MEMORY, 0, 0 },
    { DAEMOON_ERR_PARSE_ERROR, "parse_error", DAEMOON_STR_ERR_PARSE_ERROR, 0, 0 },
    { DAEMOON_ERR_NETWORK_ERROR, "network_error", DAEMOON_STR_ERR_NETWORK_ERROR, 0, 1 },
    { DAEMOON_ERR_TIMEOUT, "timeout", DAEMOON_STR_ERR_TIMEOUT, 0, 1 },
    { DAEMOON_ERR_BACKEND_ERROR, "backend_error", DAEMOON_STR_ERR_BACKEND_ERROR, 0, 0 },
    { DAEMOON_ERR_USER_CANCELLED, "user_cancelled", DAEMOON_STR_ERR_USER_CANCELLED, 0, 0 },
    { DAEMOON_ERR_NO_SPACE, "no_space", DAEMOON_STR_ERR_NO_SPACE, 0, 0 },
    { DAEMOON_ERR_UNSUPPORTED, "unsupported", DAEMOON_STR_ERR_UNSUPPORTED, 0, 0 },
    { DAEMOON_ERR_ARCHIVE_ERROR, "archive_error", DAEMOON_STR_ERR_ARCHIVE_ERROR, 0, 0 },
    { DAEMOON_ERR_BUFFER_TOO_SMALL, "buffer_too_small", DAEMOON_STR_ERR_BUFFER_TOO_SMALL, 0, 0 },
    { DAEMOON_ERR_EMPTY_SAVE, "empty_save", DAEMOON_STR_ERR_EMPTY_SAVE, 0, 0 },
    { DAEMOON_ERR_TLS_ERROR, "tls_error", DAEMOON_STR_ERR_TLS_ERROR, 0, 0 },
};

static const size_t k_error_count = sizeof(k_errors) / sizeof(k_errors[0]);

static const daemoon_error_row_t *find_row(daemoon_result_t r)
{
    size_t i;
    for (i = 0; i < k_error_count; ++i) {
        if (k_errors[i].result == r) {
            return &k_errors[i];
        }
    }
    return NULL;
}

const char *daemoon_result_code(daemoon_result_t r)
{
    const daemoon_error_row_t *row;
    if (r == DAEMOON_OK) {
        return "ok";
    }
    row = find_row(r);
    return row != NULL ? row->code : "internal_error";
}

daemoon_result_t daemoon_result_from_code(const char *code, size_t len)
{
    size_t i;
    if (code == NULL) {
        return DAEMOON_ERR_INTERNAL_ERROR;
    }
    if (len == 0) {
        len = strlen(code);
    }
    for (i = 0; i < k_error_count; ++i) {
        if (strlen(k_errors[i].code) == len &&
            memcmp(k_errors[i].code, code, len) == 0) {
            return k_errors[i].result;
        }
    }
    /* An unknown code from a newer server must not be mistaken for success. */
    return DAEMOON_ERR_INTERNAL_ERROR;
}

daemoon_str_id_t daemoon_result_str_id(daemoon_result_t r)
{
    const daemoon_error_row_t *row = find_row(r);
    return row != NULL ? row->str_id : DAEMOON_STR_ERR_INTERNAL_ERROR;
}

daemoon_result_t daemoon_result_from_http(int status, const char *code, size_t len)
{
    size_t i;
    if (status >= 200 && status < 300) {
        return DAEMOON_OK;
    }
    if (code != NULL && *code != '\0') {
        return daemoon_result_from_code(code, len);
    }
    /* No body, or a body the proxy replaced: fall back to the status. */
    for (i = 0; i < k_error_count; ++i) {
        if (k_errors[i].http == status) {
            return k_errors[i].result;
        }
    }
    return DAEMOON_ERR_INTERNAL_ERROR;
}

int daemoon_result_retryable(daemoon_result_t r)
{
    const daemoon_error_row_t *row = find_row(r);
    return row != NULL ? (int)row->retryable : 0;
}
