/* GENERATED by tools/gen. DO NOT EDIT.
 * Source: shared/lang/
 * Regenerate with: make gen
 */

#include <daemoon/i18n.h>

/* Indexed [language][string id]. English is index 0 and is the fallback for any
 * entry a translation has not filled in. */
const char *const daemoon_lang_table[DAEMOON_LANG_COUNT][DAEMOON_STR_COUNT] = {
    /* en */ {
        "DaeMoon", /* app.title */
        "Dates come from the console clock. They describe a backup; they never decide which save is newer.", /* backup.clock_note */
        "Backing up the current save", /* backup.creating */
        "The backup was deleted. The save on the console was not touched.", /* backup.deleted */
        "Local backup failed. Nothing was changed.", /* backup.failed */
        "Backups of {0}", /* backup.list */
        "date unknown", /* backup.no_date */
        "No backup of {0} yet.", /* backup.none */
        "same as the save on the console now", /* backup.same_as_console */
        "Cancel", /* btn.cancel */
        "No", /* btn.no */
        "OK", /* btn.ok */
        "Yes", /* btn.yes */
        "The save could not be committed. Do not launch the game until this is resolved.", /* commit.failed */
        "Back up the save for {0} to the SD card?", /* confirm.backup */
        "Delete this backup? The save on the console is not touched.", /* confirm.delete_backup */
        "Restore {0} to this console? A local backup is made first.", /* confirm.restore */
        "Upload the save for {0} to the server?", /* confirm.upload */
        "{0} was also changed on another device. Both versions are kept. Choose which one to use now.", /* conflict.explain */
        "Keep both and decide later", /* conflict.keep_both */
        "Keep this console's save ({0}, saved on {1})", /* conflict.keep_local */
        "Keep the server save ({0}, from {1})", /* conflict.keep_server */
        "Conflicting saves", /* conflict.title */
        "The save package is damaged.", /* err.archive_error */
        "The console refused the save operation.", /* err.backend_error */
        "Internal buffer too small.", /* err.buffer_too_small */
        "The downloaded save is damaged.", /* err.checksum_mismatch */
        "Access for this console was revoked. Pair it again.", /* err.device_revoked */
        "This title has no save data to back up.", /* err.empty_save */
        "This save does not belong to this account.", /* err.forbidden */
        "The server ran into a problem.", /* err.internal_error */
        "The save package is not readable.", /* err.invalid_manifest */
        "The server rejected the request.", /* err.invalid_request */
        "Could not read or write the save.", /* err.io_error */
        "Could not reach the server.", /* err.network_error */
        "Not enough space on the SD card.", /* err.no_space */
        "Not found on the server.", /* err.not_found */
        "Not enough memory.", /* err.out_of_memory */
        "The pairing code has expired. Start again.", /* err.pairing_expired */
        "Waiting for approval.", /* err.pairing_pending */
        "The data could not be read.", /* err.parse_error */
        "Too many requests. Try again shortly.", /* err.rate_limited */
        "The save is larger than the server allows.", /* err.save_too_large */
        "This share code has expired.", /* err.share_expired */
        "The server did not answer in time.", /* err.timeout */
        "The server's certificate could not be verified.", /* err.tls_error */
        "This console is not signed in. Pair it again.", /* err.unauthorized */
        "This is not supported.", /* err.unsupported */
        "This console is not supported by the server.", /* err.unsupported_platform */
        "Cancelled.", /* err.user_cancelled */
        "The server has a newer save. Choose which version to keep.", /* err.version_conflict */
        "English", /* lang.name */
        "Downloading", /* progress.downloading */
        "Packing save data", /* progress.packing */
        "Unpacking save data", /* progress.unpacking */
        "Uploading", /* progress.uploading */
        "Verifying", /* progress.verifying */
        "This console's name", /* settings.label */
        "The settings could not be written to the SD card.", /* settings.save_failed */
        "Saved. This console will use these from now on.", /* settings.saved */
        "Server address", /* settings.server */
        "Settings", /* settings.title */
        "Device token", /* settings.token */
        "not set", /* settings.unset */
        "Conflict", /* sync.action_conflict */
        "Download", /* sync.action_download */
        "Up to date", /* sync.action_none */
        "Upload", /* sync.action_upload */
        "Sync finished. {0} updated, {1} skipped.", /* sync.done */
        "{0} is already up to date.", /* sync.up_to_date */
        "Checksum does not match. The restore was aborted and nothing was changed.", /* verify.failed */
        "Running in applet mode with limited memory. Launch the app over a game to enable every feature.", /* warn.applet_mode */
        "Close the game before syncing. Syncing while a game is running corrupts the save.", /* warn.game_running */
        "{0} ties its save to this console. A save from another console may be deleted by the game.", /* warn.secure_value */
    },
    /* ko */ {
        "DaeMoon", /* app.title */
        "날짜는 본체 시계에서 옵니다. 백업을 설명할 뿐, 어느 세이브가 최신인지 결정하지 않습니다.", /* backup.clock_note */
        "현재 세이브를 백업하는 중", /* backup.creating */
        "백업을 삭제했습니다. 본체의 세이브는 건드리지 않았습니다.", /* backup.deleted */
        "로컬 백업에 실패했습니다. 변경된 내용은 없습니다.", /* backup.failed */
        "{0} 백업 목록", /* backup.list */
        "날짜 없음", /* backup.no_date */
        "{0}의 백업이 아직 없습니다.", /* backup.none */
        "지금 본체에 있는 세이브와 같음", /* backup.same_as_console */
        "취소", /* btn.cancel */
        "아니오", /* btn.no */
        "확인", /* btn.ok */
        "예", /* btn.yes */
        "세이브를 확정하지 못했습니다. 해결하기 전에는 게임을 실행하지 마세요.", /* commit.failed */
        "{0}의 세이브를 SD 카드에 백업할까요?", /* confirm.backup */
        "이 백업을 삭제할까요? 본체의 세이브는 건드리지 않습니다.", /* confirm.delete_backup */
        "{0}을(를) 이 본체에 복원할까요? 먼저 로컬 백업을 만듭니다.", /* confirm.restore */
        "{0}의 세이브를 서버에 업로드할까요?", /* confirm.upload */
        "{0}은(는) 다른 기기에서도 변경되었습니다. 두 버전 모두 보관합니다. 지금 사용할 쪽을 선택하세요.", /* conflict.explain */
        "둘 다 보관하고 나중에 결정", /* conflict.keep_both */
        "이 본체의 세이브 사용 ({0}, {1} 저장)", /* conflict.keep_local */
        "서버의 세이브 사용 ({0}, {1})", /* conflict.keep_server */
        "세이브 충돌", /* conflict.title */
        "세이브 패키지가 손상되었습니다.", /* err.archive_error */
        "본체가 세이브 작업을 거부했습니다.", /* err.backend_error */
        "내부 버퍼가 너무 작습니다.", /* err.buffer_too_small */
        "내려받은 세이브가 손상되었습니다.", /* err.checksum_mismatch */
        "이 본체의 접근 권한이 해제되었습니다. 다시 연결하세요.", /* err.device_revoked */
        "이 타이틀에는 백업할 세이브 데이터가 없습니다.", /* err.empty_save */
        "이 세이브는 이 계정의 것이 아닙니다.", /* err.forbidden */
        "서버에 문제가 발생했습니다.", /* err.internal_error */
        "세이브 패키지를 읽을 수 없습니다.", /* err.invalid_manifest */
        "서버가 요청을 거부했습니다.", /* err.invalid_request */
        "세이브를 읽거나 쓰지 못했습니다.", /* err.io_error */
        "서버에 연결하지 못했습니다.", /* err.network_error */
        "SD 카드 공간이 부족합니다.", /* err.no_space */
        "서버에서 찾을 수 없습니다.", /* err.not_found */
        "메모리가 부족합니다.", /* err.out_of_memory */
        "연결 코드가 만료되었습니다. 다시 시작하세요.", /* err.pairing_expired */
        "승인을 기다리는 중입니다.", /* err.pairing_pending */
        "데이터를 읽지 못했습니다.", /* err.parse_error */
        "요청이 너무 많습니다. 잠시 후 다시 시도하세요.", /* err.rate_limited */
        "세이브가 서버 허용 크기보다 큽니다.", /* err.save_too_large */
        "이 공유 코드는 만료되었습니다.", /* err.share_expired */
        "서버가 제때 응답하지 않았습니다.", /* err.timeout */
        "서버 인증서를 확인하지 못했습니다.", /* err.tls_error */
        "이 본체가 로그인되어 있지 않습니다. 다시 연결하세요.", /* err.unauthorized */
        "지원하지 않는 기능입니다.", /* err.unsupported */
        "서버가 이 본체를 지원하지 않습니다.", /* err.unsupported_platform */
        "취소되었습니다.", /* err.user_cancelled */
        "서버에 더 새로운 세이브가 있습니다. 사용할 버전을 선택하세요.", /* err.version_conflict */
        "한국어", /* lang.name */
        "다운로드 중", /* progress.downloading */
        "세이브 데이터 압축 중", /* progress.packing */
        "세이브 데이터 푸는 중", /* progress.unpacking */
        "업로드 중", /* progress.uploading */
        "검증 중", /* progress.verifying */
        "이 본체의 이름", /* settings.label */
        "설정을 SD 카드에 쓰지 못했습니다.", /* settings.save_failed */
        "저장했습니다. 이제부터 이 설정을 사용합니다.", /* settings.saved */
        "서버 주소", /* settings.server */
        "설정", /* settings.title */
        "기기 토큰", /* settings.token */
        "설정 안 됨", /* settings.unset */
        "충돌", /* sync.action_conflict */
        "다운로드", /* sync.action_download */
        "최신 상태", /* sync.action_none */
        "업로드", /* sync.action_upload */
        "동기화를 마쳤습니다. {0}개 갱신, {1}개 건너뜀.", /* sync.done */
        "{0}은(는) 이미 최신 상태입니다.", /* sync.up_to_date */
        "체크섬이 일치하지 않습니다. 복원을 중단했으며 변경된 내용은 없습니다.", /* verify.failed */
        "메모리가 제한된 애플릿 모드입니다. 모든 기능을 쓰려면 게임 위에서 실행하세요.", /* warn.applet_mode */
        "동기화 전에 게임을 종료하세요. 게임 실행 중 동기화하면 세이브가 손상됩니다.", /* warn.game_running */
        "{0}은(는) 세이브를 이 본체에 묶습니다. 다른 본체의 세이브는 게임이 삭제할 수 있습니다.", /* warn.secure_value */
    },
    /* ja */ {
        "DaeMoon", /* app.title */
        "日付は本体の時計によるものです。バックアップの説明にすぎず、どちらが新しいかを決めることはありません。", /* backup.clock_note */
        "現在のセーブをバックアップ中", /* backup.creating */
        "バックアップを削除しました。本体のセーブデータは変更していません。", /* backup.deleted */
        "ローカルバックアップに失敗しました。変更はありません。", /* backup.failed */
        "{0} のバックアップ", /* backup.list */
        "日付なし", /* backup.no_date */
        "{0} のバックアップはまだありません。", /* backup.none */
        "今、本体にあるセーブデータと同じ", /* backup.same_as_console */
        "キャンセル", /* btn.cancel */
        "いいえ", /* btn.no */
        "OK", /* btn.ok */
        "はい", /* btn.yes */
        "セーブを確定できませんでした。解決するまでゲームを起動しないでください。", /* commit.failed */
        "{0} のセーブデータを SD カードにバックアップしますか？", /* confirm.backup */
        "このバックアップを削除しますか？本体のセーブデータは変更しません。", /* confirm.delete_backup */
        "{0} をこの本体に復元しますか？先にローカルバックアップを作成します。", /* confirm.restore */
        "{0} のセーブをサーバーにアップロードしますか？", /* confirm.upload */
        "{0} は別の端末でも変更されています。両方のバージョンを保持します。今使う方を選んでください。", /* conflict.explain */
        "両方残して後で決める", /* conflict.keep_both */
        "この本体のセーブを使う（{0}、{1} 保存）", /* conflict.keep_local */
        "サーバーのセーブを使う（{0}、{1}）", /* conflict.keep_server */
        "セーブの競合", /* conflict.title */
        "セーブパッケージが壊れています。", /* err.archive_error */
        "本体がセーブ操作を拒否しました。", /* err.backend_error */
        "内部バッファが小さすぎます。", /* err.buffer_too_small */
        "ダウンロードしたセーブが壊れています。", /* err.checksum_mismatch */
        "この本体のアクセスは取り消されました。もう一度ペアリングしてください。", /* err.device_revoked */
        "このタイトルにはバックアップするセーブデータがありません。", /* err.empty_save */
        "このセーブはこのアカウントのものではありません。", /* err.forbidden */
        "サーバーで問題が発生しました。", /* err.internal_error */
        "セーブパッケージを読み取れません。", /* err.invalid_manifest */
        "サーバーがリクエストを拒否しました。", /* err.invalid_request */
        "セーブの読み書きができませんでした。", /* err.io_error */
        "サーバーに接続できませんでした。", /* err.network_error */
        "SD カードの空き容量が足りません。", /* err.no_space */
        "サーバー上に見つかりません。", /* err.not_found */
        "メモリが足りません。", /* err.out_of_memory */
        "ペアリングコードの期限が切れました。最初からやり直してください。", /* err.pairing_expired */
        "承認を待っています。", /* err.pairing_pending */
        "データを読み取れませんでした。", /* err.parse_error */
        "リクエストが多すぎます。しばらくして再試行してください。", /* err.rate_limited */
        "セーブがサーバーの上限を超えています。", /* err.save_too_large */
        "この共有コードは期限切れです。", /* err.share_expired */
        "サーバーが時間内に応答しませんでした。", /* err.timeout */
        "サーバーの証明書を確認できませんでした。", /* err.tls_error */
        "この本体はサインインしていません。もう一度ペアリングしてください。", /* err.unauthorized */
        "対応していません。", /* err.unsupported */
        "この本体はサーバーに対応していません。", /* err.unsupported_platform */
        "キャンセルしました。", /* err.user_cancelled */
        "サーバーに新しいセーブがあります。使うバージョンを選んでください。", /* err.version_conflict */
        "日本語", /* lang.name */
        "ダウンロード中", /* progress.downloading */
        "セーブデータを圧縮中", /* progress.packing */
        "セーブデータを展開中", /* progress.unpacking */
        "アップロード中", /* progress.uploading */
        "検証中", /* progress.verifying */
        "この本体の名前", /* settings.label */
        "設定を SD カードに書き込めませんでした。", /* settings.save_failed */
        "保存しました。これ以降はこの設定を使います。", /* settings.saved */
        "サーバーのアドレス", /* settings.server */
        "設定", /* settings.title */
        "本体のトークン", /* settings.token */
        "未設定", /* settings.unset */
        "競合", /* sync.action_conflict */
        "ダウンロード", /* sync.action_download */
        "最新", /* sync.action_none */
        "アップロード", /* sync.action_upload */
        "同期が終わりました。{0} 件更新、{1} 件スキップ。", /* sync.done */
        "{0} はすでに最新です。", /* sync.up_to_date */
        "チェックサムが一致しません。復元を中止し、変更はありません。", /* verify.failed */
        "メモリが制限されたアプレットモードです。すべての機能を使うにはゲーム上から起動してください。", /* warn.applet_mode */
        "同期の前にゲームを終了してください。ゲーム実行中の同期はセーブを壊します。", /* warn.game_running */
        "{0} はセーブをこの本体に紐付けます。他の本体のセーブはゲームに削除されることがあります。", /* warn.secure_value */
    },
    /* zh-Hans */ {
        "DaeMoon", /* app.title */
        "日期来自主机时钟，仅用于描述备份，绝不决定哪个存档更新。", /* backup.clock_note */
        "正在备份当前存档", /* backup.creating */
        "备份已删除。主机上的存档未被改动。", /* backup.deleted */
        "本地备份失败，未做任何更改。", /* backup.failed */
        "{0} 的备份", /* backup.list */
        "日期未知", /* backup.no_date */
        "还没有 {0} 的备份。", /* backup.none */
        "与主机上现在的存档相同", /* backup.same_as_console */
        "取消", /* btn.cancel */
        "否", /* btn.no */
        "确定", /* btn.ok */
        "是", /* btn.yes */
        "存档未能提交。问题解决前请不要启动游戏。", /* commit.failed */
        "把 {0} 的存档备份到 SD 卡？", /* confirm.backup */
        "删除这个备份？主机上的存档不会被改动。", /* confirm.delete_backup */
        "要把 {0} 恢复到本机吗？会先生成本地备份。", /* confirm.restore */
        "要把 {0} 的存档上传到服务器吗？", /* confirm.upload */
        "{0} 在另一台设备上也被修改过。两个版本都会保留。请选择现在使用哪一个。", /* conflict.explain */
        "都保留，稍后再决定", /* conflict.keep_both */
        "使用本机存档（{0}，保存于 {1}）", /* conflict.keep_local */
        "使用服务器存档（{0}，来自 {1}）", /* conflict.keep_server */
        "存档冲突", /* conflict.title */
        "存档包已损坏。", /* err.archive_error */
        "主机拒绝了该存档操作。", /* err.backend_error */
        "内部缓冲区过小。", /* err.buffer_too_small */
        "下载的存档已损坏。", /* err.checksum_mismatch */
        "本机的访问权限已被撤销，请重新配对。", /* err.device_revoked */
        "该标题没有可备份的存档。", /* err.empty_save */
        "该存档不属于此账号。", /* err.forbidden */
        "服务器出现问题。", /* err.internal_error */
        "无法读取存档包。", /* err.invalid_manifest */
        "服务器拒绝了该请求。", /* err.invalid_request */
        "无法读取或写入存档。", /* err.io_error */
        "无法连接服务器。", /* err.network_error */
        "SD 卡空间不足。", /* err.no_space */
        "服务器上找不到。", /* err.not_found */
        "内存不足。", /* err.out_of_memory */
        "配对码已过期，请重新开始。", /* err.pairing_expired */
        "正在等待批准。", /* err.pairing_pending */
        "无法读取数据。", /* err.parse_error */
        "请求过于频繁，请稍后再试。", /* err.rate_limited */
        "存档超过服务器允许的大小。", /* err.save_too_large */
        "该分享码已过期。", /* err.share_expired */
        "服务器未在规定时间内响应。", /* err.timeout */
        "无法验证服务器证书。", /* err.tls_error */
        "本机尚未登录，请重新配对。", /* err.unauthorized */
        "不支持该操作。", /* err.unsupported */
        "服务器不支持该主机。", /* err.unsupported_platform */
        "已取消。", /* err.user_cancelled */
        "服务器上有更新的存档，请选择要保留的版本。", /* err.version_conflict */
        "简体中文", /* lang.name */
        "正在下载", /* progress.downloading */
        "正在打包存档", /* progress.packing */
        "正在解包存档", /* progress.unpacking */
        "正在上传", /* progress.uploading */
        "正在校验", /* progress.verifying */
        "这台主机的名称", /* settings.label */
        "无法把设置写入 SD 卡。", /* settings.save_failed */
        "已保存。此后将使用这些设置。", /* settings.saved */
        "服务器地址", /* settings.server */
        "设置", /* settings.title */
        "设备令牌", /* settings.token */
        "未设置", /* settings.unset */
        "冲突", /* sync.action_conflict */
        "下载", /* sync.action_download */
        "已是最新", /* sync.action_none */
        "上传", /* sync.action_upload */
        "同步完成。已更新 {0} 个，跳过 {1} 个。", /* sync.done */
        "{0} 已是最新。", /* sync.up_to_date */
        "校验值不匹配。已中止恢复，未做任何更改。", /* verify.failed */
        "当前为内存受限的小程序模式。请在游戏之上启动本应用以使用全部功能。", /* warn.applet_mode */
        "同步前请先关闭游戏。游戏运行时同步会损坏存档。", /* warn.game_running */
        "{0} 会把存档绑定到本机。来自其他主机的存档可能被游戏删除。", /* warn.secure_value */
    },
    /* zh-Hant */ {
        "DaeMoon", /* app.title */
        "日期來自主機時鐘，僅用於描述備份，絕不決定哪個存檔較新。", /* backup.clock_note */
        "正在備份目前的存檔", /* backup.creating */
        "備份已刪除。主機上的存檔未被更動。", /* backup.deleted */
        "本機備份失敗，未做任何變更。", /* backup.failed */
        "{0} 的備份", /* backup.list */
        "日期不明", /* backup.no_date */
        "還沒有 {0} 的備份。", /* backup.none */
        "與主機上目前的存檔相同", /* backup.same_as_console */
        "取消", /* btn.cancel */
        "否", /* btn.no */
        "確定", /* btn.ok */
        "是", /* btn.yes */
        "存檔未能提交。問題解決前請勿啟動遊戲。", /* commit.failed */
        "把 {0} 的存檔備份到 SD 卡？", /* confirm.backup */
        "刪除這個備份？主機上的存檔不會被更動。", /* confirm.delete_backup */
        "要將 {0} 還原到本機嗎？會先建立本機備份。", /* confirm.restore */
        "要將 {0} 的存檔上傳到伺服器嗎？", /* confirm.upload */
        "{0} 在另一台裝置上也被修改過。兩個版本都會保留。請選擇現在要使用哪一個。", /* conflict.explain */
        "都保留，稍後再決定", /* conflict.keep_both */
        "使用本機存檔（{0}，儲存於 {1}）", /* conflict.keep_local */
        "使用伺服器存檔（{0}，來自 {1}）", /* conflict.keep_server */
        "存檔衝突", /* conflict.title */
        "存檔包已損壞。", /* err.archive_error */
        "主機拒絕了該存檔操作。", /* err.backend_error */
        "內部緩衝區過小。", /* err.buffer_too_small */
        "下載的存檔已損壞。", /* err.checksum_mismatch */
        "本機的存取權限已被撤銷，請重新配對。", /* err.device_revoked */
        "此標題沒有可備份的存檔。", /* err.empty_save */
        "該存檔不屬於此帳號。", /* err.forbidden */
        "伺服器發生問題。", /* err.internal_error */
        "無法讀取存檔包。", /* err.invalid_manifest */
        "伺服器拒絕了該請求。", /* err.invalid_request */
        "無法讀取或寫入存檔。", /* err.io_error */
        "無法連線到伺服器。", /* err.network_error */
        "SD 卡空間不足。", /* err.no_space */
        "伺服器上找不到。", /* err.not_found */
        "記憶體不足。", /* err.out_of_memory */
        "配對碼已過期，請重新開始。", /* err.pairing_expired */
        "正在等待核准。", /* err.pairing_pending */
        "無法讀取資料。", /* err.parse_error */
        "請求過於頻繁，請稍後再試。", /* err.rate_limited */
        "存檔超過伺服器允許的大小。", /* err.save_too_large */
        "此分享碼已過期。", /* err.share_expired */
        "伺服器未在時間內回應。", /* err.timeout */
        "無法驗證伺服器憑證。", /* err.tls_error */
        "本機尚未登入，請重新配對。", /* err.unauthorized */
        "不支援此操作。", /* err.unsupported */
        "伺服器不支援這台主機。", /* err.unsupported_platform */
        "已取消。", /* err.user_cancelled */
        "伺服器上有較新的存檔，請選擇要保留的版本。", /* err.version_conflict */
        "繁體中文", /* lang.name */
        "正在下載", /* progress.downloading */
        "正在封裝存檔", /* progress.packing */
        "正在解開存檔", /* progress.unpacking */
        "正在上傳", /* progress.uploading */
        "正在驗證", /* progress.verifying */
        "這台主機的名稱", /* settings.label */
        "無法將設定寫入 SD 卡。", /* settings.save_failed */
        "已儲存。此後將使用這些設定。", /* settings.saved */
        "伺服器位址", /* settings.server */
        "設定", /* settings.title */
        "裝置權杖", /* settings.token */
        "未設定", /* settings.unset */
        "衝突", /* sync.action_conflict */
        "下載", /* sync.action_download */
        "已是最新", /* sync.action_none */
        "上傳", /* sync.action_upload */
        "同步完成。已更新 {0} 個，略過 {1} 個。", /* sync.done */
        "{0} 已是最新。", /* sync.up_to_date */
        "校驗值不符。已中止還原，未做任何變更。", /* verify.failed */
        "目前為記憶體受限的小程式模式。請在遊戲之上啟動本程式以使用完整功能。", /* warn.applet_mode */
        "同步前請先關閉遊戲。遊戲執行中同步會損壞存檔。", /* warn.game_running */
        "{0} 會將存檔綁定到本機。來自其他主機的存檔可能被遊戲刪除。", /* warn.secure_value */
    },
    /* es */ {
        "DaeMoon", /* app.title */
        "Las fechas vienen del reloj de la consola. Describen una copia; nunca deciden qué partida es más reciente.", /* backup.clock_note */
        "Creando copia de seguridad de la partida actual", /* backup.creating */
        "La copia de seguridad se ha eliminado. No se ha tocado la partida de la consola.", /* backup.deleted */
        "La copia de seguridad local ha fallado. No se ha cambiado nada.", /* backup.failed */
        "Copias de seguridad de {0}", /* backup.list */
        "fecha desconocida", /* backup.no_date */
        "Todavía no hay ninguna copia de seguridad de {0}.", /* backup.none */
        "igual que la partida que hay ahora en la consola", /* backup.same_as_console */
        "Cancelar", /* btn.cancel */
        "No", /* btn.no */
        "Aceptar", /* btn.ok */
        "Sí", /* btn.yes */
        "No se ha podido confirmar la partida. No inicies el juego hasta resolverlo.", /* commit.failed */
        "¿Hacer una copia de seguridad de la partida de {0} en la tarjeta SD?", /* confirm.backup */
        "¿Eliminar esta copia de seguridad? No se toca la partida de la consola.", /* confirm.delete_backup */
        "¿Restaurar {0} en esta consola? Primero se crea una copia de seguridad local.", /* confirm.restore */
        "¿Subir la partida de {0} al servidor?", /* confirm.upload */
        "{0} también se ha modificado en otro dispositivo. Se conservan ambas versiones. Elige cuál usar ahora.", /* conflict.explain */
        "Conservar ambas y decidir más tarde", /* conflict.keep_both */
        "Usar la partida de esta consola ({0}, guardada el {1})", /* conflict.keep_local */
        "Usar la partida del servidor ({0}, del {1})", /* conflict.keep_server */
        "Partidas en conflicto", /* conflict.title */
        "El paquete de la partida está dañado.", /* err.archive_error */
        "La consola ha rechazado la operación sobre la partida.", /* err.backend_error */
        "Búfer interno demasiado pequeño.", /* err.buffer_too_small */
        "La partida descargada está dañada.", /* err.checksum_mismatch */
        "Se ha revocado el acceso de esta consola. Vuelve a vincularla.", /* err.device_revoked */
        "Este título no tiene partida que copiar.", /* err.empty_save */
        "Esta partida no pertenece a esta cuenta.", /* err.forbidden */
        "El servidor ha tenido un problema.", /* err.internal_error */
        "No se puede leer el paquete de la partida.", /* err.invalid_manifest */
        "El servidor ha rechazado la petición.", /* err.invalid_request */
        "No se ha podido leer o escribir la partida.", /* err.io_error */
        "No se ha podido conectar con el servidor.", /* err.network_error */
        "No hay espacio suficiente en la tarjeta SD.", /* err.no_space */
        "No se ha encontrado en el servidor.", /* err.not_found */
        "Memoria insuficiente.", /* err.out_of_memory */
        "El código de vinculación ha caducado. Empieza de nuevo.", /* err.pairing_expired */
        "Esperando la aprobación.", /* err.pairing_pending */
        "No se han podido leer los datos.", /* err.parse_error */
        "Demasiadas peticiones. Inténtalo de nuevo en un momento.", /* err.rate_limited */
        "La partida supera el tamaño permitido por el servidor.", /* err.save_too_large */
        "Este código de compartición ha caducado.", /* err.share_expired */
        "El servidor no ha respondido a tiempo.", /* err.timeout */
        "No se ha podido verificar el certificado del servidor.", /* err.tls_error */
        "Esta consola no ha iniciado sesión. Vuelve a vincularla.", /* err.unauthorized */
        "No es compatible.", /* err.unsupported */
        "El servidor no admite esta consola.", /* err.unsupported_platform */
        "Cancelado.", /* err.user_cancelled */
        "El servidor tiene una partida más reciente. Elige qué versión conservar.", /* err.version_conflict */
        "Español", /* lang.name */
        "Descargando", /* progress.downloading */
        "Empaquetando la partida", /* progress.packing */
        "Extrayendo la partida", /* progress.unpacking */
        "Subiendo", /* progress.uploading */
        "Verificando", /* progress.verifying */
        "Nombre de esta consola", /* settings.label */
        "No se han podido escribir los ajustes en la tarjeta SD.", /* settings.save_failed */
        "Guardado. Esta consola usará estos ajustes a partir de ahora.", /* settings.saved */
        "Dirección del servidor", /* settings.server */
        "Ajustes", /* settings.title */
        "Token del dispositivo", /* settings.token */
        "sin definir", /* settings.unset */
        "Conflicto", /* sync.action_conflict */
        "Descargar", /* sync.action_download */
        "Al día", /* sync.action_none */
        "Subir", /* sync.action_upload */
        "Sincronización terminada. {0} actualizados, {1} omitidos.", /* sync.done */
        "{0} ya está al día.", /* sync.up_to_date */
        "La suma de verificación no coincide. La restauración se ha cancelado y no se ha cambiado nada.", /* verify.failed */
        "En modo applet con memoria limitada. Abre la aplicación desde un juego para tener todas las funciones.", /* warn.applet_mode */
        "Cierra el juego antes de sincronizar. Sincronizar con el juego abierto daña la partida.", /* warn.game_running */
        "{0} vincula su partida a esta consola. El juego puede borrar una partida de otra consola.", /* warn.secure_value */
    },
    /* fr */ {
        "DaeMoon", /* app.title */
        "Les dates viennent de l'horloge de la console. Elles décrivent une sauvegarde ; elles ne décident jamais laquelle est la plus récente.", /* backup.clock_note */
        "Sauvegarde locale de la partie en cours", /* backup.creating */
        "La sauvegarde a été supprimée. La partie sur la console n'a pas été touchée.", /* backup.deleted */
        "La sauvegarde locale a échoué. Rien n'a été modifié.", /* backup.failed */
        "Sauvegardes de {0}", /* backup.list */
        "date inconnue", /* backup.no_date */
        "Aucune sauvegarde de {0} pour l'instant.", /* backup.none */
        "identique à la partie actuellement sur la console", /* backup.same_as_console */
        "Annuler", /* btn.cancel */
        "Non", /* btn.no */
        "OK", /* btn.ok */
        "Oui", /* btn.yes */
        "La sauvegarde n'a pas pu être validée. Ne lancez pas le jeu avant d'avoir résolu ce problème.", /* commit.failed */
        "Sauvegarder la partie de {0} sur la carte SD ?", /* confirm.backup */
        "Supprimer cette sauvegarde ? La partie sur la console n'est pas touchée.", /* confirm.delete_backup */
        "Restaurer {0} sur cette console ? Une sauvegarde locale est créée d'abord.", /* confirm.restore */
        "Envoyer la sauvegarde de {0} vers le serveur ?", /* confirm.upload */
        "{0} a aussi été modifié sur un autre appareil. Les deux versions sont conservées. Choisissez celle à utiliser maintenant.", /* conflict.explain */
        "Tout conserver et décider plus tard", /* conflict.keep_both */
        "Utiliser la sauvegarde de cette console ({0}, enregistrée le {1})", /* conflict.keep_local */
        "Utiliser la sauvegarde du serveur ({0}, du {1})", /* conflict.keep_server */
        "Sauvegardes en conflit", /* conflict.title */
        "Le paquet de sauvegarde est endommagé.", /* err.archive_error */
        "La console a refusé l'opération sur la sauvegarde.", /* err.backend_error */
        "Tampon interne trop petit.", /* err.buffer_too_small */
        "La sauvegarde téléchargée est endommagée.", /* err.checksum_mismatch */
        "L'accès de cette console a été révoqué. Associez-la de nouveau.", /* err.device_revoked */
        "Ce titre n'a aucune sauvegarde à copier.", /* err.empty_save */
        "Cette sauvegarde n'appartient pas à ce compte.", /* err.forbidden */
        "Le serveur a rencontré un problème.", /* err.internal_error */
        "Le paquet de sauvegarde est illisible.", /* err.invalid_manifest */
        "Le serveur a rejeté la requête.", /* err.invalid_request */
        "Impossible de lire ou d'écrire la sauvegarde.", /* err.io_error */
        "Impossible de joindre le serveur.", /* err.network_error */
        "Espace insuffisant sur la carte SD.", /* err.no_space */
        "Introuvable sur le serveur.", /* err.not_found */
        "Mémoire insuffisante.", /* err.out_of_memory */
        "Le code d'association a expiré. Recommencez.", /* err.pairing_expired */
        "En attente d'approbation.", /* err.pairing_pending */
        "Les données n'ont pas pu être lues.", /* err.parse_error */
        "Trop de requêtes. Réessayez dans un instant.", /* err.rate_limited */
        "La sauvegarde dépasse la taille autorisée par le serveur.", /* err.save_too_large */
        "Ce code de partage a expiré.", /* err.share_expired */
        "Le serveur n'a pas répondu à temps.", /* err.timeout */
        "Le certificat du serveur n'a pas pu être vérifié.", /* err.tls_error */
        "Cette console n'est pas connectée. Associez-la de nouveau.", /* err.unauthorized */
        "Non pris en charge.", /* err.unsupported */
        "Cette console n'est pas prise en charge par le serveur.", /* err.unsupported_platform */
        "Annulé.", /* err.user_cancelled */
        "Le serveur a une sauvegarde plus récente. Choisissez la version à conserver.", /* err.version_conflict */
        "Français", /* lang.name */
        "Téléchargement en cours", /* progress.downloading */
        "Compression de la sauvegarde", /* progress.packing */
        "Extraction de la sauvegarde", /* progress.unpacking */
        "Envoi en cours", /* progress.uploading */
        "Vérification", /* progress.verifying */
        "Nom de cette console", /* settings.label */
        "Impossible d'écrire les réglages sur la carte SD.", /* settings.save_failed */
        "Enregistré. Cette console utilisera ces réglages désormais.", /* settings.saved */
        "Adresse du serveur", /* settings.server */
        "Réglages", /* settings.title */
        "Jeton de l'appareil", /* settings.token */
        "non défini", /* settings.unset */
        "Conflit", /* sync.action_conflict */
        "Télécharger", /* sync.action_download */
        "À jour", /* sync.action_none */
        "Envoyer", /* sync.action_upload */
        "Synchronisation terminée. {0} mis à jour, {1} ignorés.", /* sync.done */
        "{0} est déjà à jour.", /* sync.up_to_date */
        "La somme de contrôle ne correspond pas. La restauration a été annulée et rien n'a été modifié.", /* verify.failed */
        "Mode applet avec mémoire limitée. Lancez l'application depuis un jeu pour accéder à toutes les fonctions.", /* warn.applet_mode */
        "Fermez le jeu avant de synchroniser. Synchroniser pendant une partie corrompt la sauvegarde.", /* warn.game_running */
        "{0} lie sa sauvegarde à cette console. Une sauvegarde venant d'une autre console peut être supprimée par le jeu.", /* warn.secure_value */
    },
    /* de */ {
        "DaeMoon", /* app.title */
        "Die Datumsangaben stammen von der Uhr der Konsole. Sie beschreiben eine Sicherung; sie entscheiden nie, welcher Spielstand neuer ist.", /* backup.clock_note */
        "Sicherung des aktuellen Spielstands wird erstellt", /* backup.creating */
        "Die Sicherung wurde gelöscht. Der Spielstand auf der Konsole blieb unberührt.", /* backup.deleted */
        "Lokale Sicherung fehlgeschlagen. Es wurde nichts geändert.", /* backup.failed */
        "Sicherungen von {0}", /* backup.list */
        "Datum unbekannt", /* backup.no_date */
        "Noch keine Sicherung von {0}.", /* backup.none */
        "identisch mit dem Spielstand, der jetzt auf der Konsole liegt", /* backup.same_as_console */
        "Abbrechen", /* btn.cancel */
        "Nein", /* btn.no */
        "OK", /* btn.ok */
        "Ja", /* btn.yes */
        "Der Spielstand konnte nicht festgeschrieben werden. Starte das Spiel erst, wenn das behoben ist.", /* commit.failed */
        "Den Spielstand von {0} auf die SD-Karte sichern?", /* confirm.backup */
        "Diese Sicherung löschen? Der Spielstand auf der Konsole bleibt unberührt.", /* confirm.delete_backup */
        "{0} auf dieser Konsole wiederherstellen? Zuvor wird eine lokale Sicherung erstellt.", /* confirm.restore */
        "Spielstand von {0} auf den Server hochladen?", /* confirm.upload */
        "{0} wurde auch auf einem anderen Gerät geändert. Beide Fassungen bleiben erhalten. Wähle, welche jetzt verwendet wird.", /* conflict.explain */
        "Beide behalten und später entscheiden", /* conflict.keep_both */
        "Spielstand dieser Konsole verwenden ({0}, gespeichert am {1})", /* conflict.keep_local */
        "Spielstand vom Server verwenden ({0}, vom {1})", /* conflict.keep_server */
        "Widersprüchliche Spielstände", /* conflict.title */
        "Das Spielstandpaket ist beschädigt.", /* err.archive_error */
        "Die Konsole hat den Zugriff auf den Spielstand abgelehnt.", /* err.backend_error */
        "Interner Puffer zu klein.", /* err.buffer_too_small */
        "Der heruntergeladene Spielstand ist beschädigt.", /* err.checksum_mismatch */
        "Der Zugriff dieser Konsole wurde entzogen. Koppel sie erneut.", /* err.device_revoked */
        "Dieser Titel hat keinen Spielstand zum Sichern.", /* err.empty_save */
        "Dieser Spielstand gehört nicht zu diesem Konto.", /* err.forbidden */
        "Auf dem Server ist ein Problem aufgetreten.", /* err.internal_error */
        "Das Spielstandpaket ist nicht lesbar.", /* err.invalid_manifest */
        "Der Server hat die Anfrage abgelehnt.", /* err.invalid_request */
        "Der Spielstand konnte nicht gelesen oder geschrieben werden.", /* err.io_error */
        "Der Server ist nicht erreichbar.", /* err.network_error */
        "Nicht genug Platz auf der SD-Karte.", /* err.no_space */
        "Auf dem Server nicht gefunden.", /* err.not_found */
        "Nicht genug Speicher.", /* err.out_of_memory */
        "Der Kopplungscode ist abgelaufen. Beginne von vorn.", /* err.pairing_expired */
        "Warten auf Bestätigung.", /* err.pairing_pending */
        "Die Daten konnten nicht gelesen werden.", /* err.parse_error */
        "Zu viele Anfragen. Versuche es gleich noch einmal.", /* err.rate_limited */
        "Der Spielstand ist größer als der Server erlaubt.", /* err.save_too_large */
        "Dieser Freigabecode ist abgelaufen.", /* err.share_expired */
        "Der Server hat nicht rechtzeitig geantwortet.", /* err.timeout */
        "Das Zertifikat des Servers konnte nicht geprüft werden.", /* err.tls_error */
        "Diese Konsole ist nicht angemeldet. Koppel sie erneut.", /* err.unauthorized */
        "Wird nicht unterstützt.", /* err.unsupported */
        "Diese Konsole wird vom Server nicht unterstützt.", /* err.unsupported_platform */
        "Abgebrochen.", /* err.user_cancelled */
        "Der Server hat einen neueren Spielstand. Wähle, welche Fassung bleibt.", /* err.version_conflict */
        "Deutsch", /* lang.name */
        "Wird heruntergeladen", /* progress.downloading */
        "Spielstand wird gepackt", /* progress.packing */
        "Spielstand wird entpackt", /* progress.unpacking */
        "Wird hochgeladen", /* progress.uploading */
        "Wird geprüft", /* progress.verifying */
        "Name dieser Konsole", /* settings.label */
        "Die Einstellungen konnten nicht auf die SD-Karte geschrieben werden.", /* settings.save_failed */
        "Gespeichert. Diese Konsole verwendet sie ab jetzt.", /* settings.saved */
        "Serveradresse", /* settings.server */
        "Einstellungen", /* settings.title */
        "Gerätetoken", /* settings.token */
        "nicht gesetzt", /* settings.unset */
        "Konflikt", /* sync.action_conflict */
        "Herunterladen", /* sync.action_download */
        "Aktuell", /* sync.action_none */
        "Hochladen", /* sync.action_upload */
        "Abgleich beendet. {0} aktualisiert, {1} übersprungen.", /* sync.done */
        "{0} ist bereits aktuell.", /* sync.up_to_date */
        "Die Prüfsumme stimmt nicht. Die Wiederherstellung wurde abgebrochen, es wurde nichts geändert.", /* verify.failed */
        "Applet-Modus mit stark begrenztem Speicher. Starte die Anwendung über ein Spiel, um alle Funktionen zu nutzen.", /* warn.applet_mode */
        "Beende das Spiel vor dem Abgleich. Ein Abgleich bei laufendem Spiel beschädigt den Spielstand.", /* warn.game_running */
        "{0} bindet seinen Spielstand an diese Konsole. Ein Spielstand von einer anderen Konsole kann vom Spiel gelöscht werden.", /* warn.secure_value */
    },
};

const char *const daemoon_lang_codes[DAEMOON_LANG_COUNT] = {
    "en",
    "ko",
    "ja",
    "zh-Hans",
    "zh-Hant",
    "es",
    "fr",
    "de",
};
