/* GENERATED by tools/gen. DO NOT EDIT.
 * Source: shared/lang/
 * Regenerate with: make gen
 */

#include <daemoon/i18n.h>

/* Indexed [language][string id]. English is index 0 and is the fallback for any
 * entry a translation has not filled in. */
const char *const daemoon_lang_table[DAEMOON_LANG_COUNT][DAEMOON_STR_COUNT] = {
    /* en */ {
        "DaeMoon", /* app.title */
        "Dates come from the console clock. They describe a backup; they never decide which save is newer.", /* backup.clock_note */
        "Backing up the current save", /* backup.creating */
        "The backup was deleted. The save on the console was not touched.", /* backup.deleted */
        "Local backup failed. Nothing was changed.", /* backup.failed */
        "Backups of {0}", /* backup.list */
        "date unknown", /* backup.no_date */
        "No backup of {0} yet.", /* backup.none */
        "same as the save on the console now", /* backup.same_as_console */
        "Back every save up to the SD card", /* batch.backup */
        "Backed up {0}, skipped {1}, failed {2}.", /* batch.backup_done */
        "Reads every save in this library and writes a package for each. Nothing on the console or the server is changed.", /* batch.backup_hint */
        "Back up all {0} saves in this library to the SD card?", /* batch.confirm_backup */
        "Sync all {0} titles? Where both sides changed: {1}", /* batch.confirm_sync */
        "Sync all {0} titles, taking the server's version wherever the two differ? Saves on this console will be overwritten. Each one is backed up to the SD card first.", /* batch.confirm_sync_server */
        "There is nothing in this library to work on.", /* batch.empty */
        "A start   up/down move   B back", /* batch.hint */
        "B stop after this title", /* batch.hint_running */
        "When both sides changed", /* batch.policy */
        "Ask me for each one", /* batch.policy_ask */
        "The same dialog a single title shows, once per title that differs. Right when a few differ, tiring when many do.", /* batch.policy_ask_hint */
        "Send this console's up", /* batch.policy_local */
        "This console's save goes on top as a new version. The server keeps everything it already had, so the other side is still there to go back to.", /* batch.policy_local_hint */
        "Take the server's down", /* batch.policy_server */
        "The server's save is written over this console's. Each one is backed up to the SD card first, so what is replaced is still on the card.", /* batch.policy_server_hint */
        "{0} of {1}", /* batch.running */
        "Stopped. Everything finished before this point is done and nothing was left half written.", /* batch.stopped */
        "Sync every title with the server", /* batch.sync */
        "Uploads what only this console changed and downloads what only the server changed. What happens when both changed is the next question.", /* batch.sync_hint */
        "All titles", /* batch.title */
        "Cancel", /* btn.cancel */
        "No", /* btn.no */
        "OK", /* btn.ok */
        "Yes", /* btn.yes */
        "The save could not be committed. Do not launch the game until this is resolved.", /* commit.failed */
        "Back up the save for {0} to the SD card?", /* confirm.backup */
        "Delete this backup? The save on the console is not touched.", /* confirm.delete_backup */
        "Restore {0} to this console? A local backup is made first.", /* confirm.restore */
        "Upload the save for {0} to the server?", /* confirm.upload */
        "{0} was also changed on another device. Both versions are kept. Choose which one to use now.", /* conflict.explain */
        "Keep both and decide later", /* conflict.keep_both */
        "Keep this console's save ({0}, saved on {1})", /* conflict.keep_local */
        "Keep the server save ({0}, from {1})", /* conflict.keep_server */
        "Conflicting saves", /* conflict.title */
        "The save package is damaged.", /* err.archive_error */
        "The console refused the save operation.", /* err.backend_error */
        "Internal buffer too small.", /* err.buffer_too_small */
        "The downloaded save is damaged.", /* err.checksum_mismatch */
        "Access for this console was revoked. Pair it again.", /* err.device_revoked */
        "This title has no save data to back up.", /* err.empty_save */
        "This save does not belong to this account.", /* err.forbidden */
        "The server ran into a problem.", /* err.internal_error */
        "The save package is not readable.", /* err.invalid_manifest */
        "The server rejected the request.", /* err.invalid_request */
        "Could not read or write the save.", /* err.io_error */
        "Could not reach the server.", /* err.network_error */
        "No server is set. Open Settings and enter the address and the token.", /* err.no_server */
        "Not enough space on the SD card.", /* err.no_space */
        "Not found on the server.", /* err.not_found */
        "Not enough memory.", /* err.out_of_memory */
        "The pairing code has expired. Start again.", /* err.pairing_expired */
        "Waiting for approval.", /* err.pairing_pending */
        "The data could not be read.", /* err.parse_error */
        "Too many requests. Try again shortly.", /* err.rate_limited */
        "The save is larger than the server allows.", /* err.save_too_large */
        "This share code has expired.", /* err.share_expired */
        "The server did not answer in time.", /* err.timeout */
        "The list of titles could not be read.", /* err.title_list */
        "The server's certificate could not be verified.", /* err.tls_error */
        "This console is not signed in. Pair it again.", /* err.unauthorized */
        "This is not supported.", /* err.unsupported */
        "This console is not supported by the server.", /* err.unsupported_platform */
        "Cancelled.", /* err.user_cancelled */
        "The server has a newer save. Choose which version to keep.", /* err.version_conflict */
        "No titles with save data were found.", /* grid.empty */
        "nothing selected", /* grid.nothing_selected */
        "{0} saves", /* grid.saves */
        "A restore   X delete   B back", /* hint.backups */
        "A select   B back   up/down move", /* hint.choose */
        "A continue", /* hint.continue */
        "A edit   B back   up/down move", /* hint.edit */
        "A back up   Y restore   X survey   L/R library   START exit", /* hint.grid */
        "English", /* lang.name */
        "3DS titles", /* lib.3ds */
        "nds-bootstrap saves", /* lib.nds */
        "Reading backups", /* loading.backups */
        "Reading icons", /* loading.icons */
        "Reading titles", /* loading.titles */
        "Back up this save", /* menu.backup */
        "All titles", /* menu.batch */
        "Restore from a backup", /* menu.restore */
        "Self test (destroys this save)", /* menu.selftest */
        "Settings", /* menu.settings */
        "Survey every title to the SD card", /* menu.survey */
        "Sync with the server", /* menu.sync */
        "Backup", /* op.backup */
        "Restore", /* op.restore */
        "Secure value", /* op.secure_value */
        "Survey", /* op.survey */
        "Sync", /* op.sync */
        "Point the camera at the code on the web page.   B cancel", /* pair.aim */
        "Paired. This console can sync now.", /* pair.done */
        "Type the six digit code shown on the web page.", /* pair.enter_code */
        "The camera could not be started.", /* pair.no_camera */
        "Set the server address first, or scan a code instead - a scanned code carries the address with it.", /* pair.no_server */
        "Scan a QR code", /* pair.scan */
        "L/R camera   X/Y preview mode   B cancel", /* pair.switch */
        "Pair this console", /* pair.title */
        "That is not a DaeMoon pairing code.", /* pair.wrong_code */
        "Downloading", /* progress.downloading */
        "Packing save data", /* progress.packing */
        "Unpacking save data", /* progress.unpacking */
        "Uploading", /* progress.uploading */
        "Verifying", /* progress.verifying */
        "{0} failed. {1}", /* report.failed */
        "{0}: done.", /* report.ok */
        "This build has no save archive of its own. Build it with SAVEDATA_SIZE=128K.", /* selftest.no_archive */
        "DaeMoon itself", /* selftest.self */
        "This DESTROYS the save of {0}. Use a dummy title. A backup is made first, but do not rely on it.", /* selftest.warning */
        "This console's name", /* settings.label */
        "Language", /* settings.language */
        "From the console ({0})", /* settings.language_auto */
        "This console has no font for {0}, so the text would be blank. The language was not changed.", /* settings.no_font */
        "The settings could not be written to the SD card.", /* settings.save_failed */
        "Saved. This console will use these from now on.", /* settings.saved */
        "Server address", /* settings.server */
        "Settings", /* settings.title */
        "Device token", /* settings.token */
        "not set", /* settings.unset */
        "Show the welcome again", /* settings.welcome */
        "Conflict", /* sync.action_conflict */
        "Download", /* sync.action_download */
        "Up to date", /* sync.action_none */
        "Upload", /* sync.action_upload */
        "Sync finished. {0} updated, {1} skipped.", /* sync.done */
        "{0} uploaded, {1} downloaded, {2} unchanged, {3} conflicts.", /* sync.result */
        "{0} is already up to date.", /* sync.up_to_date */
        "no secure value", /* title.no_secure_value */
        "secure value {0}", /* title.secure_value */
        "Checksum does not match. The restore was aborted and nothing was changed.", /* verify.failed */
        "Running in applet mode with limited memory. Launch the app over a game to enable every feature.", /* warn.applet_mode */
        "Close the game before syncing. Syncing while a game is running corrupts the save.", /* warn.game_running */
        "{0} ties its save to this console. A save from another console may be deleted by the game.", /* warn.secure_value */
        "Connect to your server", /* welcome.connect */
        "Sign in to the panel in a browser and press Add a console. It shows a code.", /* welcome.connect_how */
        "A select   up/down move   START skip", /* welcome.hint_choose */
        "A next   START skip", /* welcome.hint_intro */
        "Nothing is connected, and backing up to the SD card works anyway. Settings has the server and the pairing rows when you want them.", /* welcome.later */
        "Type the address and the code", /* welcome.opt_code */
        "For when the camera cannot read a screen. Two things to type on the keyboard, and it always works.", /* welcome.opt_code_hint */
        "Not now", /* welcome.opt_later */
        "Backing up to the SD card works without a server. Settings has this screen's choices whenever you want them.", /* welcome.opt_later_hint */
        "Scan the QR code", /* welcome.opt_qr */
        "Nothing to type. The code carries the server address with it, so this console needs no address set first.", /* welcome.opt_qr_hint */
        "This console is connected. Back one save up first and restore it, on a game you are not attached to, before trusting it with one you are.", /* welcome.ready */
        "A local backup is always made before anything is restored, and a conflict is never merged for you: both versions are kept and you choose.", /* welcome.safe */
        "Welcome", /* welcome.title */
        "DaeMoon copies this console's saves to a server you run, and brings them back. The same save on two consoles, without moving the card.", /* welcome.what */
        "Sync before you start a game or after you quit it, never while one is running. A game holds its save open, and writing to it then breaks it.", /* welcome.when */
    },
    /* ko */ {
        "DaeMoon", /* app.title */
        "날짜는 본체 시계에서 옵니다. 백업을 설명할 뿐, 어느 세이브가 최신인지 결정하지 않습니다.", /* backup.clock_note */
        "현재 세이브를 백업하는 중", /* backup.creating */
        "백업을 삭제했습니다. 본체의 세이브는 건드리지 않았습니다.", /* backup.deleted */
        "로컬 백업에 실패했습니다. 변경된 내용은 없습니다.", /* backup.failed */
        "{0} 백업 목록", /* backup.list */
        "날짜 없음", /* backup.no_date */
        "{0}의 백업이 아직 없습니다.", /* backup.none */
        "지금 본체에 있는 세이브와 같음", /* backup.same_as_console */
        "모든 세이브를 SD 카드에 백업", /* batch.backup */
        "백업 {0}개, 건너뜀 {1}개, 실패 {2}개.", /* batch.backup_done */
        "이 목록의 모든 세이브를 읽어 각각 패키지로 씁니다. 본체와 서버의 어떤 것도 바뀌지 않습니다.", /* batch.backup_hint */
        "이 목록의 세이브 {0}개를 모두 SD 카드에 백업할까요?", /* batch.confirm_backup */
        "타이틀 {0}개를 모두 동기화할까요? 양쪽 다 바뀐 경우: {1}", /* batch.confirm_sync */
        "타이틀 {0}개를 모두 동기화하고, 다른 것은 서버 버전을 받을까요? 이 본체의 세이브를 덮어씁니다. 덮기 전에 하나씩 SD 카드에 백업합니다.", /* batch.confirm_sync_server */
        "이 목록에는 작업할 것이 없습니다.", /* batch.empty */
        "A 시작   위/아래 이동   B 뒤로", /* batch.hint */
        "B 이 타이틀까지 하고 중단", /* batch.hint_running */
        "양쪽 다 바뀌었을 때", /* batch.policy */
        "하나씩 물어보기", /* batch.policy_ask */
        "타이틀 하나를 동기화할 때 나오는 그 대화상자를, 다른 것마다 한 번씩 띄웁니다. 몇 개일 때는 이게 맞고, 많으면 지칩니다.", /* batch.policy_ask_hint */
        "이 본체 것을 올리기", /* batch.policy_local */
        "이 본체의 세이브가 새 버전으로 올라갑니다. 서버는 가지고 있던 것을 모두 그대로 두므로, 반대쪽도 언제든 되돌아갈 수 있습니다.", /* batch.policy_local_hint */
        "서버 것을 받기", /* batch.policy_server */
        "서버의 세이브를 이 본체 위에 씁니다. 하나하나 먼저 SD 카드에 백업하므로, 덮인 것은 카드에 그대로 남습니다.", /* batch.policy_server_hint */
        "{1}개 중 {0}개", /* batch.running */
        "중단했습니다. 그 전까지 끝난 것은 그대로 완료됐고, 반쯤 쓰인 것은 없습니다.", /* batch.stopped */
        "모든 타이틀을 서버와 동기화", /* batch.sync */
        "이 본체만 바뀐 것은 올리고, 서버만 바뀐 것은 받습니다. 양쪽 다 바뀐 경우를 어떻게 할지는 다음에 묻습니다.", /* batch.sync_hint */
        "일괄 작업", /* batch.title */
        "취소", /* btn.cancel */
        "아니오", /* btn.no */
        "확인", /* btn.ok */
        "예", /* btn.yes */
        "세이브를 확정하지 못했습니다. 해결하기 전에는 게임을 실행하지 마세요.", /* commit.failed */
        "{0}의 세이브를 SD 카드에 백업할까요?", /* confirm.backup */
        "이 백업을 삭제할까요? 본체의 세이브는 건드리지 않습니다.", /* confirm.delete_backup */
        "{0}을(를) 이 본체에 복원할까요? 먼저 로컬 백업을 만듭니다.", /* confirm.restore */
        "{0}의 세이브를 서버에 업로드할까요?", /* confirm.upload */
        "{0}은(는) 다른 기기에서도 변경되었습니다. 두 버전 모두 보관합니다. 지금 사용할 쪽을 선택하세요.", /* conflict.explain */
        "둘 다 보관하고 나중에 결정", /* conflict.keep_both */
        "이 본체의 세이브 사용 ({0}, {1} 저장)", /* conflict.keep_local */
        "서버의 세이브 사용 ({0}, {1})", /* conflict.keep_server */
        "세이브 충돌", /* conflict.title */
        "세이브 패키지가 손상되었습니다.", /* err.archive_error */
        "본체가 세이브 작업을 거부했습니다.", /* err.backend_error */
        "내부 버퍼가 너무 작습니다.", /* err.buffer_too_small */
        "내려받은 세이브가 손상되었습니다.", /* err.checksum_mismatch */
        "이 본체의 접근 권한이 해제되었습니다. 다시 연결하세요.", /* err.device_revoked */
        "이 타이틀에는 백업할 세이브 데이터가 없습니다.", /* err.empty_save */
        "이 세이브는 이 계정의 것이 아닙니다.", /* err.forbidden */
        "서버에 문제가 발생했습니다.", /* err.internal_error */
        "세이브 패키지를 읽을 수 없습니다.", /* err.invalid_manifest */
        "서버가 요청을 거부했습니다.", /* err.invalid_request */
        "세이브를 읽거나 쓰지 못했습니다.", /* err.io_error */
        "서버에 연결하지 못했습니다.", /* err.network_error */
        "서버가 설정되지 않았습니다. 설정에서 주소와 토큰을 입력하세요.", /* err.no_server */
        "SD 카드 공간이 부족합니다.", /* err.no_space */
        "서버에서 찾을 수 없습니다.", /* err.not_found */
        "메모리가 부족합니다.", /* err.out_of_memory */
        "연결 코드가 만료되었습니다. 다시 시작하세요.", /* err.pairing_expired */
        "승인을 기다리는 중입니다.", /* err.pairing_pending */
        "데이터를 읽지 못했습니다.", /* err.parse_error */
        "요청이 너무 많습니다. 잠시 후 다시 시도하세요.", /* err.rate_limited */
        "세이브가 서버 허용 크기보다 큽니다.", /* err.save_too_large */
        "이 공유 코드는 만료되었습니다.", /* err.share_expired */
        "서버가 제때 응답하지 않았습니다.", /* err.timeout */
        "타이틀 목록을 읽지 못했습니다.", /* err.title_list */
        "서버 인증서를 확인하지 못했습니다.", /* err.tls_error */
        "이 본체가 로그인되어 있지 않습니다. 다시 연결하세요.", /* err.unauthorized */
        "지원하지 않는 기능입니다.", /* err.unsupported */
        "서버가 이 본체를 지원하지 않습니다.", /* err.unsupported_platform */
        "취소되었습니다.", /* err.user_cancelled */
        "서버에 더 새로운 세이브가 있습니다. 사용할 버전을 선택하세요.", /* err.version_conflict */
        "세이브 데이터가 있는 타이틀을 찾지 못했습니다.", /* grid.empty */
        "선택된 항목 없음", /* grid.nothing_selected */
        "세이브 {0}개", /* grid.saves */
        "A 복원   X 삭제   B 뒤로", /* hint.backups */
        "A 선택   B 뒤로   위/아래 이동", /* hint.choose */
        "A 계속", /* hint.continue */
        "A 편집   B 뒤로   위/아래 이동", /* hint.edit */
        "A 백업   Y 복원   X 조사   L/R 라이브러리   START 종료", /* hint.grid */
        "한국어", /* lang.name */
        "3DS 타이틀", /* lib.3ds */
        "nds-bootstrap 세이브", /* lib.nds */
        "백업 읽는 중", /* loading.backups */
        "아이콘 읽는 중", /* loading.icons */
        "타이틀 목록 읽는 중", /* loading.titles */
        "이 세이브 백업", /* menu.backup */
        "일괄 작업", /* menu.batch */
        "백업에서 복원", /* menu.restore */
        "자체 검사 (이 세이브를 파괴함)", /* menu.selftest */
        "설정", /* menu.settings */
        "모든 타이틀 조사해 SD 카드에 기록", /* menu.survey */
        "서버와 동기화", /* menu.sync */
        "백업", /* op.backup */
        "복원", /* op.restore */
        "보안 값", /* op.secure_value */
        "조사", /* op.survey */
        "동기화", /* op.sync */
        "웹 페이지의 코드에 카메라를 맞추세요.   B 취소", /* pair.aim */
        "연결됐습니다. 이제 동기화할 수 있습니다.", /* pair.done */
        "웹 페이지에 표시된 여섯 자리 코드를 입력하세요.", /* pair.enter_code */
        "카메라를 시작하지 못했습니다.", /* pair.no_camera */
        "먼저 서버 주소를 설정하거나, QR 코드를 스캔하세요. 스캔한 코드에는 주소가 함께 들어 있습니다.", /* pair.no_server */
        "QR 코드 스캔", /* pair.scan */
        "L/R 카메라   X/Y 프리뷰 모드   B 취소", /* pair.switch */
        "이 본체 연결", /* pair.title */
        "DaeMoon 연결 코드가 아닙니다.", /* pair.wrong_code */
        "다운로드 중", /* progress.downloading */
        "세이브 데이터 압축 중", /* progress.packing */
        "세이브 데이터 푸는 중", /* progress.unpacking */
        "업로드 중", /* progress.uploading */
        "검증 중", /* progress.verifying */
        "{0} 실패. {1}", /* report.failed */
        "{0}: 완료했습니다.", /* report.ok */
        "이 빌드에는 자체 세이브 아카이브가 없습니다. SAVEDATA_SIZE=128K로 빌드하세요.", /* selftest.no_archive */
        "DaeMoon 자신", /* selftest.self */
        "{0}의 세이브를 파괴합니다. 더미 타이틀에만 사용하세요. 백업을 먼저 만들지만 그것에 의존하지 마세요.", /* selftest.warning */
        "이 본체의 이름", /* settings.label */
        "언어", /* settings.language */
        "본체 설정 따름 ({0})", /* settings.language_auto */
        "이 본체에는 {0} 글꼴이 없어 글자가 비어 보입니다. 언어를 바꾸지 않았습니다.", /* settings.no_font */
        "설정을 SD 카드에 쓰지 못했습니다.", /* settings.save_failed */
        "저장했습니다. 이제부터 이 설정을 사용합니다.", /* settings.saved */
        "서버 주소", /* settings.server */
        "설정", /* settings.title */
        "기기 토큰", /* settings.token */
        "설정 안 됨", /* settings.unset */
        "시작 안내 다시 보기", /* settings.welcome */
        "충돌", /* sync.action_conflict */
        "다운로드", /* sync.action_download */
        "최신 상태", /* sync.action_none */
        "업로드", /* sync.action_upload */
        "동기화를 마쳤습니다. {0}개 갱신, {1}개 건너뜀.", /* sync.done */
        "업로드 {0}개, 다운로드 {1}개, 변경 없음 {2}개, 충돌 {3}개.", /* sync.result */
        "{0}은(는) 이미 최신 상태입니다.", /* sync.up_to_date */
        "보안 값 없음", /* title.no_secure_value */
        "보안 값 {0}", /* title.secure_value */
        "체크섬이 일치하지 않습니다. 복원을 중단했으며 변경된 내용은 없습니다.", /* verify.failed */
        "메모리가 제한된 애플릿 모드입니다. 모든 기능을 쓰려면 게임 위에서 실행하세요.", /* warn.applet_mode */
        "동기화 전에 게임을 종료하세요. 게임 실행 중 동기화하면 세이브가 손상됩니다.", /* warn.game_running */
        "{0}은(는) 세이브를 이 본체에 묶습니다. 다른 본체의 세이브는 게임이 삭제할 수 있습니다.", /* warn.secure_value */
        "서버에 연결", /* welcome.connect */
        "브라우저에서 패널에 로그인하고 '본체 추가'를 누르면 코드가 나옵니다.", /* welcome.connect_how */
        "A 선택   위/아래 이동   START 건너뛰기", /* welcome.hint_choose */
        "A 다음   START 건너뛰기", /* welcome.hint_intro */
        "연결된 것은 없지만 SD 카드 백업은 그대로 됩니다. 서버와 연결은 설정 화면에 있습니다.", /* welcome.later */
        "주소와 코드 직접 입력", /* welcome.opt_code */
        "카메라가 화면을 못 읽을 때 씁니다. 키보드로 두 가지를 입력하면 되고, 이 방법은 항상 됩니다.", /* welcome.opt_code_hint */
        "나중에", /* welcome.opt_later */
        "서버 없이도 SD 카드로 백업은 됩니다. 이 화면의 선택은 설정에서 언제든 다시 할 수 있습니다.", /* welcome.opt_later_hint */
        "QR 코드 스캔", /* welcome.opt_qr */
        "입력할 것이 없습니다. 코드에 서버 주소가 함께 들어 있어서, 주소를 먼저 설정할 필요가 없습니다.", /* welcome.opt_qr_hint */
        "본체가 연결됐습니다. 아끼지 않는 게임으로 백업하고 되돌려 보는 것을 먼저 해 보세요. 아끼는 세이브는 그다음입니다.", /* welcome.ready */
        "무엇을 되돌리든 그 전에 항상 로컬 백업을 먼저 만듭니다. 충돌은 마음대로 합치지 않고, 양쪽을 모두 남긴 뒤 선택하게 합니다.", /* welcome.safe */
        "시작하기", /* welcome.title */
        "DaeMoon은 이 본체의 세이브를 직접 운영하는 서버에 올리고 다시 받아옵니다. 카드를 옮기지 않고 두 본체에서 같은 세이브를 씁니다.", /* welcome.what */
        "동기화는 게임을 켜기 전이나 끈 뒤에 하세요. 실행 중에는 안 됩니다. 게임이 세이브를 붙잡고 있어서, 그때 쓰면 깨집니다.", /* welcome.when */
    },
    /* ja */ {
        "DaeMoon", /* app.title */
        "日付は本体の時計によるものです。バックアップの説明にすぎず、どちらが新しいかを決めることはありません。", /* backup.clock_note */
        "現在のセーブをバックアップ中", /* backup.creating */
        "バックアップを削除しました。本体のセーブデータは変更していません。", /* backup.deleted */
        "ローカルバックアップに失敗しました。変更はありません。", /* backup.failed */
        "{0} のバックアップ", /* backup.list */
        "日付なし", /* backup.no_date */
        "{0} のバックアップはまだありません。", /* backup.none */
        "今、本体にあるセーブデータと同じ", /* backup.same_as_console */
        "すべてのセーブを SD カードにバックアップ", /* batch.backup */
        "バックアップ {0} 件、スキップ {1} 件、失敗 {2} 件。", /* batch.backup_done */
        "この一覧のすべてのセーブを読み、それぞれをパッケージとして書き出します。本体もサーバーも変更しません。", /* batch.backup_hint */
        "この一覧のセーブ {0} 件をすべて SD カードにバックアップしますか。", /* batch.confirm_backup */
        "タイトル {0} 件をすべて同期しますか。両方が変わっていた場合は {1}", /* batch.confirm_sync */
        "タイトル {0} 件をすべて同期し、食い違うものはサーバーのバージョンを受け取りますか。この本体のセーブは上書きされます。上書き前にひとつずつ SD カードへバックアップします。", /* batch.confirm_sync_server */
        "この一覧に処理できるものがありません。", /* batch.empty */
        "A 開始   上下 移動   B 戻る", /* batch.hint */
        "B このタイトルで中断", /* batch.hint_running */
        "両方が変わっていたとき", /* batch.policy */
        "ひとつずつ尋ねる", /* batch.policy_ask */
        "タイトルを一つ同期するときと同じダイアログを、食い違うものごとに出します。数個なら適切で、多いと疲れます。", /* batch.policy_ask_hint */
        "この本体のものを送る", /* batch.policy_local */
        "この本体のセーブが新しいバージョンとして上に載ります。サーバーは持っていたものをすべて残すので、もう一方にも戻れます。", /* batch.policy_local_hint */
        "サーバーのものを受け取る", /* batch.policy_server */
        "サーバーのセーブをこの本体に上書きします。ひとつずつ先に SD カードへバックアップするので、上書きされたものはカードに残ります。", /* batch.policy_server_hint */
        "{1} 件中 {0} 件", /* batch.running */
        "中断しました。それまでに終わったものはそのまま完了しており、書きかけのものはありません。", /* batch.stopped */
        "すべてのタイトルをサーバーと同期", /* batch.sync */
        "この本体だけが変わったものは送り、サーバーだけが変わったものは受け取ります。両方が変わった場合をどうするかは次に尋ねます。", /* batch.sync_hint */
        "一括処理", /* batch.title */
        "キャンセル", /* btn.cancel */
        "いいえ", /* btn.no */
        "OK", /* btn.ok */
        "はい", /* btn.yes */
        "セーブを確定できませんでした。解決するまでゲームを起動しないでください。", /* commit.failed */
        "{0} のセーブデータを SD カードにバックアップしますか？", /* confirm.backup */
        "このバックアップを削除しますか？本体のセーブデータは変更しません。", /* confirm.delete_backup */
        "{0} をこの本体に復元しますか？先にローカルバックアップを作成します。", /* confirm.restore */
        "{0} のセーブをサーバーにアップロードしますか？", /* confirm.upload */
        "{0} は別の端末でも変更されています。両方のバージョンを保持します。今使う方を選んでください。", /* conflict.explain */
        "両方残して後で決める", /* conflict.keep_both */
        "この本体のセーブを使う（{0}、{1} 保存）", /* conflict.keep_local */
        "サーバーのセーブを使う（{0}、{1}）", /* conflict.keep_server */
        "セーブの競合", /* conflict.title */
        "セーブパッケージが壊れています。", /* err.archive_error */
        "本体がセーブ操作を拒否しました。", /* err.backend_error */
        "内部バッファが小さすぎます。", /* err.buffer_too_small */
        "ダウンロードしたセーブが壊れています。", /* err.checksum_mismatch */
        "この本体のアクセスは取り消されました。もう一度ペアリングしてください。", /* err.device_revoked */
        "このタイトルにはバックアップするセーブデータがありません。", /* err.empty_save */
        "このセーブはこのアカウントのものではありません。", /* err.forbidden */
        "サーバーで問題が発生しました。", /* err.internal_error */
        "セーブパッケージを読み取れません。", /* err.invalid_manifest */
        "サーバーがリクエストを拒否しました。", /* err.invalid_request */
        "セーブの読み書きができませんでした。", /* err.io_error */
        "サーバーに接続できませんでした。", /* err.network_error */
        "サーバーが設定されていません。設定でアドレスとトークンを入力してください。", /* err.no_server */
        "SD カードの空き容量が足りません。", /* err.no_space */
        "サーバー上に見つかりません。", /* err.not_found */
        "メモリが足りません。", /* err.out_of_memory */
        "ペアリングコードの期限が切れました。最初からやり直してください。", /* err.pairing_expired */
        "承認を待っています。", /* err.pairing_pending */
        "データを読み取れませんでした。", /* err.parse_error */
        "リクエストが多すぎます。しばらくして再試行してください。", /* err.rate_limited */
        "セーブがサーバーの上限を超えています。", /* err.save_too_large */
        "この共有コードは期限切れです。", /* err.share_expired */
        "サーバーが時間内に応答しませんでした。", /* err.timeout */
        "タイトル一覧を読み込めませんでした。", /* err.title_list */
        "サーバーの証明書を確認できませんでした。", /* err.tls_error */
        "この本体はサインインしていません。もう一度ペアリングしてください。", /* err.unauthorized */
        "対応していません。", /* err.unsupported */
        "この本体はサーバーに対応していません。", /* err.unsupported_platform */
        "キャンセルしました。", /* err.user_cancelled */
        "サーバーに新しいセーブがあります。使うバージョンを選んでください。", /* err.version_conflict */
        "セーブデータのあるタイトルが見つかりませんでした。", /* grid.empty */
        "未選択", /* grid.nothing_selected */
        "セーブ {0} 件", /* grid.saves */
        "A 復元   X 削除   B もどる", /* hint.backups */
        "A 決定   B もどる   上下 移動", /* hint.choose */
        "A つづける", /* hint.continue */
        "A 編集   B もどる   上下 移動", /* hint.edit */
        "A バックアップ   Y 復元   X 調査   L/R ライブラリ   START 終了", /* hint.grid */
        "日本語", /* lang.name */
        "3DS タイトル", /* lib.3ds */
        "nds-bootstrap のセーブ", /* lib.nds */
        "バックアップを読み込み中", /* loading.backups */
        "アイコンを読み込み中", /* loading.icons */
        "タイトルを読み込み中", /* loading.titles */
        "このセーブをバックアップ", /* menu.backup */
        "一括処理", /* menu.batch */
        "バックアップから復元", /* menu.restore */
        "セルフテスト（このセーブを破壊します）", /* menu.selftest */
        "設定", /* menu.settings */
        "すべてのタイトルを調べて SD カードに記録", /* menu.survey */
        "サーバーと同期", /* menu.sync */
        "バックアップ", /* op.backup */
        "復元", /* op.restore */
        "セキュア値", /* op.secure_value */
        "調査", /* op.survey */
        "同期", /* op.sync */
        "ウェブページのコードにカメラを向けてください。   B キャンセル", /* pair.aim */
        "登録しました。これで同期できます。", /* pair.done */
        "ウェブページに表示された 6 桁のコードを入力してください。", /* pair.enter_code */
        "カメラを起動できませんでした。", /* pair.no_camera */
        "先にサーバーのアドレスを設定するか、QR コードを読み取ってください。読み取ったコードにはアドレスが含まれています。", /* pair.no_server */
        "QR コードを読み取る", /* pair.scan */
        "L/R カメラ   X/Y プレビュー   B キャンセル", /* pair.switch */
        "この本体を登録", /* pair.title */
        "DaeMoon の登録コードではありません。", /* pair.wrong_code */
        "ダウンロード中", /* progress.downloading */
        "セーブデータを圧縮中", /* progress.packing */
        "セーブデータを展開中", /* progress.unpacking */
        "アップロード中", /* progress.uploading */
        "検証中", /* progress.verifying */
        "{0} に失敗しました。{1}", /* report.failed */
        "{0}: 完了しました。", /* report.ok */
        "このビルドには自分のセーブ領域がありません。SAVEDATA_SIZE=128K でビルドしてください。", /* selftest.no_archive */
        "DaeMoon 自身", /* selftest.self */
        "{0} のセーブデータを破壊します。ダミータイトルで使ってください。先にバックアップを作りますが、それを当てにしないでください。", /* selftest.warning */
        "この本体の名前", /* settings.label */
        "言語", /* settings.language */
        "本体の設定に従う（{0}）", /* settings.language_auto */
        "この本体には {0} のフォントがないため、文字が表示されません。言語は変更しませんでした。", /* settings.no_font */
        "設定を SD カードに書き込めませんでした。", /* settings.save_failed */
        "保存しました。これ以降はこの設定を使います。", /* settings.saved */
        "サーバーのアドレス", /* settings.server */
        "設定", /* settings.title */
        "本体のトークン", /* settings.token */
        "未設定", /* settings.unset */
        "はじめの案内をもう一度", /* settings.welcome */
        "競合", /* sync.action_conflict */
        "ダウンロード", /* sync.action_download */
        "最新", /* sync.action_none */
        "アップロード", /* sync.action_upload */
        "同期が終わりました。{0} 件更新、{1} 件スキップ。", /* sync.done */
        "アップロード {0}、ダウンロード {1}、変更なし {2}、競合 {3}。", /* sync.result */
        "{0} はすでに最新です。", /* sync.up_to_date */
        "セキュア値なし", /* title.no_secure_value */
        "セキュア値 {0}", /* title.secure_value */
        "チェックサムが一致しません。復元を中止し、変更はありません。", /* verify.failed */
        "メモリが制限されたアプレットモードです。すべての機能を使うにはゲーム上から起動してください。", /* warn.applet_mode */
        "同期の前にゲームを終了してください。ゲーム実行中の同期はセーブを壊します。", /* warn.game_running */
        "{0} はセーブをこの本体に紐付けます。他の本体のセーブはゲームに削除されることがあります。", /* warn.secure_value */
        "サーバーに接続", /* welcome.connect */
        "ブラウザーでパネルにサインインし、「本体を追加」を押すとコードが表示されます。", /* welcome.connect_how */
        "A 決定   上下 移動   START スキップ", /* welcome.hint_choose */
        "A 次へ   START スキップ", /* welcome.hint_intro */
        "接続はされていませんが、SD カードへのバックアップはそのまま使えます。サーバーと登録は設定画面にあります。", /* welcome.later */
        "アドレスとコードを入力", /* welcome.opt_code */
        "カメラが画面を読み取れないときに使います。キーボードで二つ入力するだけで、こちらは必ず動きます。", /* welcome.opt_code_hint */
        "あとで", /* welcome.opt_later */
        "サーバーがなくても SD カードへのバックアップはできます。この画面の選択は設定からいつでも行えます。", /* welcome.opt_later_hint */
        "QR コードを読み取る", /* welcome.opt_qr */
        "入力は不要です。コードにサーバーのアドレスが含まれているので、先にアドレスを設定する必要はありません。", /* welcome.opt_qr_hint */
        "この本体は接続されました。まずは惜しくないゲームでバックアップと復元を試してから、大事なセーブを預けてください。", /* welcome.ready */
        "復元の前には必ずローカルバックアップを作ります。競合を勝手に統合することはなく、両方を残してあなたが選びます。", /* welcome.safe */
        "はじめに", /* welcome.title */
        "DaeMoon はこの本体のセーブを自分で動かすサーバーに上げ、また取り戻します。カードを差し替えずに二台で同じセーブを使えます。", /* welcome.what */
        "同期はゲームを起動する前か終了した後に行ってください。実行中はできません。ゲームがセーブを掴んでいるため、そのとき書き込むと壊れます。", /* welcome.when */
    },
    /* zh-Hans */ {
        "DaeMoon", /* app.title */
        "日期来自主机时钟，仅用于描述备份，绝不决定哪个存档更新。", /* backup.clock_note */
        "正在备份当前存档", /* backup.creating */
        "备份已删除。主机上的存档未被改动。", /* backup.deleted */
        "本地备份失败，未做任何更改。", /* backup.failed */
        "{0} 的备份", /* backup.list */
        "日期未知", /* backup.no_date */
        "还没有 {0} 的备份。", /* backup.none */
        "与主机上现在的存档相同", /* backup.same_as_console */
        "把所有存档备份到 SD 卡", /* batch.backup */
        "已备份 {0} 个，跳过 {1} 个，失败 {2} 个。", /* batch.backup_done */
        "读取本列表里的每个存档，各写出一个包。主机和服务器上的东西都不会改动。", /* batch.backup_hint */
        "把本列表里的 {0} 个存档全部备份到 SD 卡吗？", /* batch.confirm_backup */
        "同步全部 {0} 个游戏吗？两边都变过时：{1}", /* batch.confirm_sync */
        "同步全部 {0} 个游戏，凡是不一致的都取服务器的版本吗？本机的存档会被覆盖。每一个都会先备份到 SD 卡。", /* batch.confirm_sync_server */
        "这个列表里没有可处理的内容。", /* batch.empty */
        "A 开始   上下 移动   B 返回", /* batch.hint */
        "B 做完这个游戏后停止", /* batch.hint_running */
        "两边都变过时", /* batch.policy */
        "逐个询问我", /* batch.policy_ask */
        "和同步单个游戏时一样的对话框，每有一个不一致就弹一次。少数几个时合适，多了会累。", /* batch.policy_ask_hint */
        "上传本机的", /* batch.policy_local */
        "本机的存档作为新版本盖上去。服务器保留原有的一切，另一边随时还能取回。", /* batch.policy_local_hint */
        "下载服务器的", /* batch.policy_server */
        "用服务器的存档覆盖本机的。每一个都会先备份到 SD 卡，所以被覆盖的仍在卡上。", /* batch.policy_server_hint */
        "{1} 个中的第 {0} 个", /* batch.running */
        "已停止。此前完成的都已完成，没有留下写到一半的东西。", /* batch.stopped */
        "把所有游戏与服务器同步", /* batch.sync */
        "只有本机变过的上传，只有服务器变过的下载。两边都变过时怎么办，下一步再问。", /* batch.sync_hint */
        "批量操作", /* batch.title */
        "取消", /* btn.cancel */
        "否", /* btn.no */
        "确定", /* btn.ok */
        "是", /* btn.yes */
        "存档未能提交。问题解决前请不要启动游戏。", /* commit.failed */
        "把 {0} 的存档备份到 SD 卡？", /* confirm.backup */
        "删除这个备份？主机上的存档不会被改动。", /* confirm.delete_backup */
        "要把 {0} 恢复到本机吗？会先生成本地备份。", /* confirm.restore */
        "要把 {0} 的存档上传到服务器吗？", /* confirm.upload */
        "{0} 在另一台设备上也被修改过。两个版本都会保留。请选择现在使用哪一个。", /* conflict.explain */
        "都保留，稍后再决定", /* conflict.keep_both */
        "使用本机存档（{0}，保存于 {1}）", /* conflict.keep_local */
        "使用服务器存档（{0}，来自 {1}）", /* conflict.keep_server */
        "存档冲突", /* conflict.title */
        "存档包已损坏。", /* err.archive_error */
        "主机拒绝了该存档操作。", /* err.backend_error */
        "内部缓冲区过小。", /* err.buffer_too_small */
        "下载的存档已损坏。", /* err.checksum_mismatch */
        "本机的访问权限已被撤销，请重新配对。", /* err.device_revoked */
        "该标题没有可备份的存档。", /* err.empty_save */
        "该存档不属于此账号。", /* err.forbidden */
        "服务器出现问题。", /* err.internal_error */
        "无法读取存档包。", /* err.invalid_manifest */
        "服务器拒绝了该请求。", /* err.invalid_request */
        "无法读取或写入存档。", /* err.io_error */
        "无法连接服务器。", /* err.network_error */
        "未设置服务器。请在设置中填写地址和令牌。", /* err.no_server */
        "SD 卡空间不足。", /* err.no_space */
        "服务器上找不到。", /* err.not_found */
        "内存不足。", /* err.out_of_memory */
        "配对码已过期，请重新开始。", /* err.pairing_expired */
        "正在等待批准。", /* err.pairing_pending */
        "无法读取数据。", /* err.parse_error */
        "请求过于频繁，请稍后再试。", /* err.rate_limited */
        "存档超过服务器允许的大小。", /* err.save_too_large */
        "该分享码已过期。", /* err.share_expired */
        "服务器未在规定时间内响应。", /* err.timeout */
        "无法读取游戏列表。", /* err.title_list */
        "无法验证服务器证书。", /* err.tls_error */
        "本机尚未登录，请重新配对。", /* err.unauthorized */
        "不支持该操作。", /* err.unsupported */
        "服务器不支持该主机。", /* err.unsupported_platform */
        "已取消。", /* err.user_cancelled */
        "服务器上有更新的存档，请选择要保留的版本。", /* err.version_conflict */
        "没有找到带存档的游戏。", /* grid.empty */
        "未选择", /* grid.nothing_selected */
        "{0} 个存档", /* grid.saves */
        "A 恢复   X 删除   B 返回", /* hint.backups */
        "A 选择   B 返回   上下 移动", /* hint.choose */
        "A 继续", /* hint.continue */
        "A 编辑   B 返回   上下 移动", /* hint.edit */
        "A 备份   Y 恢复   X 调查   L/R 库   START 退出", /* hint.grid */
        "简体中文", /* lang.name */
        "3DS 游戏", /* lib.3ds */
        "nds-bootstrap 存档", /* lib.nds */
        "正在读取备份", /* loading.backups */
        "正在读取图标", /* loading.icons */
        "正在读取游戏列表", /* loading.titles */
        "备份此存档", /* menu.backup */
        "批量操作", /* menu.batch */
        "从备份恢复", /* menu.restore */
        "自检（会销毁此存档）", /* menu.selftest */
        "设置", /* menu.settings */
        "调查所有游戏并写入 SD 卡", /* menu.survey */
        "与服务器同步", /* menu.sync */
        "备份", /* op.backup */
        "恢复", /* op.restore */
        "安全值", /* op.secure_value */
        "调查", /* op.survey */
        "同步", /* op.sync */
        "把摄像头对准网页上的代码。   B 取消", /* pair.aim */
        "已配对。现在可以同步了。", /* pair.done */
        "输入网页上显示的六位代码。", /* pair.enter_code */
        "无法启动摄像头。", /* pair.no_camera */
        "请先设置服务器地址，或改为扫描二维码，扫描的代码里带着地址。", /* pair.no_server */
        "扫描二维码", /* pair.scan */
        "L/R 摄像头   X/Y 预览模式   B 取消", /* pair.switch */
        "配对这台主机", /* pair.title */
        "这不是 DaeMoon 的配对代码。", /* pair.wrong_code */
        "正在下载", /* progress.downloading */
        "正在打包存档", /* progress.packing */
        "正在解包存档", /* progress.unpacking */
        "正在上传", /* progress.uploading */
        "正在校验", /* progress.verifying */
        "{0}失败。{1}", /* report.failed */
        "{0}：已完成。", /* report.ok */
        "此版本没有自己的存档区。请用 SAVEDATA_SIZE=128K 构建。", /* selftest.no_archive */
        "DaeMoon 自身", /* selftest.self */
        "这会销毁 {0} 的存档。请只用于测试用游戏。会先做备份，但不要依赖它。", /* selftest.warning */
        "这台主机的名称", /* settings.label */
        "语言", /* settings.language */
        "跟随主机设置（{0}）", /* settings.language_auto */
        "这台主机没有{0}字体，文字会是空白。语言未更改。", /* settings.no_font */
        "无法把设置写入 SD 卡。", /* settings.save_failed */
        "已保存。此后将使用这些设置。", /* settings.saved */
        "服务器地址", /* settings.server */
        "设置", /* settings.title */
        "设备令牌", /* settings.token */
        "未设置", /* settings.unset */
        "重新查看欢迎说明", /* settings.welcome */
        "冲突", /* sync.action_conflict */
        "下载", /* sync.action_download */
        "已是最新", /* sync.action_none */
        "上传", /* sync.action_upload */
        "同步完成。已更新 {0} 个，跳过 {1} 个。", /* sync.done */
        "上传 {0}，下载 {1}，无变化 {2}，冲突 {3}。", /* sync.result */
        "{0} 已是最新。", /* sync.up_to_date */
        "无安全值", /* title.no_secure_value */
        "安全值 {0}", /* title.secure_value */
        "校验值不匹配。已中止恢复，未做任何更改。", /* verify.failed */
        "当前为内存受限的小程序模式。请在游戏之上启动本应用以使用全部功能。", /* warn.applet_mode */
        "同步前请先关闭游戏。游戏运行时同步会损坏存档。", /* warn.game_running */
        "{0} 会把存档绑定到本机。来自其他主机的存档可能被游戏删除。", /* warn.secure_value */
        "连接到你的服务器", /* welcome.connect */
        "在浏览器里登录面板，按下“添加主机”，就会显示一个代码。", /* welcome.connect_how */
        "A 选择   上下 移动   START 跳过", /* welcome.hint_choose */
        "A 下一步   START 跳过", /* welcome.hint_intro */
        "没有连接任何东西，但备份到 SD 卡照样可用。服务器和配对都在设置里。", /* welcome.later */
        "手动输入地址和代码", /* welcome.opt_code */
        "摄像头读不到屏幕时用这个。用键盘输入两项，这条路总是行得通。", /* welcome.opt_code_hint */
        "以后再说", /* welcome.opt_later */
        "没有服务器也能备份到 SD 卡。这个画面上的选项在设置里随时都能再用。", /* welcome.opt_later_hint */
        "扫描二维码", /* welcome.opt_qr */
        "不用输入任何东西。代码里带着服务器地址，所以不必先设置地址。", /* welcome.opt_qr_hint */
        "这台主机已连接。先拿一个不心疼的游戏做一次备份和还原，再把要紧的存档交给它。", /* welcome.ready */
        "任何还原之前都会先做一份本地备份。冲突不会替你合并：两个版本都保留，由你来选。", /* welcome.safe */
        "欢迎", /* welcome.title */
        "DaeMoon 把这台主机的存档上传到你自己运行的服务器，也能取回来。不用换卡就能在两台主机上用同一份存档。", /* welcome.what */
        "在开始游戏之前或退出之后同步，正在运行时不要同步。游戏占着存档，此时写入会把它弄坏。", /* welcome.when */
    },
    /* zh-Hant */ {
        "DaeMoon", /* app.title */
        "日期來自主機時鐘，僅用於描述備份，絕不決定哪個存檔較新。", /* backup.clock_note */
        "正在備份目前的存檔", /* backup.creating */
        "備份已刪除。主機上的存檔未被更動。", /* backup.deleted */
        "本機備份失敗，未做任何變更。", /* backup.failed */
        "{0} 的備份", /* backup.list */
        "日期不明", /* backup.no_date */
        "還沒有 {0} 的備份。", /* backup.none */
        "與主機上目前的存檔相同", /* backup.same_as_console */
        "把所有存檔備份到 SD 卡", /* batch.backup */
        "已備份 {0} 個，跳過 {1} 個，失敗 {2} 個。", /* batch.backup_done */
        "讀取本清單裡的每個存檔，各寫出一個包。主機和伺服器上的東西都不會改動。", /* batch.backup_hint */
        "把本清單裡的 {0} 個存檔全部備份到 SD 卡嗎？", /* batch.confirm_backup */
        "同步全部 {0} 個遊戲嗎？兩邊都變過時：{1}", /* batch.confirm_sync */
        "同步全部 {0} 個遊戲，凡是不一致的都取伺服器的版本嗎？本機的存檔會被覆蓋。每一個都會先備份到 SD 卡。", /* batch.confirm_sync_server */
        "這個清單裡沒有可處理的內容。", /* batch.empty */
        "A 開始   上下 移動   B 返回", /* batch.hint */
        "B 做完這個遊戲後停止", /* batch.hint_running */
        "兩邊都變過時", /* batch.policy */
        "逐個詢問我", /* batch.policy_ask */
        "和同步單個遊戲時一樣的對話框，每有一個不一致就彈一次。少數幾個時合適，多了會累。", /* batch.policy_ask_hint */
        "上傳本機的", /* batch.policy_local */
        "本機的存檔作為新版本蓋上去。伺服器保留原有的一切，另一邊隨時還能取回。", /* batch.policy_local_hint */
        "下載伺服器的", /* batch.policy_server */
        "用伺服器的存檔覆蓋本機的。每一個都會先備份到 SD 卡，所以被覆蓋的仍在卡上。", /* batch.policy_server_hint */
        "{1} 個中的第 {0} 個", /* batch.running */
        "已停止。此前完成的都已完成，沒有留下寫到一半的東西。", /* batch.stopped */
        "把所有遊戲與伺服器同步", /* batch.sync */
        "只有本機變過的上傳，只有伺服器變過的下載。兩邊都變過時怎麼辦，下一步再問。", /* batch.sync_hint */
        "批次操作", /* batch.title */
        "取消", /* btn.cancel */
        "否", /* btn.no */
        "確定", /* btn.ok */
        "是", /* btn.yes */
        "存檔未能提交。問題解決前請勿啟動遊戲。", /* commit.failed */
        "把 {0} 的存檔備份到 SD 卡？", /* confirm.backup */
        "刪除這個備份？主機上的存檔不會被更動。", /* confirm.delete_backup */
        "要將 {0} 還原到本機嗎？會先建立本機備份。", /* confirm.restore */
        "要將 {0} 的存檔上傳到伺服器嗎？", /* confirm.upload */
        "{0} 在另一台裝置上也被修改過。兩個版本都會保留。請選擇現在要使用哪一個。", /* conflict.explain */
        "都保留，稍後再決定", /* conflict.keep_both */
        "使用本機存檔（{0}，儲存於 {1}）", /* conflict.keep_local */
        "使用伺服器存檔（{0}，來自 {1}）", /* conflict.keep_server */
        "存檔衝突", /* conflict.title */
        "存檔包已損壞。", /* err.archive_error */
        "主機拒絕了該存檔操作。", /* err.backend_error */
        "內部緩衝區過小。", /* err.buffer_too_small */
        "下載的存檔已損壞。", /* err.checksum_mismatch */
        "本機的存取權限已被撤銷，請重新配對。", /* err.device_revoked */
        "此標題沒有可備份的存檔。", /* err.empty_save */
        "該存檔不屬於此帳號。", /* err.forbidden */
        "伺服器發生問題。", /* err.internal_error */
        "無法讀取存檔包。", /* err.invalid_manifest */
        "伺服器拒絕了該請求。", /* err.invalid_request */
        "無法讀取或寫入存檔。", /* err.io_error */
        "無法連線到伺服器。", /* err.network_error */
        "未設定伺服器。請在設定中填寫位址與權杖。", /* err.no_server */
        "SD 卡空間不足。", /* err.no_space */
        "伺服器上找不到。", /* err.not_found */
        "記憶體不足。", /* err.out_of_memory */
        "配對碼已過期，請重新開始。", /* err.pairing_expired */
        "正在等待核准。", /* err.pairing_pending */
        "無法讀取資料。", /* err.parse_error */
        "請求過於頻繁，請稍後再試。", /* err.rate_limited */
        "存檔超過伺服器允許的大小。", /* err.save_too_large */
        "此分享碼已過期。", /* err.share_expired */
        "伺服器未在時間內回應。", /* err.timeout */
        "無法讀取遊戲清單。", /* err.title_list */
        "無法驗證伺服器憑證。", /* err.tls_error */
        "本機尚未登入，請重新配對。", /* err.unauthorized */
        "不支援此操作。", /* err.unsupported */
        "伺服器不支援這台主機。", /* err.unsupported_platform */
        "已取消。", /* err.user_cancelled */
        "伺服器上有較新的存檔，請選擇要保留的版本。", /* err.version_conflict */
        "沒有找到帶存檔的遊戲。", /* grid.empty */
        "未選擇", /* grid.nothing_selected */
        "{0} 個存檔", /* grid.saves */
        "A 還原   X 刪除   B 返回", /* hint.backups */
        "A 選擇   B 返回   上下 移動", /* hint.choose */
        "A 繼續", /* hint.continue */
        "A 編輯   B 返回   上下 移動", /* hint.edit */
        "A 備份   Y 還原   X 調查   L/R 庫   START 離開", /* hint.grid */
        "繁體中文", /* lang.name */
        "3DS 遊戲", /* lib.3ds */
        "nds-bootstrap 存檔", /* lib.nds */
        "正在讀取備份", /* loading.backups */
        "正在讀取圖示", /* loading.icons */
        "正在讀取遊戲清單", /* loading.titles */
        "備份此存檔", /* menu.backup */
        "批次操作", /* menu.batch */
        "從備份還原", /* menu.restore */
        "自我測試（會銷毀此存檔）", /* menu.selftest */
        "設定", /* menu.settings */
        "調查所有遊戲並寫入 SD 卡", /* menu.survey */
        "與伺服器同步", /* menu.sync */
        "備份", /* op.backup */
        "還原", /* op.restore */
        "安全值", /* op.secure_value */
        "調查", /* op.survey */
        "同步", /* op.sync */
        "把鏡頭對準網頁上的代碼。   B 取消", /* pair.aim */
        "已配對。現在可以同步了。", /* pair.done */
        "輸入網頁上顯示的六位代碼。", /* pair.enter_code */
        "無法啟動鏡頭。", /* pair.no_camera */
        "請先設定伺服器位址，或改為掃描 QR 碼，掃描的代碼裡帶著位址。", /* pair.no_server */
        "掃描 QR 碼", /* pair.scan */
        "L/R 鏡頭   X/Y 預覽模式   B 取消", /* pair.switch */
        "配對這台主機", /* pair.title */
        "這不是 DaeMoon 的配對代碼。", /* pair.wrong_code */
        "正在下載", /* progress.downloading */
        "正在封裝存檔", /* progress.packing */
        "正在解開存檔", /* progress.unpacking */
        "正在上傳", /* progress.uploading */
        "正在驗證", /* progress.verifying */
        "{0}失敗。{1}", /* report.failed */
        "{0}：已完成。", /* report.ok */
        "此版本沒有自己的存檔區。請用 SAVEDATA_SIZE=128K 建置。", /* selftest.no_archive */
        "DaeMoon 自身", /* selftest.self */
        "這會銷毀 {0} 的存檔。請只用於測試用遊戲。會先做備份，但不要依賴它。", /* selftest.warning */
        "這台主機的名稱", /* settings.label */
        "語言", /* settings.language */
        "跟隨主機設定（{0}）", /* settings.language_auto */
        "這台主機沒有{0}字型，文字會是空白。語言未變更。", /* settings.no_font */
        "無法將設定寫入 SD 卡。", /* settings.save_failed */
        "已儲存。此後將使用這些設定。", /* settings.saved */
        "伺服器位址", /* settings.server */
        "設定", /* settings.title */
        "裝置權杖", /* settings.token */
        "未設定", /* settings.unset */
        "重新查看歡迎說明", /* settings.welcome */
        "衝突", /* sync.action_conflict */
        "下載", /* sync.action_download */
        "已是最新", /* sync.action_none */
        "上傳", /* sync.action_upload */
        "同步完成。已更新 {0} 個，略過 {1} 個。", /* sync.done */
        "上傳 {0}，下載 {1}，無變更 {2}，衝突 {3}。", /* sync.result */
        "{0} 已是最新。", /* sync.up_to_date */
        "無安全值", /* title.no_secure_value */
        "安全值 {0}", /* title.secure_value */
        "校驗值不符。已中止還原，未做任何變更。", /* verify.failed */
        "目前為記憶體受限的小程式模式。請在遊戲之上啟動本程式以使用完整功能。", /* warn.applet_mode */
        "同步前請先關閉遊戲。遊戲執行中同步會損壞存檔。", /* warn.game_running */
        "{0} 會將存檔綁定到本機。來自其他主機的存檔可能被遊戲刪除。", /* warn.secure_value */
        "連線到你的伺服器", /* welcome.connect */
        "在瀏覽器裡登入面板，按下「新增主機」，就會顯示一個代碼。", /* welcome.connect_how */
        "A 選擇   上下 移動   START 跳過", /* welcome.hint_choose */
        "A 下一步   START 跳過", /* welcome.hint_intro */
        "沒有連線任何東西，但備份到 SD 卡照樣可用。伺服器和配對都在設定裡。", /* welcome.later */
        "手動輸入位址和代碼", /* welcome.opt_code */
        "相機讀不到螢幕時用這個。用鍵盤輸入兩項，這條路總是行得通。", /* welcome.opt_code_hint */
        "之後再說", /* welcome.opt_later */
        "沒有伺服器也能備份到 SD 卡。這個畫面上的選項在設定裡隨時都能再用。", /* welcome.opt_later_hint */
        "掃描 QR 碼", /* welcome.opt_qr */
        "不用輸入任何東西。代碼裡帶著伺服器位址，所以不必先設定位址。", /* welcome.opt_qr_hint */
        "這台主機已連線。先拿一個不心疼的遊戲做一次備份和還原，再把要緊的存檔交給它。", /* welcome.ready */
        "任何還原之前都會先做一份本機備份。衝突不會替你合併：兩個版本都保留，由你來選。", /* welcome.safe */
        "歡迎", /* welcome.title */
        "DaeMoon 把這台主機的存檔上傳到你自己運行的伺服器，也能取回來。不用換卡就能在兩台主機上用同一份存檔。", /* welcome.what */
        "在開始遊戲之前或退出之後同步，正在執行時不要同步。遊戲佔著存檔，此時寫入會把它弄壞。", /* welcome.when */
    },
    /* es */ {
        "DaeMoon", /* app.title */
        "Las fechas vienen del reloj de la consola. Describen una copia; nunca deciden qué partida es más reciente.", /* backup.clock_note */
        "Creando copia de seguridad de la partida actual", /* backup.creating */
        "La copia de seguridad se ha eliminado. No se ha tocado la partida de la consola.", /* backup.deleted */
        "La copia de seguridad local ha fallado. No se ha cambiado nada.", /* backup.failed */
        "Copias de seguridad de {0}", /* backup.list */
        "fecha desconocida", /* backup.no_date */
        "Todavía no hay ninguna copia de seguridad de {0}.", /* backup.none */
        "igual que la partida que hay ahora en la consola", /* backup.same_as_console */
        "Copiar todas las partidas a la tarjeta SD", /* batch.backup */
        "{0} copiadas, {1} omitidas, {2} fallidas.", /* batch.backup_done */
        "Lee todas las partidas de esta biblioteca y escribe un paquete por cada una. No cambia nada en la consola ni en el servidor.", /* batch.backup_hint */
        "¿Copiar las {0} partidas de esta biblioteca a la tarjeta SD?", /* batch.confirm_backup */
        "¿Sincronizar los {0} juegos? Donde cambiaron ambos lados: {1}", /* batch.confirm_sync */
        "¿Sincronizar los {0} juegos tomando la versión del servidor donde difieran? Se sobrescribirán partidas de esta consola. Cada una se copia antes a la tarjeta SD.", /* batch.confirm_sync_server */
        "No hay nada en esta biblioteca sobre lo que trabajar.", /* batch.empty */
        "A empezar   arriba/abajo mover   B atrás", /* batch.hint */
        "B parar tras este juego", /* batch.hint_running */
        "Cuando cambiaron ambos lados", /* batch.policy */
        "Preguntarme una por una", /* batch.policy_ask */
        "El mismo diálogo que muestra un juego suelto, una vez por cada uno que difiera. Va bien con unos pocos, cansa con muchos.", /* batch.policy_ask_hint */
        "Subir las de esta consola", /* batch.policy_local */
        "La partida de esta consola sube como una versión nueva. El servidor conserva todo lo que ya tenía, así que el otro lado sigue ahí para volver.", /* batch.policy_local_hint */
        "Bajar las del servidor", /* batch.policy_server */
        "La partida del servidor se escribe sobre la de esta consola. Cada una se copia antes a la tarjeta SD, así que lo reemplazado sigue en la tarjeta.", /* batch.policy_server_hint */
        "{0} de {1}", /* batch.running */
        "Detenido. Todo lo terminado antes de este punto está hecho y nada quedó a medio escribir.", /* batch.stopped */
        "Sincronizar todos los juegos con el servidor", /* batch.sync */
        "Sube lo que solo cambió en esta consola y baja lo que solo cambió en el servidor. Qué pasa cuando cambiaron los dos es la siguiente pregunta.", /* batch.sync_hint */
        "Todos los juegos", /* batch.title */
        "Cancelar", /* btn.cancel */
        "No", /* btn.no */
        "Aceptar", /* btn.ok */
        "Sí", /* btn.yes */
        "No se ha podido confirmar la partida. No inicies el juego hasta resolverlo.", /* commit.failed */
        "¿Hacer una copia de seguridad de la partida de {0} en la tarjeta SD?", /* confirm.backup */
        "¿Eliminar esta copia de seguridad? No se toca la partida de la consola.", /* confirm.delete_backup */
        "¿Restaurar {0} en esta consola? Primero se crea una copia de seguridad local.", /* confirm.restore */
        "¿Subir la partida de {0} al servidor?", /* confirm.upload */
        "{0} también se ha modificado en otro dispositivo. Se conservan ambas versiones. Elige cuál usar ahora.", /* conflict.explain */
        "Conservar ambas y decidir más tarde", /* conflict.keep_both */
        "Usar la partida de esta consola ({0}, guardada el {1})", /* conflict.keep_local */
        "Usar la partida del servidor ({0}, del {1})", /* conflict.keep_server */
        "Partidas en conflicto", /* conflict.title */
        "El paquete de la partida está dañado.", /* err.archive_error */
        "La consola ha rechazado la operación sobre la partida.", /* err.backend_error */
        "Búfer interno demasiado pequeño.", /* err.buffer_too_small */
        "La partida descargada está dañada.", /* err.checksum_mismatch */
        "Se ha revocado el acceso de esta consola. Vuelve a vincularla.", /* err.device_revoked */
        "Este título no tiene partida que copiar.", /* err.empty_save */
        "Esta partida no pertenece a esta cuenta.", /* err.forbidden */
        "El servidor ha tenido un problema.", /* err.internal_error */
        "No se puede leer el paquete de la partida.", /* err.invalid_manifest */
        "El servidor ha rechazado la petición.", /* err.invalid_request */
        "No se ha podido leer o escribir la partida.", /* err.io_error */
        "No se ha podido conectar con el servidor.", /* err.network_error */
        "No hay servidor configurado. Abre Ajustes e introduce la dirección y el token.", /* err.no_server */
        "No hay espacio suficiente en la tarjeta SD.", /* err.no_space */
        "No se ha encontrado en el servidor.", /* err.not_found */
        "Memoria insuficiente.", /* err.out_of_memory */
        "El código de vinculación ha caducado. Empieza de nuevo.", /* err.pairing_expired */
        "Esperando la aprobación.", /* err.pairing_pending */
        "No se han podido leer los datos.", /* err.parse_error */
        "Demasiadas peticiones. Inténtalo de nuevo en un momento.", /* err.rate_limited */
        "La partida supera el tamaño permitido por el servidor.", /* err.save_too_large */
        "Este código de compartición ha caducado.", /* err.share_expired */
        "El servidor no ha respondido a tiempo.", /* err.timeout */
        "No se ha podido leer la lista de juegos.", /* err.title_list */
        "No se ha podido verificar el certificado del servidor.", /* err.tls_error */
        "Esta consola no ha iniciado sesión. Vuelve a vincularla.", /* err.unauthorized */
        "No es compatible.", /* err.unsupported */
        "El servidor no admite esta consola.", /* err.unsupported_platform */
        "Cancelado.", /* err.user_cancelled */
        "El servidor tiene una partida más reciente. Elige qué versión conservar.", /* err.version_conflict */
        "No se ha encontrado ningún juego con partida guardada.", /* grid.empty */
        "nada seleccionado", /* grid.nothing_selected */
        "{0} partidas", /* grid.saves */
        "A restaurar   X eliminar   B atrás", /* hint.backups */
        "A elegir   B atrás   arriba/abajo mover", /* hint.choose */
        "A continuar", /* hint.continue */
        "A editar   B atrás   arriba/abajo mover", /* hint.edit */
        "A copiar   Y restaurar   X analizar   L/R biblioteca   START salir", /* hint.grid */
        "Español", /* lang.name */
        "Juegos de 3DS", /* lib.3ds */
        "Partidas de nds-bootstrap", /* lib.nds */
        "Leyendo las copias de seguridad", /* loading.backups */
        "Leyendo los iconos", /* loading.icons */
        "Leyendo los juegos", /* loading.titles */
        "Copiar esta partida", /* menu.backup */
        "Todos los juegos", /* menu.batch */
        "Restaurar desde una copia", /* menu.restore */
        "Autocomprobación (destruye esta partida)", /* menu.selftest */
        "Ajustes", /* menu.settings */
        "Analizar todos los juegos y escribirlo en la tarjeta SD", /* menu.survey */
        "Sincronizar con el servidor", /* menu.sync */
        "Copia de seguridad", /* op.backup */
        "Restauración", /* op.restore */
        "Valor seguro", /* op.secure_value */
        "Análisis", /* op.survey */
        "Sincronización", /* op.sync */
        "Apunta la cámara al código de la página web.   B cancelar", /* pair.aim */
        "Vinculada. Ya puede sincronizar.", /* pair.done */
        "Escribe el código de seis dígitos que muestra la página web.", /* pair.enter_code */
        "No se ha podido iniciar la cámara.", /* pair.no_camera */
        "Configura primero la dirección del servidor, o escanea un código: el código escaneado lleva la dirección.", /* pair.no_server */
        "Escanear un código QR", /* pair.scan */
        "L/R cámara   X/Y modo de vista   B cancelar", /* pair.switch */
        "Vincular esta consola", /* pair.title */
        "Ese no es un código de vinculación de DaeMoon.", /* pair.wrong_code */
        "Descargando", /* progress.downloading */
        "Empaquetando la partida", /* progress.packing */
        "Extrayendo la partida", /* progress.unpacking */
        "Subiendo", /* progress.uploading */
        "Verificando", /* progress.verifying */
        "{0} ha fallado. {1}", /* report.failed */
        "{0}: hecho.", /* report.ok */
        "Esta compilación no tiene su propio archivo de partida. Compílala con SAVEDATA_SIZE=128K.", /* selftest.no_archive */
        "El propio DaeMoon", /* selftest.self */
        "Esto DESTRUYE la partida de {0}. Usa un juego de prueba. Se hace una copia antes, pero no confíes en ella.", /* selftest.warning */
        "Nombre de esta consola", /* settings.label */
        "Idioma", /* settings.language */
        "Según la consola ({0})", /* settings.language_auto */
        "Esta consola no tiene una fuente para {0}, el texto quedaría en blanco. No se ha cambiado el idioma.", /* settings.no_font */
        "No se han podido escribir los ajustes en la tarjeta SD.", /* settings.save_failed */
        "Guardado. Esta consola usará estos ajustes a partir de ahora.", /* settings.saved */
        "Dirección del servidor", /* settings.server */
        "Ajustes", /* settings.title */
        "Token del dispositivo", /* settings.token */
        "sin definir", /* settings.unset */
        "Volver a ver la bienvenida", /* settings.welcome */
        "Conflicto", /* sync.action_conflict */
        "Descargar", /* sync.action_download */
        "Al día", /* sync.action_none */
        "Subir", /* sync.action_upload */
        "Sincronización terminada. {0} actualizados, {1} omitidos.", /* sync.done */
        "{0} subidas, {1} descargas, {2} sin cambios, {3} conflictos.", /* sync.result */
        "{0} ya está al día.", /* sync.up_to_date */
        "sin valor seguro", /* title.no_secure_value */
        "valor seguro {0}", /* title.secure_value */
        "La suma de verificación no coincide. La restauración se ha cancelado y no se ha cambiado nada.", /* verify.failed */
        "En modo applet con memoria limitada. Abre la aplicación desde un juego para tener todas las funciones.", /* warn.applet_mode */
        "Cierra el juego antes de sincronizar. Sincronizar con el juego abierto daña la partida.", /* warn.game_running */
        "{0} vincula su partida a esta consola. El juego puede borrar una partida de otra consola.", /* warn.secure_value */
        "Conecta con tu servidor", /* welcome.connect */
        "Inicia sesión en el panel desde un navegador y pulsa Añadir consola. Aparecerá un código.", /* welcome.connect_how */
        "A elegir   arriba/abajo mover   START saltar", /* welcome.hint_choose */
        "A siguiente   START saltar", /* welcome.hint_intro */
        "No hay nada conectado, y las copias en la tarjeta SD funcionan igual. En Ajustes están el servidor y el emparejamiento cuando los quieras.", /* welcome.later */
        "Escribir la dirección y el código", /* welcome.opt_code */
        "Para cuando la cámara no puede leer una pantalla. Dos cosas que escribir con el teclado, y siempre funciona.", /* welcome.opt_code_hint */
        "Ahora no", /* welcome.opt_later */
        "Hacer copias en la tarjeta SD funciona sin servidor. Ajustes tiene las opciones de esta pantalla cuando las quieras.", /* welcome.opt_later_hint */
        "Escanear el código QR", /* welcome.opt_qr */
        "No hay que escribir nada. El código lleva la dirección del servidor, así que no hace falta configurarla antes.", /* welcome.opt_qr_hint */
        "Esta consola está conectada. Haz primero una copia y una restauración con un juego que no te importe, antes de confiarle uno que sí.", /* welcome.ready */
        "Siempre se hace una copia local antes de restaurar nada, y un conflicto nunca se fusiona por ti: se guardan ambas versiones y eliges tú.", /* welcome.safe */
        "Bienvenida", /* welcome.title */
        "DaeMoon copia las partidas de esta consola a un servidor tuyo, y las trae de vuelta. La misma partida en dos consolas, sin mover la tarjeta.", /* welcome.what */
        "Sincroniza antes de empezar un juego o después de salir, nunca mientras uno está en marcha. Un juego mantiene su partida abierta, y escribir entonces la rompe.", /* welcome.when */
    },
    /* fr */ {
        "DaeMoon", /* app.title */
        "Les dates viennent de l'horloge de la console. Elles décrivent une sauvegarde ; elles ne décident jamais laquelle est la plus récente.", /* backup.clock_note */
        "Sauvegarde locale de la partie en cours", /* backup.creating */
        "La sauvegarde a été supprimée. La partie sur la console n'a pas été touchée.", /* backup.deleted */
        "La sauvegarde locale a échoué. Rien n'a été modifié.", /* backup.failed */
        "Sauvegardes de {0}", /* backup.list */
        "date inconnue", /* backup.no_date */
        "Aucune sauvegarde de {0} pour l'instant.", /* backup.none */
        "identique à la partie actuellement sur la console", /* backup.same_as_console */
        "Sauvegarder toutes les parties sur la carte SD", /* batch.backup */
        "{0} sauvegardées, {1} ignorées, {2} en échec.", /* batch.backup_done */
        "Lit toutes les sauvegardes de cette bibliothèque et écrit un paquet pour chacune. Rien n'est modifié sur la console ni sur le serveur.", /* batch.backup_hint */
        "Sauvegarder les {0} parties de cette bibliothèque sur la carte SD ?", /* batch.confirm_backup */
        "Synchroniser les {0} jeux ? Là où les deux côtés ont changé : {1}", /* batch.confirm_sync */
        "Synchroniser les {0} jeux en prenant la version du serveur là où elles diffèrent ? Des sauvegardes de cette console seront écrasées. Chacune est d'abord copiée sur la carte SD.", /* batch.confirm_sync_server */
        "Il n'y a rien à traiter dans cette bibliothèque.", /* batch.empty */
        "A démarrer   haut/bas déplacer   B retour", /* batch.hint */
        "B arrêter après ce jeu", /* batch.hint_running */
        "Quand les deux côtés ont changé", /* batch.policy */
        "Me demander pour chacun", /* batch.policy_ask */
        "La même boîte de dialogue qu'un jeu seul, une fois par jeu divergent. Bien pour quelques-uns, fatigant pour beaucoup.", /* batch.policy_ask_hint */
        "Envoyer celles de cette console", /* batch.policy_local */
        "La sauvegarde de cette console est envoyée comme nouvelle version. Le serveur garde tout ce qu'il avait, l'autre côté reste donc récupérable.", /* batch.policy_local_hint */
        "Récupérer celles du serveur", /* batch.policy_server */
        "La sauvegarde du serveur écrase celle de cette console. Chacune est d'abord copiée sur la carte SD, donc ce qui est remplacé y reste.", /* batch.policy_server_hint */
        "{0} sur {1}", /* batch.running */
        "Arrêté. Tout ce qui était terminé avant ce point l'est, et rien n'est resté à moitié écrit.", /* batch.stopped */
        "Synchroniser tous les jeux avec le serveur", /* batch.sync */
        "Envoie ce que seule cette console a changé et récupère ce que seul le serveur a changé. Ce qui se passe quand les deux ont changé est la question suivante.", /* batch.sync_hint */
        "Tous les jeux", /* batch.title */
        "Annuler", /* btn.cancel */
        "Non", /* btn.no */
        "OK", /* btn.ok */
        "Oui", /* btn.yes */
        "La sauvegarde n'a pas pu être validée. Ne lancez pas le jeu avant d'avoir résolu ce problème.", /* commit.failed */
        "Sauvegarder la partie de {0} sur la carte SD ?", /* confirm.backup */
        "Supprimer cette sauvegarde ? La partie sur la console n'est pas touchée.", /* confirm.delete_backup */
        "Restaurer {0} sur cette console ? Une sauvegarde locale est créée d'abord.", /* confirm.restore */
        "Envoyer la sauvegarde de {0} vers le serveur ?", /* confirm.upload */
        "{0} a aussi été modifié sur un autre appareil. Les deux versions sont conservées. Choisissez celle à utiliser maintenant.", /* conflict.explain */
        "Tout conserver et décider plus tard", /* conflict.keep_both */
        "Utiliser la sauvegarde de cette console ({0}, enregistrée le {1})", /* conflict.keep_local */
        "Utiliser la sauvegarde du serveur ({0}, du {1})", /* conflict.keep_server */
        "Sauvegardes en conflit", /* conflict.title */
        "Le paquet de sauvegarde est endommagé.", /* err.archive_error */
        "La console a refusé l'opération sur la sauvegarde.", /* err.backend_error */
        "Tampon interne trop petit.", /* err.buffer_too_small */
        "La sauvegarde téléchargée est endommagée.", /* err.checksum_mismatch */
        "L'accès de cette console a été révoqué. Associez-la de nouveau.", /* err.device_revoked */
        "Ce titre n'a aucune sauvegarde à copier.", /* err.empty_save */
        "Cette sauvegarde n'appartient pas à ce compte.", /* err.forbidden */
        "Le serveur a rencontré un problème.", /* err.internal_error */
        "Le paquet de sauvegarde est illisible.", /* err.invalid_manifest */
        "Le serveur a rejeté la requête.", /* err.invalid_request */
        "Impossible de lire ou d'écrire la sauvegarde.", /* err.io_error */
        "Impossible de joindre le serveur.", /* err.network_error */
        "Aucun serveur configuré. Ouvre les Réglages et saisis l'adresse et le jeton.", /* err.no_server */
        "Espace insuffisant sur la carte SD.", /* err.no_space */
        "Introuvable sur le serveur.", /* err.not_found */
        "Mémoire insuffisante.", /* err.out_of_memory */
        "Le code d'association a expiré. Recommencez.", /* err.pairing_expired */
        "En attente d'approbation.", /* err.pairing_pending */
        "Les données n'ont pas pu être lues.", /* err.parse_error */
        "Trop de requêtes. Réessayez dans un instant.", /* err.rate_limited */
        "La sauvegarde dépasse la taille autorisée par le serveur.", /* err.save_too_large */
        "Ce code de partage a expiré.", /* err.share_expired */
        "Le serveur n'a pas répondu à temps.", /* err.timeout */
        "Impossible de lire la liste des jeux.", /* err.title_list */
        "Le certificat du serveur n'a pas pu être vérifié.", /* err.tls_error */
        "Cette console n'est pas connectée. Associez-la de nouveau.", /* err.unauthorized */
        "Non pris en charge.", /* err.unsupported */
        "Cette console n'est pas prise en charge par le serveur.", /* err.unsupported_platform */
        "Annulé.", /* err.user_cancelled */
        "Le serveur a une sauvegarde plus récente. Choisissez la version à conserver.", /* err.version_conflict */
        "Aucun jeu avec une sauvegarde n'a été trouvé.", /* grid.empty */
        "rien de sélectionné", /* grid.nothing_selected */
        "{0} sauvegardes", /* grid.saves */
        "A restaurer   X supprimer   B retour", /* hint.backups */
        "A choisir   B retour   haut/bas déplacer", /* hint.choose */
        "A continuer", /* hint.continue */
        "A modifier   B retour   haut/bas déplacer", /* hint.edit */
        "A sauvegarder   Y restaurer   X analyser   L/R bibliothèque   START quitter", /* hint.grid */
        "Français", /* lang.name */
        "Jeux 3DS", /* lib.3ds */
        "Sauvegardes nds-bootstrap", /* lib.nds */
        "Lecture des sauvegardes", /* loading.backups */
        "Lecture des icônes", /* loading.icons */
        "Lecture des jeux", /* loading.titles */
        "Sauvegarder cette partie", /* menu.backup */
        "Tous les jeux", /* menu.batch */
        "Restaurer depuis une sauvegarde", /* menu.restore */
        "Autotest (détruit cette partie)", /* menu.selftest */
        "Réglages", /* menu.settings */
        "Analyser tous les jeux et écrire sur la carte SD", /* menu.survey */
        "Synchroniser avec le serveur", /* menu.sync */
        "Sauvegarde", /* op.backup */
        "Restauration", /* op.restore */
        "Valeur sécurisée", /* op.secure_value */
        "Analyse", /* op.survey */
        "Synchronisation", /* op.sync */
        "Vise le code de la page web avec la caméra.   B annuler", /* pair.aim */
        "Associée. La synchronisation est possible.", /* pair.done */
        "Saisis le code à six chiffres affiché sur la page web.", /* pair.enter_code */
        "Impossible de démarrer la caméra.", /* pair.no_camera */
        "Renseigne d'abord l'adresse du serveur, ou scanne un code : un code scanné contient l'adresse.", /* pair.no_server */
        "Scanner un code QR", /* pair.scan */
        "L/R caméra   X/Y mode d'aperçu   B annuler", /* pair.switch */
        "Associer cette console", /* pair.title */
        "Ce n'est pas un code d'association DaeMoon.", /* pair.wrong_code */
        "Téléchargement en cours", /* progress.downloading */
        "Compression de la sauvegarde", /* progress.packing */
        "Extraction de la sauvegarde", /* progress.unpacking */
        "Envoi en cours", /* progress.uploading */
        "Vérification", /* progress.verifying */
        "{0} a échoué. {1}", /* report.failed */
        "{0} : terminé.", /* report.ok */
        "Cette version n'a pas d'archive de sauvegarde propre. Compile avec SAVEDATA_SIZE=128K.", /* selftest.no_archive */
        "DaeMoon lui-même", /* selftest.self */
        "Ceci DÉTRUIT la partie de {0}. Utilise un jeu de test. Une sauvegarde est faite d'abord, mais ne compte pas dessus.", /* selftest.warning */
        "Nom de cette console", /* settings.label */
        "Langue", /* settings.language */
        "Selon la console ({0})", /* settings.language_auto */
        "Cette console n'a pas de police pour {0}, le texte serait vide. La langue n'a pas été changée.", /* settings.no_font */
        "Impossible d'écrire les réglages sur la carte SD.", /* settings.save_failed */
        "Enregistré. Cette console utilisera ces réglages désormais.", /* settings.saved */
        "Adresse du serveur", /* settings.server */
        "Réglages", /* settings.title */
        "Jeton de l'appareil", /* settings.token */
        "non défini", /* settings.unset */
        "Revoir l'accueil", /* settings.welcome */
        "Conflit", /* sync.action_conflict */
        "Télécharger", /* sync.action_download */
        "À jour", /* sync.action_none */
        "Envoyer", /* sync.action_upload */
        "Synchronisation terminée. {0} mis à jour, {1} ignorés.", /* sync.done */
        "{0} envoyées, {1} téléchargées, {2} inchangées, {3} conflits.", /* sync.result */
        "{0} est déjà à jour.", /* sync.up_to_date */
        "pas de valeur sécurisée", /* title.no_secure_value */
        "valeur sécurisée {0}", /* title.secure_value */
        "La somme de contrôle ne correspond pas. La restauration a été annulée et rien n'a été modifié.", /* verify.failed */
        "Mode applet avec mémoire limitée. Lancez l'application depuis un jeu pour accéder à toutes les fonctions.", /* warn.applet_mode */
        "Fermez le jeu avant de synchroniser. Synchroniser pendant une partie corrompt la sauvegarde.", /* warn.game_running */
        "{0} lie sa sauvegarde à cette console. Une sauvegarde venant d'une autre console peut être supprimée par le jeu.", /* warn.secure_value */
        "Connecte-toi à ton serveur", /* welcome.connect */
        "Connecte-toi au panneau dans un navigateur et appuie sur Ajouter une console. Un code s'affiche.", /* welcome.connect_how */
        "A choisir   haut/bas déplacer   START passer", /* welcome.hint_choose */
        "A suivant   START passer", /* welcome.hint_intro */
        "Rien n'est connecté, et la sauvegarde sur carte SD fonctionne quand même. Le serveur et l'association sont dans Réglages quand tu veux.", /* welcome.later */
        "Saisir l'adresse et le code", /* welcome.opt_code */
        "Pour quand la caméra n'arrive pas à lire un écran. Deux choses à saisir au clavier, et ça marche toujours.", /* welcome.opt_code_hint */
        "Pas maintenant", /* welcome.opt_later */
        "La sauvegarde sur la carte SD fonctionne sans serveur. Les choix de cet écran sont dans Réglages quand tu veux.", /* welcome.opt_later_hint */
        "Scanner le code QR", /* welcome.opt_qr */
        "Rien à saisir. Le code contient l'adresse du serveur, donc aucune adresse n'est à régler d'abord.", /* welcome.opt_qr_hint */
        "Cette console est connectée. Fais d'abord une sauvegarde et une restauration sur un jeu qui ne compte pas, avant de lui confier celui qui compte.", /* welcome.ready */
        "Une sauvegarde locale est toujours faite avant toute restauration, et un conflit n'est jamais fusionné à ta place : les deux versions sont gardées et tu choisis.", /* welcome.safe */
        "Bienvenue", /* welcome.title */
        "DaeMoon copie les sauvegardes de cette console vers un serveur que tu héberges, et les ramène. La même sauvegarde sur deux consoles, sans déplacer la carte.", /* welcome.what */
        "Synchronise avant de lancer un jeu ou après l'avoir quitté, jamais pendant qu'il tourne. Un jeu garde sa sauvegarde ouverte, et y écrire à ce moment la casse.", /* welcome.when */
    },
    /* de */ {
        "DaeMoon", /* app.title */
        "Die Datumsangaben stammen von der Uhr der Konsole. Sie beschreiben eine Sicherung; sie entscheiden nie, welcher Spielstand neuer ist.", /* backup.clock_note */
        "Sicherung des aktuellen Spielstands wird erstellt", /* backup.creating */
        "Die Sicherung wurde gelöscht. Der Spielstand auf der Konsole blieb unberührt.", /* backup.deleted */
        "Lokale Sicherung fehlgeschlagen. Es wurde nichts geändert.", /* backup.failed */
        "Sicherungen von {0}", /* backup.list */
        "Datum unbekannt", /* backup.no_date */
        "Noch keine Sicherung von {0}.", /* backup.none */
        "identisch mit dem Spielstand, der jetzt auf der Konsole liegt", /* backup.same_as_console */
        "Alle Spielstände auf die SD-Karte sichern", /* batch.backup */
        "{0} gesichert, {1} übersprungen, {2} fehlgeschlagen.", /* batch.backup_done */
        "Liest jeden Spielstand dieser Bibliothek und schreibt je ein Paket. Auf Konsole und Server ändert sich nichts.", /* batch.backup_hint */
        "Alle {0} Spielstände dieser Bibliothek auf die SD-Karte sichern?", /* batch.confirm_backup */
        "Alle {0} Titel abgleichen? Wo beide Seiten geändert wurden: {1}", /* batch.confirm_sync */
        "Alle {0} Titel abgleichen und überall dort die Version des Servers nehmen, wo sie sich unterscheiden? Spielstände auf dieser Konsole werden überschrieben. Jeder wird vorher auf die SD-Karte gesichert.", /* batch.confirm_sync_server */
        "In dieser Bibliothek gibt es nichts zu tun.", /* batch.empty */
        "A starten   hoch/runter bewegen   B zurück", /* batch.hint */
        "B nach diesem Titel anhalten", /* batch.hint_running */
        "Wenn beide Seiten geändert wurden", /* batch.policy */
        "Bei jedem nachfragen", /* batch.policy_ask */
        "Derselbe Dialog wie bei einem einzelnen Titel, einmal je abweichendem Titel. Bei wenigen richtig, bei vielen ermüdend.", /* batch.policy_ask_hint */
        "Die dieser Konsole hochladen", /* batch.policy_local */
        "Der Spielstand dieser Konsole kommt als neue Version obenauf. Der Server behält alles, was er hatte, die andere Seite bleibt also erreichbar.", /* batch.policy_local_hint */
        "Die des Servers herunterladen", /* batch.policy_server */
        "Der Spielstand des Servers wird über den dieser Konsole geschrieben. Jeder wird vorher auf die SD-Karte gesichert, das Ersetzte bleibt also auf der Karte.", /* batch.policy_server_hint */
        "{0} von {1}", /* batch.running */
        "Angehalten. Alles vor diesem Punkt Abgeschlossene ist fertig, und nichts blieb halb geschrieben.", /* batch.stopped */
        "Alle Titel mit dem Server abgleichen", /* batch.sync */
        "Lädt hoch, was nur diese Konsole geändert hat, und herunter, was nur der Server geändert hat. Was passiert, wenn beide geändert haben, ist die nächste Frage.", /* batch.sync_hint */
        "Alle Titel", /* batch.title */
        "Abbrechen", /* btn.cancel */
        "Nein", /* btn.no */
        "OK", /* btn.ok */
        "Ja", /* btn.yes */
        "Der Spielstand konnte nicht festgeschrieben werden. Starte das Spiel erst, wenn das behoben ist.", /* commit.failed */
        "Den Spielstand von {0} auf die SD-Karte sichern?", /* confirm.backup */
        "Diese Sicherung löschen? Der Spielstand auf der Konsole bleibt unberührt.", /* confirm.delete_backup */
        "{0} auf dieser Konsole wiederherstellen? Zuvor wird eine lokale Sicherung erstellt.", /* confirm.restore */
        "Spielstand von {0} auf den Server hochladen?", /* confirm.upload */
        "{0} wurde auch auf einem anderen Gerät geändert. Beide Fassungen bleiben erhalten. Wähle, welche jetzt verwendet wird.", /* conflict.explain */
        "Beide behalten und später entscheiden", /* conflict.keep_both */
        "Spielstand dieser Konsole verwenden ({0}, gespeichert am {1})", /* conflict.keep_local */
        "Spielstand vom Server verwenden ({0}, vom {1})", /* conflict.keep_server */
        "Widersprüchliche Spielstände", /* conflict.title */
        "Das Spielstandpaket ist beschädigt.", /* err.archive_error */
        "Die Konsole hat den Zugriff auf den Spielstand abgelehnt.", /* err.backend_error */
        "Interner Puffer zu klein.", /* err.buffer_too_small */
        "Der heruntergeladene Spielstand ist beschädigt.", /* err.checksum_mismatch */
        "Der Zugriff dieser Konsole wurde entzogen. Koppel sie erneut.", /* err.device_revoked */
        "Dieser Titel hat keinen Spielstand zum Sichern.", /* err.empty_save */
        "Dieser Spielstand gehört nicht zu diesem Konto.", /* err.forbidden */
        "Auf dem Server ist ein Problem aufgetreten.", /* err.internal_error */
        "Das Spielstandpaket ist nicht lesbar.", /* err.invalid_manifest */
        "Der Server hat die Anfrage abgelehnt.", /* err.invalid_request */
        "Der Spielstand konnte nicht gelesen oder geschrieben werden.", /* err.io_error */
        "Der Server ist nicht erreichbar.", /* err.network_error */
        "Kein Server eingerichtet. Adresse und Token in den Einstellungen eintragen.", /* err.no_server */
        "Nicht genug Platz auf der SD-Karte.", /* err.no_space */
        "Auf dem Server nicht gefunden.", /* err.not_found */
        "Nicht genug Speicher.", /* err.out_of_memory */
        "Der Kopplungscode ist abgelaufen. Beginne von vorn.", /* err.pairing_expired */
        "Warten auf Bestätigung.", /* err.pairing_pending */
        "Die Daten konnten nicht gelesen werden.", /* err.parse_error */
        "Zu viele Anfragen. Versuche es gleich noch einmal.", /* err.rate_limited */
        "Der Spielstand ist größer als der Server erlaubt.", /* err.save_too_large */
        "Dieser Freigabecode ist abgelaufen.", /* err.share_expired */
        "Der Server hat nicht rechtzeitig geantwortet.", /* err.timeout */
        "Die Titelliste konnte nicht gelesen werden.", /* err.title_list */
        "Das Zertifikat des Servers konnte nicht geprüft werden.", /* err.tls_error */
        "Diese Konsole ist nicht angemeldet. Koppel sie erneut.", /* err.unauthorized */
        "Wird nicht unterstützt.", /* err.unsupported */
        "Diese Konsole wird vom Server nicht unterstützt.", /* err.unsupported_platform */
        "Abgebrochen.", /* err.user_cancelled */
        "Der Server hat einen neueren Spielstand. Wähle, welche Fassung bleibt.", /* err.version_conflict */
        "Keine Titel mit Spielständen gefunden.", /* grid.empty */
        "nichts ausgewählt", /* grid.nothing_selected */
        "{0} Spielstände", /* grid.saves */
        "A wiederherstellen   X löschen   B zurück", /* hint.backups */
        "A wählen   B zurück   hoch/runter bewegen", /* hint.choose */
        "A weiter", /* hint.continue */
        "A bearbeiten   B zurück   hoch/runter bewegen", /* hint.edit */
        "A sichern   Y wiederherstellen   X erfassen   L/R Bibliothek   START beenden", /* hint.grid */
        "Deutsch", /* lang.name */
        "3DS-Titel", /* lib.3ds */
        "nds-bootstrap-Spielstände", /* lib.nds */
        "Sicherungen werden gelesen", /* loading.backups */
        "Symbole werden gelesen", /* loading.icons */
        "Titel werden gelesen", /* loading.titles */
        "Diesen Spielstand sichern", /* menu.backup */
        "Alle Titel", /* menu.batch */
        "Aus einer Sicherung wiederherstellen", /* menu.restore */
        "Selbsttest (zerstört diesen Spielstand)", /* menu.selftest */
        "Einstellungen", /* menu.settings */
        "Alle Titel erfassen und auf die SD-Karte schreiben", /* menu.survey */
        "Mit dem Server abgleichen", /* menu.sync */
        "Sicherung", /* op.backup */
        "Wiederherstellung", /* op.restore */
        "Sicherheitswert", /* op.secure_value */
        "Erfassung", /* op.survey */
        "Abgleich", /* op.sync */
        "Die Kamera auf den Code der Webseite richten.   B abbrechen", /* pair.aim */
        "Verbunden. Diese Konsole kann jetzt abgleichen.", /* pair.done */
        "Gib den sechsstelligen Code von der Webseite ein.", /* pair.enter_code */
        "Die Kamera konnte nicht gestartet werden.", /* pair.no_camera */
        "Zuerst die Serveradresse eintragen, oder einen Code scannen - ein gescannter Code enthält die Adresse.", /* pair.no_server */
        "QR-Code scannen", /* pair.scan */
        "L/R Kamera   X/Y Vorschaumodus   B abbrechen", /* pair.switch */
        "Diese Konsole verbinden", /* pair.title */
        "Das ist kein DaeMoon-Verbindungscode.", /* pair.wrong_code */
        "Wird heruntergeladen", /* progress.downloading */
        "Spielstand wird gepackt", /* progress.packing */
        "Spielstand wird entpackt", /* progress.unpacking */
        "Wird hochgeladen", /* progress.uploading */
        "Wird geprüft", /* progress.verifying */
        "{0} fehlgeschlagen. {1}", /* report.failed */
        "{0}: fertig.", /* report.ok */
        "Dieser Build hat kein eigenes Speicherarchiv. Mit SAVEDATA_SIZE=128K bauen.", /* selftest.no_archive */
        "DaeMoon selbst", /* selftest.self */
        "Das ZERSTÖRT den Spielstand von {0}. Nur mit einem Testtitel verwenden. Vorher wird gesichert, aber verlass dich nicht darauf.", /* selftest.warning */
        "Name dieser Konsole", /* settings.label */
        "Sprache", /* settings.language */
        "Wie die Konsole ({0})", /* settings.language_auto */
        "Diese Konsole hat keine Schrift für {0}, der Text bliebe leer. Die Sprache wurde nicht geändert.", /* settings.no_font */
        "Die Einstellungen konnten nicht auf die SD-Karte geschrieben werden.", /* settings.save_failed */
        "Gespeichert. Diese Konsole verwendet sie ab jetzt.", /* settings.saved */
        "Serveradresse", /* settings.server */
        "Einstellungen", /* settings.title */
        "Gerätetoken", /* settings.token */
        "nicht gesetzt", /* settings.unset */
        "Willkommen erneut anzeigen", /* settings.welcome */
        "Konflikt", /* sync.action_conflict */
        "Herunterladen", /* sync.action_download */
        "Aktuell", /* sync.action_none */
        "Hochladen", /* sync.action_upload */
        "Abgleich beendet. {0} aktualisiert, {1} übersprungen.", /* sync.done */
        "{0} hochgeladen, {1} heruntergeladen, {2} unverändert, {3} Konflikte.", /* sync.result */
        "{0} ist bereits aktuell.", /* sync.up_to_date */
        "kein Sicherheitswert", /* title.no_secure_value */
        "Sicherheitswert {0}", /* title.secure_value */
        "Die Prüfsumme stimmt nicht. Die Wiederherstellung wurde abgebrochen, es wurde nichts geändert.", /* verify.failed */
        "Applet-Modus mit stark begrenztem Speicher. Starte die Anwendung über ein Spiel, um alle Funktionen zu nutzen.", /* warn.applet_mode */
        "Beende das Spiel vor dem Abgleich. Ein Abgleich bei laufendem Spiel beschädigt den Spielstand.", /* warn.game_running */
        "{0} bindet seinen Spielstand an diese Konsole. Ein Spielstand von einer anderen Konsole kann vom Spiel gelöscht werden.", /* warn.secure_value */
        "Mit deinem Server verbinden", /* welcome.connect */
        "Melde dich im Browser am Panel an und drücke Konsole hinzufügen. Es zeigt einen Code.", /* welcome.connect_how */
        "A wählen   hoch/runter bewegen   START überspringen", /* welcome.hint_choose */
        "A weiter   START überspringen", /* welcome.hint_intro */
        "Es ist nichts verbunden, und Sichern auf die SD-Karte funktioniert trotzdem. Server und Verbindung stehen in den Einstellungen bereit.", /* welcome.later */
        "Adresse und Code eintippen", /* welcome.opt_code */
        "Für den Fall, dass die Kamera einen Bildschirm nicht lesen kann. Zwei Dinge über die Tastatur, und es klappt immer.", /* welcome.opt_code_hint */
        "Jetzt nicht", /* welcome.opt_later */
        "Sichern auf die SD-Karte geht auch ohne Server. Die Auswahl dieses Bildschirms steht jederzeit in den Einstellungen.", /* welcome.opt_later_hint */
        "QR-Code scannen", /* welcome.opt_qr */
        "Nichts zu tippen. Der Code enthält die Serveradresse, es muss also vorher keine Adresse gesetzt werden.", /* welcome.opt_qr_hint */
        "Diese Konsole ist verbunden. Sichere und stelle zuerst ein Spiel wieder her, an dem dir nichts liegt, bevor du ihr eines anvertraust, an dem dir etwas liegt.", /* welcome.ready */
        "Vor jeder Wiederherstellung wird zuerst lokal gesichert, und ein Konflikt wird nie für dich zusammengeführt: beide Fassungen bleiben, und du entscheidest.", /* welcome.safe */
        "Willkommen", /* welcome.title */
        "DaeMoon kopiert die Spielstände dieser Konsole auf einen Server, den du selbst betreibst, und holt sie zurück. Derselbe Spielstand auf zwei Konsolen, ohne die Karte zu tauschen.", /* welcome.what */
        "Synchronisiere vor dem Start eines Spiels oder nach dem Beenden, nie während eines läuft. Ein Spiel hält seinen Spielstand offen, und ein Schreibzugriff zerstört ihn dann.", /* welcome.when */
    },
};

const char *const daemoon_lang_codes[DAEMOON_LANG_COUNT] = {
    "en",
    "ko",
    "ja",
    "zh-Hans",
    "zh-Hant",
    "es",
    "fr",
    "de",
};
