/* 3DS entry point. Phase 1: local backup and restore, no server involved.
 *
 * Everything below the platform layer already exists and is tested on a desktop.
 * This file assembles a daemoon_env_t out of libctru and draws a grid of game
 * icons, because the question this application asks - which game's save do you
 * want to overwrite - is not one anybody should answer from a product code.
 *
 * The scratch buffer is static rather than malloc'd. The 3DS heap fragments
 * badly, this one lives for the whole run, and there is nothing to gain from
 * putting it on the heap and a slow loss of headroom to lose.
 */
#include "daemoon_3ds.h"
#include "gfx.h"
#include "icons.h"

#include "../../../tools/test/backend_conformance.h"
#include "../../../tools/test/test.h"

#include <daemoon/archive.h>
#include <daemoon/i18n.h>
#include <daemoon/sync.h>
#include <daemoon/util/strbuf.h>

#include <3ds.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by the Makefile. Says which build this is, so "did the install take"
 * is answered by the screen rather than inferred from behaviour. */
#include "build_stamp.h"

#ifndef DAEMOON_BUILD_STAMP
#define DAEMOON_BUILD_STAMP "unknown"
#endif

/* Enough icons for a console with a lot of saves. Past this the grid still works
 * and the rest draw a placeholder, which is a better failure than refusing to
 * list them. */
#define MAX_ICONS 128

#define GRID_COLS   6
#define GRID_ROWS   3
#define GRID_CELL_W 64.0f
#define GRID_CELL_H 74.0f
#define GRID_X      ((GFX_TOP_W - GRID_COLS * GRID_CELL_W) / 2.0f)
#define GRID_Y      36.0f
#define GRID_PAGE   (GRID_COLS * GRID_ROWS)

/* libctru's weak default is 32 KiB, and `StackSize` in app.rsf does not override
 * it - the exheader value is not what the main thread ends up running on. Thirty
 * two kilobytes is not enough for this application:
 *
 *   - the first restore ever run on hardware died because one function wanted
 *     fifty of them for a single frame. That frame is gone, but the ceiling it hit
 *     was this one, and it sat about thirty kilobytes above the floor.
 *   - curl and mbedtls are linked in. A TLS handshake alone is tens of kilobytes
 *     of stack, and Phase 2 is where https starts mattering.
 *
 * A quarter of a megabyte of address space costs nothing on a console with tens of
 * megabytes of it, and the failure it prevents is a data abort with no message. */
unsigned int __stacksize__ = 256 * 1024;

static unsigned char g_scratch[64 * 1024];
static daemoon_archive_ctx_t g_archive;

static daemoon_3ds_save_ctx_t g_save_ctx;
static daemoon_3ds_nds_ctx_t  g_nds_ctx;
static daemoon_3ds_net_ctx_t  g_net_ctx;
static daemoon_3ds_config_t   g_config;
/* Which library is on screen: the console's own titles, or the DS saves
 * nds-bootstrap keeps as plain files. Phase 2 syncs the second one first because
 * nothing about it can fail in a way unique to the platform. */
static int g_source_nds;
static daemoon_3ds_ui_ctx_t   g_ui_ctx;
static daemoon_env_t          g_env;

static daemoon_title_t   *g_titles;
static size_t             g_title_count;
static daemoon_3ds_icon_t g_icons[MAX_ICONS];

static int g_selected;
static int g_scroll;

/* --------------------------------------------------------------------- i18n */

static daemoon_lang_t select_language(void)
{
    u8 code = 0;
    daemoon_lang_t lang = DAEMOON_LANG_EN;

    g_save_ctx.smdh_language = 1; /* English, until the console says otherwise */

    if (R_FAILED(CFGU_GetSystemLanguage(&code))) {
        return lang;
    }
    switch (code) {
    case CFG_LANGUAGE_JP: (void)daemoon_i18n_language_from_code("ja", &lang); break;
    case CFG_LANGUAGE_FR: (void)daemoon_i18n_language_from_code("fr", &lang); break;
    case CFG_LANGUAGE_DE: (void)daemoon_i18n_language_from_code("de", &lang); break;
    case CFG_LANGUAGE_ES: (void)daemoon_i18n_language_from_code("es", &lang); break;
    case CFG_LANGUAGE_ZH: (void)daemoon_i18n_language_from_code("zh-Hans", &lang); break;
    case CFG_LANGUAGE_KO: (void)daemoon_i18n_language_from_code("ko", &lang); break;
    case CFG_LANGUAGE_TW: (void)daemoon_i18n_language_from_code("zh-Hant", &lang); break;
    default:              lang = DAEMOON_LANG_EN; break;
    }
    daemoon_i18n_set_language(lang);

    /* The SMDH title index is the console's own language numbering, so a title's
     * name comes back in the language the HOME menu shows it in. */
    g_save_ctx.smdh_language = (int)code;
    return lang;
}

/* ------------------------------------------------------------------- titles */

static unsigned long long tid_of(const daemoon_title_t *t)
{
    unsigned long long id = 0;

    (void)daemoon_3ds_parse_title_id(t->id, &id);
    return id;
}

static void free_icons(void)
{
    size_t i;

    for (i = 0; i < MAX_ICONS; ++i) {
        daemoon_3ds_icon_free(&g_icons[i]);
    }
}

/* One frame of the loading screen. Reading the list opens every save archive on
 * the console, so this runs for as long as that takes and a still screen would
 * look like a hang. */
static void draw_loading(const char *what, unsigned done, unsigned total)
{
    char line[96];

    daemoon_gfx_frame_begin();
    daemoon_gfx_top();
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
    daemoon_gfx_text(12.0f, 6.0f, 0.55f, GFX_TEXT, daemoon_str(DAEMOON_STR_APP_TITLE));

    if (total > 0) {
        (void)snprintf(line, sizeof(line), "%s  %u/%u", what, done, total);
    } else {
        (void)snprintf(line, sizeof(line), "%s", what);
    }
    daemoon_gfx_text(12.0f, 100.0f, 0.5f, GFX_TEXT_DIM, line);

    if (total > 0) {
        float w = (GFX_TOP_W - 24.0f) * (float)done / (float)total;

        daemoon_gfx_rect(12.0f, 126.0f, GFX_TOP_W - 24.0f, 6.0f, GFX_PANEL);
        daemoon_gfx_rect(12.0f, 126.0f, w, 6.0f, GFX_ACCENT);
    }
    daemoon_gfx_frame_end();
}

static void loading_progress(void *user, unsigned done, unsigned total)
{
    (void)user;
    draw_loading("reading titles", done, total);
}

static daemoon_result_t reload_titles(void)
{
    daemoon_result_t r;
    size_t i;

    free_icons();
    if (g_titles != NULL) {
        g_env.save->free_titles(g_env.save_ctx, g_titles, g_title_count);
        g_titles = NULL;
        g_title_count = 0;
    }

    /* The backend and its context change together. Getting that pair out of step
     * would point save operations at the wrong library entirely. */
    if (g_source_nds) {
        g_env.save = &daemoon_3ds_nds_backend;
        g_env.save_ctx = &g_nds_ctx;
    } else {
        g_env.save = &daemoon_3ds_save_backend;
        g_env.save_ctx = &g_save_ctx;
    }

    r = g_env.save->list_titles(g_env.save_ctx, &g_titles, &g_title_count);
    if (r != DAEMOON_OK) {
        return r;
    }

    if (!g_source_nds) {
        for (i = 0; i < g_title_count && i < MAX_ICONS; ++i) {
            draw_loading("reading icons", (unsigned)i, (unsigned)g_title_count);
            /* The same SMDH the name came from, already in the cache by now, so
             * this loop costs a texture upload rather than a decrypt per title. */
            (void)daemoon_3ds_icon_upload(
                daemoon_3ds_cache_icon(g_save_ctx.cache, g_save_ctx.media,
                                       tid_of(&g_titles[i])),
                &g_icons[i]);
        }
        /* Written back once the list is complete, not per title: a title that was
         * skipped this run is a title that is no longer installed, and that is
         * only known at the end. */
        (void)daemoon_3ds_cache_flush(g_save_ctx.cache, DAEMOON_3DS_CACHE_PATH);
    }
    if (g_selected >= (int)g_title_count) {
        g_selected = g_title_count > 0 ? (int)g_title_count - 1 : 0;
    }
    return DAEMOON_OK;
}

/* ------------------------------------------------------------------ drawing */

static void draw_grid(void)
{
    char right[96];
    float w;
    int i;
    int first = g_scroll * GRID_COLS;

    daemoon_gfx_top();
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
    daemoon_gfx_text(10.0f, 5.0f, 0.55f, GFX_TEXT, daemoon_str(DAEMOON_STR_APP_TITLE));
    daemoon_gfx_text(96.0f, 9.0f, 0.4f, GFX_ACCENT,
                     g_source_nds ? "nds-bootstrap saves" : "3DS titles");

    if (g_title_count > GRID_PAGE) {
        (void)snprintf(right, sizeof(right), "%d/%u   %s", g_selected + 1,
                       (unsigned)g_title_count, DAEMOON_BUILD_STAMP);
    } else {
        (void)snprintf(right, sizeof(right), "%u saves   %s", (unsigned)g_title_count,
                       DAEMOON_BUILD_STAMP);
    }
    w = daemoon_gfx_text_width(0.36f, right);
    daemoon_gfx_text(GFX_TOP_W - w - 8.0f, 10.0f, 0.36f, GFX_TEXT_DIM, right);

    for (i = 0; i < GRID_PAGE; ++i) {
        int index = first + i;
        float x = GRID_X + (float)(i % GRID_COLS) * GRID_CELL_W;
        float y = GRID_Y + (float)(i / GRID_COLS) * GRID_CELL_H;

        if (index >= (int)g_title_count) {
            break;
        }

        if (index == g_selected) {
            daemoon_gfx_rect(x, y - 2.0f, GRID_CELL_W - 4.0f, GRID_CELL_H - 6.0f,
                             GFX_ACCENT);
        }

        if (index < MAX_ICONS && g_icons[index].loaded) {
            C2D_DrawImageAt(g_icons[index].image, x + 6.0f, y + 2.0f, 0.0f, NULL,
                            1.0f, 1.0f);
        } else {
            /* No icon is normal for some titles. A flat tile keeps the grid
             * aligned, which a gap would not. */
            daemoon_gfx_rect(x + 6.0f, y + 2.0f, 48.0f, 48.0f, GFX_PANEL);
        }

        daemoon_gfx_text_fit(x, y + 54.0f, GRID_CELL_W - 4.0f, 0.34f,
                             index == g_selected ? GFX_TEXT : GFX_TEXT_DIM,
                             g_titles[index].name);
    }

    if (g_title_count == 0) {
        daemoon_gfx_text(12.0f, 100.0f, 0.5f, GFX_TEXT_DIM,
                         "No titles with save data were found.");
    }
}

static void draw_details(u32 down, touchPosition touch, int *out_action)
{
    static const char *const labels[] = {
        "Back up this save",
        "Restore from a backup",
        "Sync with the server",
        "Survey every title to the SD card",
        "Self test (destroys this save)"
    };
    const daemoon_title_t *t = NULL;
    char line[160];
    float y = 6.0f;
    int touched = (down & KEY_TOUCH) != 0;
    size_t i;

    if (g_title_count > 0) {
        t = &g_titles[g_selected];
    }

    daemoon_gfx_bottom();

    if (t != NULL) {
        daemoon_gfx_text_fit(4.0f, y, GFX_BOTTOM_W - 8.0f, 0.5f, GFX_TEXT, t->name);
        y += 20.0f;
        daemoon_gfx_text(8.0f, y, 0.36f, GFX_TEXT_DIM, t->id);
        y += 15.0f;

        /* The warning that matters before a restore, on screen before anything is
         * chosen rather than after. */
        {
            daemoon_3ds_secure_value_t secure;

            if (daemoon_3ds_read_secure_value(t, &secure) == DAEMOON_OK && secure.exists) {
                (void)snprintf(line, sizeof(line), "secure value %016llX",
                               (unsigned long long)secure.value);
                daemoon_gfx_text(8.0f, y, 0.34f, GFX_WARN, line);
            } else {
                daemoon_gfx_text(8.0f, y, 0.34f, GFX_TEXT_DIM, "no secure value");
            }
            y += 16.0f;
        }
    } else {
        daemoon_gfx_text(8.0f, y, 0.5f, GFX_TEXT_DIM, "nothing selected");
        y += 40.0f;
    }

    for (i = 0; i < sizeof(labels) / sizeof(labels[0]); ++i) {
        if (daemoon_gfx_button(8.0f, y, GFX_BOTTOM_W - 16.0f, 30.0f, labels[i], 0,
                               down, touch.px, touch.py, touched)) {
            *out_action = (int)i;
        }
        y += 34.0f;
    }

    daemoon_gfx_text(8.0f, GFX_SCREEN_H - 16.0f, 0.34f, GFX_TEXT_DIM,
                     "A back up   Y restore   X survey   L/R library   START exit");
}

/* ------------------------------------------------------------------ actions */

static void message(const char *title, const char *body, u32 accent)
{
    /* main.c has its own dialog loop, so it was the one screen the trail could not
     * see - two syncs in a row ended at "uploading" in the file with no sign of the
     * result the user was looking at. */
    daemoon_3ds_trace("ui/message", body);

    while (aptMainLoop()) {
        u32 down;

        hidScanInput();
        down = hidKeysDown();

        daemoon_gfx_frame_begin();
        daemoon_gfx_top();
        daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, accent);
        daemoon_gfx_text(12.0f, 6.0f, 0.6f, GFX_TEXT, title);
        (void)daemoon_gfx_text_wrapped(12.0f, 56.0f, GFX_TOP_W - 24.0f, 0.5f, GFX_TEXT,
                                       body);
        daemoon_gfx_bottom();
        daemoon_gfx_text(12.0f, 100.0f, 0.5f, GFX_TEXT_DIM, "A continue");
        daemoon_gfx_frame_end();

        if (down & (KEY_A | KEY_B)) {
            return;
        }
    }
}

static void report(const char *what, daemoon_result_t r)
{
    char body[256];

    if (r == DAEMOON_OK) {
        (void)snprintf(body, sizeof(body), "%s: ok", what);
        message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_OK);
        return;
    }
    /* The wire code and the translated text: one for a photograph in a bug
     * report, the other for the person holding the console. */
    (void)snprintf(body, sizeof(body), "%s: %s - %s", what, daemoon_result_code(r),
                   daemoon_str(daemoon_result_str_id(r)));
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_DANGER);
}

static void action_backup(void)
{
    char path[DAEMOON_PATH_MAX * 2];
    daemoon_str_ref_t ask;

    if (g_title_count == 0) {
        return;
    }

    /* Backing up writes only to the SD card and cannot lose a save, so this is not
     * one of the confirmations the rules demand. It is here because the button that
     * makes a backup and the button that overwrites a save are next to each other
     * on a console with no pointer, and being told which title is about to be read
     * is worth one press. */
    daemoon_3ds_trace("backup/begin", g_titles[g_selected].id);
    memset(&ask, 0, sizeof(ask));
    ask.id = DAEMOON_STR_CONFIRM_BACKUP;
    ask.args[0] = g_titles[g_selected].name;
    ask.nargs = 1;
    if (!g_env.ui->confirm(g_env.ui_ctx, &ask)) {
        return;
    }

    {
        daemoon_result_t r = daemoon_sync_backup_local(&g_env, &g_archive,
                                                       &g_titles[g_selected], path,
                                                       sizeof(path));

        daemoon_3ds_trace("backup/done", daemoon_result_code(r));
        report("backup", r);
    }
}

/* The digest of what is on the console right now, so the backup list can say which
 * of its entries would change nothing. Best effort: a title with no archive yet has
 * no digest, and that is not a reason to refuse to show the list. */
static void current_digest(const daemoon_title_t *title, char *out, size_t cap)
{
    daemoon_save_t *save = NULL;
    unsigned long long size = 0;

    out[0] = '\0';
    if (cap < DAEMOON_SHA256_HEX) {
        return;
    }
    if (g_env.save->open_save(g_env.save_ctx, title, &save) != DAEMOON_OK) {
        return;
    }
    if (daemoon_archive_hash_save(&g_env, &g_archive, save, out, &size) != DAEMOON_OK) {
        out[0] = '\0';
    }
    (void)g_env.save->close_save(g_env.save_ctx, save);
}

static void action_restore(void)
{
    char dir[DAEMOON_PATH_MAX * 2];
    char pick[DAEMOON_PATH_MAX * 2];
    char digest[DAEMOON_SHA256_HEX];
    daemoon_strbuf_t sb;
    daemoon_result_t pr;

    if (g_title_count == 0) {
        return;
    }

    daemoon_strbuf_init(&sb, dir, sizeof(dir));
    daemoon_strbuf_add(&sb, DAEMOON_3DS_WORK_DIR);
    daemoon_strbuf_add(&sb, "/backups");
    if (daemoon_strbuf_result(&sb) != DAEMOON_OK) {
        return;
    }

    daemoon_3ds_trace("restore/begin", g_titles[g_selected].id);
    draw_loading("reading backups", 0, 0);
    current_digest(&g_titles[g_selected], digest, sizeof(digest));
    daemoon_3ds_trace("restore/digest", digest[0] != '\0' ? digest : "-");

    pr = daemoon_3ds_pick_backup(&g_env, dir, &g_titles[g_selected], digest, pick,
                                 sizeof(pick));
    daemoon_3ds_trace("restore/picked", daemoon_result_code(pr));
    if (pr == DAEMOON_ERR_NOT_FOUND) {
        char none[256];
        const char *args[1];

        args[0] = g_titles[g_selected].name;
        (void)daemoon_strf(none, sizeof(none), DAEMOON_STR_BACKUP_NONE, args, 1);
        message(daemoon_str(DAEMOON_STR_APP_TITLE), none, GFX_PANEL);
        return;
    }
    if (pr != DAEMOON_OK) {
        return;
    }

    /* The secure value is read before anything is written and put back after. A
     * title that binds its save to this console will otherwise treat the restored
     * save as corrupt and delete it. */
    {
        daemoon_3ds_secure_value_t secure;
        daemoon_result_t sr = daemoon_3ds_read_secure_value(&g_titles[g_selected], &secure);
        daemoon_result_t r;

        daemoon_3ds_trace("restore/secure-read", daemoon_result_code(sr));
        daemoon_3ds_trace("restore/core", pick);
        r = daemoon_sync_restore_package(&g_env, &g_archive, &g_titles[g_selected], pick);
        daemoon_3ds_trace("restore/core-done", daemoon_result_code(r));
        report("restore", r);

        if (r == DAEMOON_OK && sr == DAEMOON_OK && secure.exists) {
            report("secure value",
                   daemoon_3ds_write_secure_value(&g_titles[g_selected], &secure));
            daemoon_3ds_trace("restore/secure-written", NULL);
        }
    }
}

static void append_hex32(daemoon_strbuf_t *sb, unsigned long value)
{
    static const char digits[] = "0123456789ABCDEF";
    char hex[11];
    int k;

    hex[0] = '0';
    hex[1] = 'x';
    for (k = 0; k < 8; ++k) {
        hex[2 + k] = digits[(value >> ((7 - k) * 4)) & 0xf];
    }
    hex[10] = '\0';
    daemoon_strbuf_add(sb, hex);
}

/* Phase 2: the whole sync path, which has been running on a desktop since Phase
 * 0. Nothing about it is new here except the network underneath it. */
static void action_sync(void)
{
    daemoon_sync_stats_t stats;
    char body[256];
    daemoon_result_t r;

    if (g_title_count == 0) {
        return;
    }
    if (!daemoon_3ds_config_can_sync(&g_config)) {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                "No server configured. Put server= and token= in "
                DAEMOON_3DS_CONFIG_PATH, GFX_WARN);
        return;
    }

    memset(&stats, 0, sizeof(stats));
    daemoon_3ds_trace("sync/begin", g_titles[g_selected].id);
    r = daemoon_sync_title(&g_env, &g_archive, &g_titles[g_selected], &stats);
    daemoon_3ds_trace("sync/done", daemoon_result_code(r));

    if (r != DAEMOON_OK) {
        report("sync", r);
        return;
    }
    (void)snprintf(body, sizeof(body), "uploaded %u  downloaded %u  skipped %u  "
                   "conflicts %u", stats.uploaded, stats.downloaded, stats.skipped,
                   stats.conflicts);
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_OK);
}

static int survey_count_cb(void *user, const char *path, unsigned long long size)
{
    unsigned long long *total = (unsigned long long *)user;

    (void)path;
    *total += size;
    return 0;
}

/* Reads every title once and writes what it found to the SD card.
 *
 * Read only: it opens save archives, counts what is in them, and asks for each
 * title's secure value. Nothing is written to any archive. The two open questions
 * of this phase are answered by data about a whole console, and reading that off a
 * screen one title at a time is how a survey turns into three titles and a guess.
 */
static void action_survey(void)
{
    daemoon_stream_t *out = NULL;
    daemoon_result_t r;
    size_t i;

    r = g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/survey.txt",
                       DAEMOON_OPEN_WRITE, &out);
    if (r != DAEMOON_OK) {
        report("survey", r);
        return;
    }

    {
        char header[160];
        daemoon_strbuf_t hb;

        daemoon_strbuf_init(&hb, header, sizeof(header));
        daemoon_strbuf_add(&hb, "# DaeMoon build ");
        daemoon_strbuf_add(&hb, DAEMOON_BUILD_STAMP);
        daemoon_strbuf_add(&hb, " font=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)daemoon_gfx_font_source());
        daemoon_strbuf_add(&hb, " ascii_names=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)g_save_ctx.ascii_names);
        daemoon_strbuf_add(&hb, " smdh_lang=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)g_save_ctx.smdh_language);
        daemoon_strbuf_addc(&hb, '\n');
        (void)daemoon_stream_write(out, header, hb.len);
    }

    for (i = 0; i < g_title_count; ++i) {
        daemoon_title_t *t = &g_titles[i];
        daemoon_3ds_secure_value_t secure;
        daemoon_save_t *save = NULL;
        unsigned long long bytes = 0;
        char line[512];
        daemoon_strbuf_t sb;
        daemoon_result_t sr;
        daemoon_result_t or_;

        memset(&secure, 0, sizeof(secure));
        sr = daemoon_3ds_read_secure_value(t, &secure);

        or_ = g_env.save->open_save(g_env.save_ctx, t, &save);
        if (or_ == DAEMOON_OK) {
            (void)g_env.save->list_entries(g_env.save_ctx, save, survey_count_cb, &bytes);
            (void)g_env.save->close_save(g_env.save_ctx, save);
        }

        daemoon_strbuf_init(&sb, line, sizeof(line));
        daemoon_strbuf_add(&sb, t->id);
        daemoon_strbuf_add(&sb, "\tsave=");
        daemoon_strbuf_add(&sb, or_ == DAEMOON_OK ? "yes" : daemoon_result_code(or_));
        daemoon_strbuf_add(&sb, "\tbytes=");
        daemoon_strbuf_add_uint(&sb, bytes);
        daemoon_strbuf_add(&sb, "\tsecure=");
        if (sr != DAEMOON_OK) {
            daemoon_strbuf_add(&sb, daemoon_result_code(sr));
        } else if (secure.exists) {
            static const char digits[] = "0123456789ABCDEF";
            char hex[17];
            int k;

            for (k = 0; k < 16; ++k) {
                hex[k] = digits[(secure.value >> ((15 - k) * 4)) & 0xf];
            }
            hex[16] = '\0';
            daemoon_strbuf_add(&sb, hex);
        } else {
            daemoon_strbuf_add(&sb, "none");
        }

        daemoon_strbuf_add(&sb, "\ticon=");
        daemoon_strbuf_add(&sb, (i < MAX_ICONS && g_icons[i].loaded) ? "yes" : "no");

        /* Why the name is what it is, and the raw Result when it is not a name.
         * A wire code says "not supported"; a Result says which module said it,
         * and this question has already cost two trips to a console. */
        {
            char real[DAEMOON_NAME_MAX];
            daemoon_result_t nr = daemoon_3ds_title_name(g_save_ctx.media, tid_of(t),
                                                         g_save_ctx.smdh_language, 0,
                                                         real, sizeof(real));

            daemoon_strbuf_add(&sb, "\tname=");
            daemoon_strbuf_add(&sb, nr == DAEMOON_OK ? "smdh" : daemoon_result_code(nr));
            {
                const daemoon_3ds_name_probe_t *pr = daemoon_3ds_last_name_probe();

                daemoon_strbuf_add(&sb, " lang=");
                daemoon_strbuf_add_int(&sb, pr->name_lang);
                if (pr->rejected_non_ascii) {
                    /* A name was there and could not be drawn. That is the font,
                     * not the lookup. */
                    daemoon_strbuf_add(&sb, " undrawable");
                }
            }
            if (nr != DAEMOON_OK) {
                /* Every route and what it said. One coarse word covered three
                 * different causes and cost four trips to a console; this is the
                 * shape of a diagnostic that ends the guessing. */
                const daemoon_3ds_name_probe_t *pr = daemoon_3ds_last_name_probe();

                daemoon_strbuf_add(&sb, " direct=");
                append_hex32(&sb, (unsigned long)pr->open_direct);
                daemoon_strbuf_add(&sb, " direct2=");
                append_hex32(&sb, (unsigned long)pr->open_direct2);
                daemoon_strbuf_add(&sb, " archive=");
                append_hex32(&sb, (unsigned long)pr->open_archive);
                daemoon_strbuf_add(&sb, " file=");
                append_hex32(&sb, (unsigned long)pr->open_file);
                daemoon_strbuf_add(&sb, " read=");
                append_hex32(&sb, (unsigned long)pr->read);
                daemoon_strbuf_add(&sb, " got=");
                daemoon_strbuf_add_uint(&sb, pr->read_bytes);
            }
            daemoon_strbuf_add(&sb, "\treal=");
            daemoon_strbuf_add(&sb, nr == DAEMOON_OK ? real : "-");
        }

        /* The name as the console knows it, in whatever script that is. This file
         * is read on a machine with fonts. */
        daemoon_strbuf_add(&sb, "\t");
        daemoon_strbuf_add(&sb, t->name);
        daemoon_strbuf_addc(&sb, '\n');

        (void)daemoon_stream_write(out, line, sb.len);
    }

    r = daemoon_stream_close(out);

    /* Everything above went to the hardware rather than to the cache, so the cache
     * is now the older of the two answers. Throwing it away also makes this the
     * button to press when a name or an icon looks wrong: the next list is read
     * from the console again. */
    daemoon_3ds_cache_forget(g_save_ctx.cache);

    report("survey", r);
}

/* The conformance suite writes, clears and commits a real save archive. It exists
 * to prove this backend behaves the way core is entitled to assume, and running
 * it on a title someone plays would be indefensible. */
static void action_self_test(void)
{
    daemoon_backend_under_test_t ut;
    daemoon_str_ref_t ask;
    char path[DAEMOON_PATH_MAX * 2];
    char body[256];
    int before;

    if (g_title_count == 0) {
        return;
    }

    (void)snprintf(body, sizeof(body),
                   "This DESTROYS the save of %s. Use a dummy title. A backup is "
                   "made first, but do not rely on it.",
                   g_titles[g_selected].name);
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_DANGER);

    memset(&ask, 0, sizeof(ask));
    ask.id = DAEMOON_STR_CONFIRM_RESTORE;
    ask.args[0] = g_titles[g_selected].name;
    ask.nargs = 1;
    if (!g_env.ui->confirm(g_env.ui_ctx, &ask)) {
        return;
    }

    report("backup", daemoon_sync_backup_local(&g_env, &g_archive, &g_titles[g_selected],
                                               path, sizeof(path)));

    memset(&ut, 0, sizeof(ut));
    ut.name = "3ds";
    ut.backend = &daemoon_3ds_save_backend;
    ut.ctx = &g_save_ctx;
    ut.title = &g_titles[g_selected];
    ut.other = NULL;
    ut.scratch = g_scratch;
    ut.scratch_len = sizeof(g_scratch);

    before = daemoon_test_failures;
    daemoon_backend_conformance(&ut);

    (void)snprintf(body, sizeof(body), "%d checks, %d failures. %s",
                   daemoon_test_checks, daemoon_test_failures - before,
                   daemoon_test_failures == before
                       ? "this backend behaves the way core assumes"
                       : daemoon_test_last_failure);
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body,
            daemoon_test_failures == before ? GFX_OK : GFX_DANGER);
}

/* Unattended, from a flag file, against this application's own save archive and
 * nothing else. See docs/3ds-workflow.md. */
static void run_autotest(void)
{
    daemoon_backend_under_test_t ut;
    daemoon_title_t self;
    daemoon_stream_t *out = NULL;
    char line[256];
    daemoon_strbuf_t sb;
    u64 program_id = 0;
    int failures;

    memset(&self, 0, sizeof(self));
    if (R_FAILED(APT_GetProgramID(&program_id))) {
        return;
    }
    daemoon_3ds_format_title_id(program_id, self.id, sizeof(self.id));
    (void)daemoon_strlcpy(self.name, sizeof(self.name), "DaeMoon itself");
    self.platform = DAEMOON_PLATFORM_3DS;
    self.save_type = DAEMOON_SAVE_SAVEDATA;
    self.size_hint = (unsigned long long)MEDIATYPE_SD;
    self.has_save = 1;

    {
        daemoon_save_t *probe = NULL;

        if (daemoon_3ds_save_backend.open_save(&g_save_ctx, &self, &probe) == DAEMOON_OK) {
            (void)daemoon_3ds_save_backend.close_save(&g_save_ctx, probe);
        } else if (daemoon_3ds_format_own_save(&self, 128) != DAEMOON_OK) {
            message(daemoon_str(DAEMOON_STR_APP_TITLE),
                    "No archive of its own: build with SAVEDATA_SIZE=128K.", GFX_WARN);
            return;
        }
    }

    memset(&ut, 0, sizeof(ut));
    ut.name = "3ds";
    ut.backend = &daemoon_3ds_save_backend;
    ut.ctx = &g_save_ctx;
    ut.title = &self;
    ut.other = NULL;
    ut.scratch = g_scratch;
    ut.scratch_len = sizeof(g_scratch);

    failures = daemoon_test_failures;
    daemoon_backend_conformance(&ut);
    failures = daemoon_test_failures - failures;

    /* The screen that has twice gone wrong on hardware, drawn unattended. It
     * asserts nothing - a fault here takes the process down, which is the report. */
    daemoon_3ds_trace("autotest/picker-draw", NULL);
    daemoon_3ds_pick_backup_render_check(&self, 8);
    daemoon_3ds_trace("autotest/picker-drawn", NULL);

    daemoon_strbuf_init(&sb, line, sizeof(line));
    daemoon_strbuf_add(&sb, "build=");
    daemoon_strbuf_add(&sb, DAEMOON_BUILD_STAMP);
    daemoon_strbuf_add(&sb, " target=");
    daemoon_strbuf_add(&sb, self.id);
    daemoon_strbuf_add(&sb, " checks=");
    daemoon_strbuf_add_uint(&sb, (unsigned long long)daemoon_test_checks);
    daemoon_strbuf_add(&sb, " failures=");
    daemoon_strbuf_add_uint(&sb, (unsigned long long)failures);
    if (failures > 0 && daemoon_test_last_failure[0] != '\0') {
        daemoon_strbuf_add(&sb, " first: ");
        daemoon_strbuf_add(&sb, daemoon_test_last_failure);
    }
    daemoon_strbuf_addc(&sb, '\n');

    if (g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/selftest.txt",
                       DAEMOON_OPEN_WRITE, &out) == DAEMOON_OK) {
        (void)daemoon_stream_write(out, line, sb.len);
        (void)daemoon_stream_close(out);
    }

    message(daemoon_str(DAEMOON_STR_APP_TITLE), line, failures == 0 ? GFX_OK : GFX_DANGER);
}

/* --------------------------------------------------------------------- main */

int main(void)
{
    daemoon_lang_t lang = DAEMOON_LANG_EN;

    /* Services first: the language decides which font to load. */
    if (R_FAILED(cfguInit())) {
        g_save_ctx.smdh_language = 1;
    } else {
        lang = select_language();
    }

    if (!daemoon_gfx_init(lang)) {
        return 1;
    }
    (void)amInit();

    /* A line the trail can be read from. Without it two runs of the same action
     * are indistinguishable in the file, and "did it get further this time" is the
     * question the file exists to answer. */
    daemoon_3ds_trace("app/start", DAEMOON_BUILD_STAMP);

    g_save_ctx.media = 1; /* MEDIATYPE_SD */
    g_save_ctx.only_with_saves = 1;
    /* The console's own font draws the languages this project ships, so a name no
     * longer has to be ASCII to be shown - unless the console has no font for it,
     * which is what docs/fonts.md is about. */
    g_save_ctx.ascii_names = !daemoon_gfx_has_language_font();

    daemoon_3ds_ui_init(&g_ui_ctx);
    g_archive.count = 0;

    (void)daemoon_3ds_config_load(DAEMOON_3DS_CONFIG_PATH, &g_config);
    g_net_ctx.ca_bundle = g_config.ca_bundle;

    g_nds_ctx.rom_dir = DAEMOON_3DS_NDS_ROM_DIR;
    g_nds_ctx.save_dir = DAEMOON_3DS_NDS_SAVE_DIR;

    /* The network is opened once. Doing it per request would mean a soc:U session
     * per sync, and that service does not enjoy being churned. */
    if (daemoon_3ds_config_can_sync(&g_config)) {
        (void)daemoon_3ds_net_init();
    }

    memset(&g_env, 0, sizeof(g_env));
    g_env.save = &daemoon_3ds_save_backend;
    g_env.fs = &daemoon_3ds_fs_backend;
    g_env.ui = &daemoon_3ds_ui_backend;
    g_env.net = &daemoon_3ds_net_backend;
    g_env.net_ctx = &g_net_ctx;
    g_env.save_ctx = &g_save_ctx;
    g_env.fs_ctx = NULL;
    g_env.ui_ctx = &g_ui_ctx;
    g_env.device_label = g_config.device_label;
    g_env.server_url = g_config.server_url;
    g_env.token = g_config.token[0] != '\0' ? g_config.token : NULL;
    g_env.work_dir = DAEMOON_3DS_WORK_DIR;
    g_env.scratch = g_scratch;
    g_env.scratch_len = sizeof(g_scratch);

    g_save_ctx.progress = loading_progress;

    /* Names and icons from the last launch, so the loading screen stops paying for
     * a decrypt per title every time. Failing to open it is not an error: without
     * one every lookup goes to the hardware, which is what happened before this
     * existed. */
    (void)g_env.fs->mkdir_p(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/cache");
    if (daemoon_3ds_cache_open(DAEMOON_3DS_CACHE_PATH, g_save_ctx.smdh_language,
                               &g_save_ctx.cache) != DAEMOON_OK) {
        g_save_ctx.cache = NULL;
    }

    if (reload_titles() != DAEMOON_OK) {
        message(daemoon_str(DAEMOON_STR_APP_TITLE), "Could not read the title list.",
                GFX_DANGER);
    }

    if (g_env.fs->exists(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/AUTOTEST")) {
        run_autotest();
        goto done;
    }

    while (aptMainLoop()) {
        touchPosition touch;
        int action = -1;
        u32 down;

        hidScanInput();
        down = hidKeysDown();
        hidTouchRead(&touch);

        if (down & KEY_START) {
            break;
        }
        if (down & (KEY_L | KEY_R)) {
            /* The other library. Reading it costs a moment, so it is a deliberate
             * press rather than something that happens while scrolling. */
            g_source_nds = !g_source_nds;
            g_selected = 0;
            g_scroll = 0;
            (void)reload_titles();
            continue;
        }
        if (g_title_count > 0) {
            if ((down & KEY_RIGHT) && g_selected + 1 < (int)g_title_count) {
                ++g_selected;
            }
            if ((down & KEY_LEFT) && g_selected > 0) {
                --g_selected;
            }
            if ((down & KEY_DOWN) && g_selected + GRID_COLS < (int)g_title_count) {
                g_selected += GRID_COLS;
            }
            if ((down & KEY_UP) && g_selected - GRID_COLS >= 0) {
                g_selected -= GRID_COLS;
            }
            if (down & KEY_A) {
                action = 0; /* back up */
            }
            if (down & KEY_Y) {
                action = 1; /* restore */
            }
            if (down & KEY_X) {
                action = 3; /* survey */
            }

            /* Keep the selection on screen. */
            if (g_selected / GRID_COLS < g_scroll) {
                g_scroll = g_selected / GRID_COLS;
            }
            if (g_selected / GRID_COLS >= g_scroll + GRID_ROWS) {
                g_scroll = g_selected / GRID_COLS - GRID_ROWS + 1;
            }
        }

        daemoon_gfx_frame_begin();
        draw_grid();
        draw_details(down, touch, &action);
        daemoon_gfx_frame_end();

        switch (action) {
        case 0: action_backup(); break;
        case 1: action_restore(); break;
        case 2: action_sync(); break;
        case 3: action_survey(); break;
        case 4: action_self_test(); (void)reload_titles(); break;
        default: break;
        }
    }

done:
    daemoon_3ds_trace("app/exit", NULL);
    free_icons();
    if (g_titles != NULL) {
        g_env.save->free_titles(g_env.save_ctx, g_titles, g_title_count);
    }
    (void)daemoon_3ds_cache_flush(g_save_ctx.cache, DAEMOON_3DS_CACHE_PATH);
    daemoon_3ds_cache_close(g_save_ctx.cache);
    daemoon_3ds_net_exit();
    amExit();
    cfguExit();
    daemoon_gfx_exit();
    return 0;
}
