/* 3DS entry point. Phase 1: local backup and restore, no server involved.
 *
 * Everything below the platform layer already exists and is tested on a desktop.
 * This file assembles a daemoon_env_t out of libctru and draws a grid of game
 * icons, because the question this application asks - which game's save do you
 * want to overwrite - is not one anybody should answer from a product code.
 *
 * The scratch buffer is static rather than malloc'd. The 3DS heap fragments
 * badly, this one lives for the whole run, and there is nothing to gain from
 * putting it on the heap and a slow loss of headroom to lose.
 */
#include "daemoon_3ds.h"
#include "gfx.h"
#include "icons.h"

#include "../../../tools/test/backend_conformance.h"
#include "../../../tools/test/test.h"

#include <daemoon/archive.h>
#include <daemoon/i18n.h>
#include <daemoon/sync.h>
#include <daemoon/util/strbuf.h>

#include <3ds.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Generated by the Makefile. Says which build this is, so "did the install take"
 * is answered by the screen rather than inferred from behaviour. */
#include "build_stamp.h"

/* Generated by bin2s from vendor/cacert/data/cacert.bin: the public root
 * certificates, in the binary. Without them https works only on a console whose
 * owner put a .pem on the card by hand, which is not something that can be
 * shipped to anybody. See net_curl.c. */
#include "cacert_bin.h"

#ifndef DAEMOON_BUILD_STAMP
#define DAEMOON_BUILD_STAMP "unknown"
#endif

/* Enough icons for a console with a lot of saves. Past this the grid still works
 * and the rest draw a placeholder, which is a better failure than refusing to
 * list them. */
#define MAX_ICONS 128

#define GRID_COLS   6
#define GRID_ROWS   3
#define GRID_CELL_W 64.0f
#define GRID_CELL_H 74.0f
#define GRID_X      ((GFX_TOP_W - GRID_COLS * GRID_CELL_W) / 2.0f)
#define GRID_Y      36.0f
#define GRID_PAGE   (GRID_COLS * GRID_ROWS)

/* libctru's weak default is 32 KiB, and `StackSize` in app.rsf does not override
 * it - the exheader value is not what the main thread ends up running on. Thirty
 * two kilobytes is not enough for this application:
 *
 *   - the first restore ever run on hardware died because one function wanted
 *     fifty of them for a single frame. That frame is gone, but the ceiling it hit
 *     was this one, and it sat about thirty kilobytes above the floor.
 *   - curl and mbedtls are linked in. A TLS handshake alone is tens of kilobytes
 *     of stack, and Phase 2 is where https starts mattering.
 *
 * A quarter of a megabyte of address space costs nothing on a console with tens of
 * megabytes of it, and the failure it prevents is a data abort with no message. */
unsigned int __stacksize__ = 256 * 1024;

static unsigned char g_scratch[64 * 1024];
static daemoon_archive_ctx_t g_archive;

/* The tally for a run over a whole library.
 *
 * A file scope structure rather than something threaded through batch.c, because
 * batch.c drives the loop and counting is not its business: it knows how many
 * titles there are and which one is in flight, and what each one turned into is
 * this file's answer to give. */
static struct {
    unsigned ok;
    unsigned skipped;
    unsigned failed;
    daemoon_sync_stats_t sync;
} g_batch;

static daemoon_3ds_save_ctx_t g_save_ctx;
static daemoon_3ds_nds_ctx_t  g_nds_ctx;
static daemoon_net_curl_ctx_t  g_net_ctx;
static daemoon_3ds_config_t   g_config;
/* Which library is on screen: the console's own titles, or the DS saves
 * nds-bootstrap keeps as plain files. Phase 2 syncs the second one first because
 * nothing about it can fail in a way unique to the platform. */
static int g_source_nds;
static daemoon_3ds_ui_ctx_t   g_ui_ctx;
static daemoon_env_t          g_env;

/* Both libraries, kept side by side.
 *
 * Switching used to free one list and enumerate the other from scratch, and on a
 * console with a real library that is a decrypt per title and several seconds -
 * every single press of L or R. The lists do not change while the application is
 * running unless it changes them, so they are read once and kept, along with where
 * the cursor was in each: coming back to a library and finding it where you left
 * it is most of what makes two libraries feel like one application. */
typedef struct {
    daemoon_title_t   *titles;
    size_t             count;
    daemoon_3ds_icon_t icons[MAX_ICONS];
    int                loaded;
    int                selected;
    int                scroll;
} library_t;

/* LIB_3DS and LIB_NDS are in daemoon_3ds.h: batch.c and autosync.c index by them
 * too, so they are part of the contract rather than local names. */

static library_t g_lib[2];

/* Shorthand for whichever library is on screen. */
#define CUR (&g_lib[g_source_nds ? LIB_NDS : LIB_3DS])

/* --------------------------------------------------------------------- i18n */

/* Which language the console itself is set to. Also the SMDH slot a title's name
 * is read from, which is why the two are worked out together. */
static daemoon_lang_t console_language(void)
{
    u8 code = 0;
    daemoon_lang_t lang = DAEMOON_LANG_EN;

    g_save_ctx.smdh_language = 1; /* English, until the console says otherwise */

    if (R_FAILED(CFGU_GetSystemLanguage(&code))) {
        return lang;
    }
    switch (code) {
    case CFG_LANGUAGE_JP: (void)daemoon_i18n_language_from_code("ja", &lang); break;
    case CFG_LANGUAGE_FR: (void)daemoon_i18n_language_from_code("fr", &lang); break;
    case CFG_LANGUAGE_DE: (void)daemoon_i18n_language_from_code("de", &lang); break;
    case CFG_LANGUAGE_ES: (void)daemoon_i18n_language_from_code("es", &lang); break;
    case CFG_LANGUAGE_ZH: (void)daemoon_i18n_language_from_code("zh-Hans", &lang); break;
    case CFG_LANGUAGE_KO: (void)daemoon_i18n_language_from_code("ko", &lang); break;
    case CFG_LANGUAGE_TW: (void)daemoon_i18n_language_from_code("zh-Hant", &lang); break;
    default:              lang = DAEMOON_LANG_EN; break;
    }

    /* The SMDH title index is the console's own language numbering, so a title's
     * name comes back in the language the HOME menu shows it in. This follows the
     * console even when the UI language does not: a game's name is the game's, not
     * a translation. */
    g_save_ctx.smdh_language = (int)code;
    return lang;
}

/* The UI language: the user's choice when they made one, the console's otherwise.
 *
 * Kept apart from the console's setting on purpose. Empty in the file is not the
 * same as "en" - a console later switched to Japanese should follow, and somebody
 * who picked English on a Japanese console should not be overruled by it. */
static daemoon_lang_t select_language(void)
{
    daemoon_lang_t lang = console_language();
    daemoon_lang_t chosen;

    if (g_config.language[0] != '\0' &&
        daemoon_i18n_language_from_code(g_config.language, &chosen) == DAEMOON_OK) {
        lang = chosen;
    }
    daemoon_i18n_set_language(lang);
    return lang;
}

/* -------------------------------------------------------------------- clock */

/* The console's clock, for manifest created_at.
 *
 * Never used to decide anything - the RTC is user settable and the rules say so
 * twice - but it is what a person recognises their own backups by, and without
 * this hook every backup in the picker was dated 1970-01-01, which is worse than
 * useless because it looks like a bug in the packaging.
 *
 * It is also a check on something else. mbedtls validates a certificate's dates
 * against the same C library clock, so a console reading 1970 cannot complete a
 * TLS handshake against any certificate issued this decade. If the dates in the
 * backup list are real, that half of https is going to work. */
static daemoon_result_t clock_iso8601(void *ctx, char *buf, size_t cap)
{
    time_t now = time(NULL);
    struct tm utc;

    (void)ctx;
    if (now <= 0 || gmtime_r(&now, &utc) == NULL) {
        return DAEMOON_ERR_UNSUPPORTED;
    }
    if (strftime(buf, cap, "%Y-%m-%dT%H:%M:%SZ", &utc) == 0) {
        return DAEMOON_ERR_BUFFER_TOO_SMALL;
    }
    return DAEMOON_OK;
}

/* ------------------------------------------------------------------- titles */

static unsigned long long tid_of(const daemoon_title_t *t)
{
    unsigned long long id = 0;

    (void)daemoon_3ds_parse_title_id(t->id, &id);
    return id;
}

static void free_library(library_t *lib)
{
    size_t i;

    for (i = 0; i < MAX_ICONS; ++i) {
        daemoon_3ds_icon_free(&lib->icons[i]);
    }
    if (lib->titles != NULL) {
        /* Freed by the backend that produced it, which is why the pairing below
         * is set before anything is released. */
        g_env.save = (lib == &g_lib[LIB_NDS]) ? &daemoon_3ds_nds_backend
                                              : &daemoon_3ds_save_backend;
        g_env.save_ctx = (lib == &g_lib[LIB_NDS]) ? (void *)&g_nds_ctx
                                                  : (void *)&g_save_ctx;
        g_env.save->free_titles(g_env.save_ctx, lib->titles, lib->count);
        lib->titles = NULL;
        lib->count = 0;
    }
    lib->loaded = 0;
}

/* One frame of the loading screen. Reading the list opens every save archive on
 * the console, so this runs for as long as that takes and a still screen would
 * look like a hang. */
static void draw_loading(daemoon_str_id_t what, unsigned done, unsigned total)
{
    char line[160];

    daemoon_gfx_frame_begin();
    daemoon_gfx_top();
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
    daemoon_gfx_text(12.0f, 6.0f, 0.55f, GFX_TEXT, daemoon_str(DAEMOON_STR_APP_TITLE));

    if (total > 0) {
        (void)snprintf(line, sizeof(line), "%s  %u/%u", daemoon_str(what), done, total);
    } else {
        (void)daemoon_strlcpy(line, sizeof(line), daemoon_str(what));
    }
    daemoon_gfx_text(12.0f, 100.0f, 0.5f, GFX_TEXT_DIM, line);

    if (total > 0) {
        float w = (GFX_TOP_W - 24.0f) * (float)done / (float)total;

        daemoon_gfx_rect(12.0f, 126.0f, GFX_TOP_W - 24.0f, 6.0f, GFX_PANEL);
        daemoon_gfx_rect(12.0f, 126.0f, w, 6.0f, GFX_ACCENT);
    }
    daemoon_gfx_frame_end();
}

static void loading_progress(void *user, unsigned done, unsigned total)
{
    (void)user;
    draw_loading(DAEMOON_STR_LOADING_TITLES, done, total);
}

/* Points the environment at one library's backend. The backend and its context
 * change together: getting that pair out of step would point save operations at
 * the wrong library entirely. */
static void select_backend(int nds)
{
    if (nds) {
        g_env.save = &daemoon_3ds_nds_backend;
        g_env.save_ctx = &g_nds_ctx;
    } else {
        g_env.save = &daemoon_3ds_save_backend;
        g_env.save_ctx = &g_save_ctx;
    }
}

static daemoon_result_t load_library(int nds)
{
    library_t *lib = &g_lib[nds ? LIB_NDS : LIB_3DS];
    daemoon_result_t r;
    size_t i;

    free_library(lib);
    select_backend(nds);

    r = g_env.save->list_titles(g_env.save_ctx, &lib->titles, &lib->count);
    if (r != DAEMOON_OK) {
        return r;
    }

    for (i = 0; i < lib->count && i < MAX_ICONS; ++i) {
        draw_loading(DAEMOON_STR_LOADING_ICONS, (unsigned)i, (unsigned)lib->count);
        if (nds) {
            /* Out of the ROM's banner, beside the save. A .sav next to a file
             * called "5684(Dsi0143) 포켓몬화이트 (K)" is exactly where a name
             * stops helping and a picture starts. */
            static unsigned char pixels[DAEMOON_3DS_ICON_BYTES];

            if (daemoon_3ds_nds_icon_read(g_nds_ctx.rom_dir, lib->titles[i].name,
                                          pixels) == DAEMOON_OK) {
                (void)daemoon_3ds_icon_upload(pixels, &lib->icons[i]);
            }
        } else {
            /* The same SMDH the name came from, already in the cache by now, so
             * this loop costs a texture upload rather than a decrypt per title. */
            (void)daemoon_3ds_icon_upload(
                daemoon_3ds_cache_icon(g_save_ctx.cache, g_save_ctx.media,
                                       tid_of(&lib->titles[i])),
                &lib->icons[i]);
        }
    }
    if (!nds) {
        /* Written back once the list is complete, not per title: a title that was
         * skipped this run is a title that is no longer installed, and that is
         * only known at the end. */
        (void)daemoon_3ds_cache_flush(g_save_ctx.cache, DAEMOON_3DS_CACHE_PATH);
    }
    if (lib->selected >= (int)lib->count) {
        lib->selected = lib->count > 0 ? (int)lib->count - 1 : 0;
    }
    lib->loaded = 1;
    return DAEMOON_OK;
}

/* Makes the library on screen the current one, reading it only if it has never
 * been read. This is what L and R call, and it is why they are now instant. */
static daemoon_result_t show_library(int nds)
{
    g_source_nds = nds;
    select_backend(nds);
    if (g_lib[nds ? LIB_NDS : LIB_3DS].loaded) {
        return DAEMOON_OK;
    }
    return load_library(nds);
}

/* Re-reads the library on screen. For after something changed it. */
static daemoon_result_t reload_titles(void)
{
    return load_library(g_source_nds);
}

/* ------------------------------------------------------------------ drawing */

static void draw_grid(void)
{
    char right[96];
    float w;
    int i;
    int first = CUR->scroll * GRID_COLS;

    daemoon_gfx_top();
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
    daemoon_gfx_text(10.0f, 5.0f, 0.55f, GFX_TEXT, daemoon_str(DAEMOON_STR_APP_TITLE));
    daemoon_gfx_text(96.0f, 9.0f, 0.4f, GFX_ACCENT,
                     daemoon_str(g_source_nds ? DAEMOON_STR_LIB_NDS
                                               : DAEMOON_STR_LIB_3DS));

    if (CUR->count > GRID_PAGE) {
        (void)snprintf(right, sizeof(right), "%d/%u   %s", CUR->selected + 1,
                       (unsigned)CUR->count, DAEMOON_BUILD_STAMP);
    } else {
        char counted[48];
        const char *args[1];
        char n[16];

        (void)snprintf(n, sizeof(n), "%u", (unsigned)CUR->count);
        args[0] = n;
        (void)daemoon_strf(counted, sizeof(counted), DAEMOON_STR_GRID_SAVES, args, 1);
        (void)snprintf(right, sizeof(right), "%s   %s", counted, DAEMOON_BUILD_STAMP);
    }
    w = daemoon_gfx_text_width(0.36f, right);
    daemoon_gfx_text(GFX_TOP_W - w - 8.0f, 10.0f, 0.36f, GFX_TEXT_DIM, right);

    for (i = 0; i < GRID_PAGE; ++i) {
        int index = first + i;
        float x = GRID_X + (float)(i % GRID_COLS) * GRID_CELL_W;
        float y = GRID_Y + (float)(i / GRID_COLS) * GRID_CELL_H;

        if (index >= (int)CUR->count) {
            break;
        }

        if (index == CUR->selected) {
            daemoon_gfx_rect(x, y - 2.0f, GRID_CELL_W - 4.0f, GRID_CELL_H - 6.0f,
                             GFX_ACCENT);
        }

        if (index < MAX_ICONS && CUR->icons[index].loaded) {
            C2D_DrawImageAt(CUR->icons[index].image, x + 6.0f, y + 2.0f, 0.0f, NULL,
                            1.0f, 1.0f);
        } else {
            /* No icon is normal for some titles. A flat tile keeps the grid
             * aligned, which a gap would not. */
            daemoon_gfx_rect(x + 6.0f, y + 2.0f, 48.0f, 48.0f, GFX_PANEL);
        }

        daemoon_gfx_text_fit(x, y + 54.0f, GRID_CELL_W - 4.0f, 0.34f,
                             index == CUR->selected ? GFX_TEXT : GFX_TEXT_DIM,
                             CUR->titles[index].name);
    }

    if (CUR->count == 0) {
        (void)daemoon_gfx_text_wrapped(12.0f, 100.0f, GFX_TOP_W - 24.0f, 0.5f,
                                       GFX_TEXT_DIM,
                                       daemoon_str(DAEMOON_STR_GRID_EMPTY));
    }
}

static void draw_details(u32 down, touchPosition touch, int *out_action)
{
    static const daemoon_str_id_t labels[] = {
        DAEMOON_STR_MENU_BACKUP, DAEMOON_STR_MENU_RESTORE,
        DAEMOON_STR_MENU_SYNC,   DAEMOON_STR_MENU_BATCH,
        DAEMOON_STR_MENU_SETTINGS
    };
    const daemoon_title_t *t = NULL;
    char line[160];
    float y = 6.0f;
    int touched = (down & KEY_TOUCH) != 0;
    size_t i;

    if (CUR->count > 0) {
        t = &CUR->titles[CUR->selected];
    }

    daemoon_gfx_bottom();

    if (t != NULL) {
        daemoon_gfx_text_fit(4.0f, y, GFX_BOTTOM_W - 8.0f, 0.45f, GFX_TEXT, t->name);
        y += 17.0f;
        daemoon_gfx_text(8.0f, y, 0.34f, GFX_TEXT_DIM, t->id);
        y += 13.0f;

        /* The warning that matters before a restore, on screen before anything is
         * chosen rather than after. */
        {
            daemoon_3ds_secure_value_t secure;

            if (daemoon_3ds_read_secure_value(t, &secure) == DAEMOON_OK && secure.exists) {
                char hex[24];
                const char *args[1];

                (void)snprintf(hex, sizeof(hex), "%016llX",
                               (unsigned long long)secure.value);
                args[0] = hex;
                (void)daemoon_strf(line, sizeof(line), DAEMOON_STR_TITLE_SECURE_VALUE,
                                   args, 1);
                daemoon_gfx_text(8.0f, y, 0.32f, GFX_WARN, line);
            } else {
                daemoon_gfx_text(8.0f, y, 0.32f, GFX_TEXT_DIM,
                                 daemoon_str(DAEMOON_STR_TITLE_NO_SECURE_VALUE));
            }
            y += 14.0f;
        }
    } else {
        daemoon_gfx_text(8.0f, y, 0.45f, GFX_TEXT_DIM,
                         daemoon_str(DAEMOON_STR_GRID_NOTHING_SELECTED));
        y += 44.0f;
    }

    /* Six buttons and 240 pixels. The heights are what they are so the last one
     * and the hint line both fit; a button that is off the bottom of the screen is
     * a feature nobody can reach. */
    for (i = 0; i < sizeof(labels) / sizeof(labels[0]); ++i) {
        if (daemoon_gfx_button(8.0f, y, GFX_BOTTOM_W - 16.0f, 27.0f,
                               daemoon_str(labels[i]), 0,
                               down, touch.px, touch.py, touched)) {
            *out_action = (int)i;
        }
        y += 29.0f;
    }

    daemoon_gfx_text(8.0f, GFX_SCREEN_H - 16.0f, 0.34f, GFX_TEXT_DIM,
                     daemoon_str(DAEMOON_STR_HINT_GRID));
}

/* ------------------------------------------------------------------ actions */

static void message(const char *title, const char *body, u32 accent)
{
    /* main.c has its own dialog loop, so it was the one screen the trail could not
     * see - two syncs in a row ended at "uploading" in the file with no sign of the
     * result the user was looking at. */
    daemoon_3ds_trace("ui/message", body);

    while (aptMainLoop()) {
        u32 down;

        hidScanInput();
        down = hidKeysDown();

        daemoon_gfx_frame_begin();
        daemoon_gfx_top();
        daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, accent);
        daemoon_gfx_text(12.0f, 6.0f, 0.6f, GFX_TEXT, title);
        (void)daemoon_gfx_text_wrapped(12.0f, 56.0f, GFX_TOP_W - 24.0f, 0.5f, GFX_TEXT,
                                       body);
        daemoon_gfx_bottom();
        daemoon_gfx_text(12.0f, 100.0f, 0.5f, GFX_TEXT_DIM,
                         daemoon_str(DAEMOON_STR_HINT_CONTINUE));
        daemoon_gfx_frame_end();

        if (down & (KEY_A | KEY_B)) {
            return;
        }
    }
}

/* One place where an operation's outcome becomes a sentence.
 *
 * The wire code goes on the end in brackets. It is an identifier rather than
 * prose - the same kind of thing as a title id - and it is what a photograph in a
 * bug report has to carry, because "동기화 실패" narrows nothing on its own. */
static void report(daemoon_str_id_t op, daemoon_result_t r)
{
    char body[320];
    const char *args[2];

    if (r == DAEMOON_OK) {
        args[0] = daemoon_str(op);
        (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_REPORT_OK, args, 1);
        message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_OK);
        return;
    }

    args[0] = daemoon_str(op);
    args[1] = daemoon_str(daemoon_result_str_id(r));
    (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_REPORT_FAILED, args, 2);
    {
        size_t len = strlen(body);

        (void)snprintf(body + len, sizeof(body) - len, "  [%s]", daemoon_result_code(r));
    }
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_DANGER);
}

static void action_backup(void)
{
    char path[DAEMOON_PATH_MAX * 2];
    daemoon_str_ref_t ask;

    if (CUR->count == 0) {
        return;
    }

    /* Backing up writes only to the SD card and cannot lose a save, so this is not
     * one of the confirmations the rules demand. It is here because the button that
     * makes a backup and the button that overwrites a save are next to each other
     * on a console with no pointer, and being told which title is about to be read
     * is worth one press. */
    daemoon_3ds_trace("backup/begin", CUR->titles[CUR->selected].id);
    memset(&ask, 0, sizeof(ask));
    ask.id = DAEMOON_STR_CONFIRM_BACKUP;
    ask.args[0] = CUR->titles[CUR->selected].name;
    ask.nargs = 1;
    if (!g_env.ui->confirm(g_env.ui_ctx, &ask)) {
        return;
    }

    {
        daemoon_result_t r = daemoon_sync_backup_local(&g_env, &g_archive,
                                                       &CUR->titles[CUR->selected], path,
                                                       sizeof(path));

        daemoon_3ds_trace("backup/done", daemoon_result_code(r));
        report(DAEMOON_STR_OP_BACKUP, r);
    }
}

/* The digest of what is on the console right now, so the backup list can say which
 * of its entries would change nothing. Best effort: a title with no archive yet has
 * no digest, and that is not a reason to refuse to show the list. */
static void current_digest(const daemoon_title_t *title, char *out, size_t cap)
{
    daemoon_save_t *save = NULL;
    unsigned long long size = 0;

    out[0] = '\0';
    if (cap < DAEMOON_SHA256_HEX) {
        return;
    }
    if (g_env.save->open_save(g_env.save_ctx, title, &save) != DAEMOON_OK) {
        return;
    }
    if (daemoon_archive_hash_save(&g_env, &g_archive, save, out, &size) != DAEMOON_OK) {
        out[0] = '\0';
    }
    (void)g_env.save->close_save(g_env.save_ctx, save);
}

static void action_restore(void)
{
    char dir[DAEMOON_PATH_MAX * 2];
    char pick[DAEMOON_PATH_MAX * 2];
    char digest[DAEMOON_SHA256_HEX];
    daemoon_strbuf_t sb;
    daemoon_result_t pr;

    if (CUR->count == 0) {
        return;
    }

    daemoon_strbuf_init(&sb, dir, sizeof(dir));
    daemoon_strbuf_add(&sb, DAEMOON_3DS_WORK_DIR);
    daemoon_strbuf_add(&sb, "/backups");
    if (daemoon_strbuf_result(&sb) != DAEMOON_OK) {
        return;
    }

    daemoon_3ds_trace("restore/begin", CUR->titles[CUR->selected].id);
    draw_loading(DAEMOON_STR_LOADING_BACKUPS, 0, 0);
    current_digest(&CUR->titles[CUR->selected], digest, sizeof(digest));
    daemoon_3ds_trace("restore/digest", digest[0] != '\0' ? digest : "-");

    pr = daemoon_3ds_pick_backup(&g_env, dir, &CUR->titles[CUR->selected], digest, pick,
                                 sizeof(pick));
    daemoon_3ds_trace("restore/picked", daemoon_result_code(pr));
    if (pr == DAEMOON_ERR_NOT_FOUND) {
        char none[256];
        const char *args[1];

        args[0] = CUR->titles[CUR->selected].name;
        (void)daemoon_strf(none, sizeof(none), DAEMOON_STR_BACKUP_NONE, args, 1);
        message(daemoon_str(DAEMOON_STR_APP_TITLE), none, GFX_PANEL);
        return;
    }
    if (pr != DAEMOON_OK) {
        return;
    }

    /* The secure value is core's business now.
     *
     * It used to be arranged here: read the console's current value before the
     * restore, put it back after. That preserved the *console's* value, which is not
     * the same as the one the save being restored was bound to - and when they differ
     * the game treats the restored save as corrupt and deletes it.
     *
     * So it is packed with the save and written back from the package, which is a
     * property of the backup rather than a step a caller has to remember. A package
     * written before that carries none, and then nothing is written and the console
     * keeps what it has, exactly as this did.
     */
    {
        daemoon_result_t r;

        daemoon_3ds_trace("restore/core", pick);
        r = daemoon_sync_restore_package(&g_env, &g_archive, &CUR->titles[CUR->selected], pick);
        daemoon_3ds_trace("restore/core-done", daemoon_result_code(r));
        report(DAEMOON_STR_OP_RESTORE, r);
    }
}

static void append_hex32(daemoon_strbuf_t *sb, unsigned long value)
{
    static const char digits[] = "0123456789ABCDEF";
    char hex[11];
    int k;

    hex[0] = '0';
    hex[1] = 'x';
    for (k = 0; k < 8; ++k) {
        hex[2 + k] = digits[(value >> ((7 - k) * 4)) & 0xf];
    }
    hex[10] = '\0';
    daemoon_strbuf_add(sb, hex);
}

/* Phase 2: the whole sync path, which has been running on a desktop since Phase
 * 0. Nothing about it is new here except the network underneath it. */
static void action_sync(void)
{
    daemoon_sync_stats_t stats;
    char body[256];
    daemoon_result_t r;

    if (CUR->count == 0) {
        return;
    }
    if (!daemoon_3ds_config_can_sync(&g_config)) {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_ERR_NO_SERVER), GFX_WARN);
        return;
    }

    memset(&stats, 0, sizeof(stats));
    daemoon_3ds_trace("sync/begin", CUR->titles[CUR->selected].id);
    r = daemoon_sync_title(&g_env, &g_archive, &CUR->titles[CUR->selected], &stats);
    daemoon_3ds_trace("sync/done", daemoon_result_code(r));

    if (r != DAEMOON_OK) {
        report(DAEMOON_STR_OP_SYNC, r);
        return;
    }
    {
        char counts[4][12];
        const char *args[4];
        size_t i;
        const unsigned n[4] = { stats.uploaded, stats.downloaded, stats.skipped,
                                stats.conflicts };

        for (i = 0; i < 4; ++i) {
            (void)snprintf(counts[i], sizeof(counts[i]), "%u", n[i]);
            args[i] = counts[i];
        }
        (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_SYNC_RESULT, args, 4);
    }
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body, GFX_OK);
}

static int survey_count_cb(void *user, const char *path, unsigned long long size)
{
    unsigned long long *total = (unsigned long long *)user;

    (void)path;
    *total += size;
    return 0;
}

/* Reads every title once and writes what it found to the SD card.
 *
 * Read only: it opens save archives, counts what is in them, and asks for each
 * title's secure value. Nothing is written to any archive. The two open questions
 * of this phase are answered by data about a whole console, and reading that off a
 * screen one title at a time is how a survey turns into three titles and a guess.
 */
/* Typing a URL and a token on a console.
 *
 * The rules call a software keyboard painful and they are right - which is why
 * Phase 4 is QR and device code pairing, and why this exists anyway: until then
 * the only way to point a console at a server is to take the card out and edit a
 * file, and taking the card out is the thing this whole workflow was built to
 * stop doing.
 *
 * Written straight back to config.txt, so what is typed here and what is pushed
 * over FTP are the same file in the same format.
 */
static int edit_field(daemoon_str_id_t label, const char *hint, char *value, size_t cap)
{
    SwkbdState kbd;
    char buf[512];
    SwkbdButton pressed;

    if (cap > sizeof(buf)) {
        cap = sizeof(buf);
    }
    swkbdInit(&kbd, SWKBD_TYPE_NORMAL, 2, (int)cap - 1);
    swkbdSetInitialText(&kbd, value);
    swkbdSetHintText(&kbd, hint);
    swkbdSetButton(&kbd, SWKBD_BUTTON_LEFT, daemoon_str(DAEMOON_STR_BTN_CANCEL), false);
    swkbdSetButton(&kbd, SWKBD_BUTTON_RIGHT, daemoon_str(DAEMOON_STR_BTN_OK), true);
    /* Blank is a legitimate answer for the token - it is how somebody unpairs a
     * console - so validation only rejects what cannot be stored. */
    swkbdSetValidation(&kbd, SWKBD_ANYTHING, 0, 0);

    daemoon_3ds_trace("settings/keyboard", daemoon_str(label));
    pressed = swkbdInputText(&kbd, buf, cap);
    if (pressed != SWKBD_BUTTON_CONFIRM) {
        return 0;
    }
    (void)daemoon_strlcpy(value, cap, buf);
    return 1;
}

#define SETTINGS_ROWS 9

static const daemoon_str_id_t k_settings_labels[SETTINGS_ROWS] = {
    DAEMOON_STR_SETTINGS_SERVER, DAEMOON_STR_SETTINGS_TOKEN,
    DAEMOON_STR_SETTINGS_LABEL, DAEMOON_STR_SETTINGS_LANGUAGE,
    DAEMOON_STR_PAIR_SCAN, DAEMOON_STR_PAIR_TITLE,
    DAEMOON_STR_SETTINGS_WELCOME, DAEMOON_STR_SETTINGS_AUTOSYNC,
    DAEMOON_STR_SETTINGS_SURVEY
};

/* What the language row shows: the chosen language, or the console's with a note
 * that it is being followed. The distinction is the point of the setting. */
static void language_value(char *out, size_t cap)
{
    daemoon_lang_t chosen;

    if (g_config.language[0] != '\0' &&
        daemoon_i18n_language_from_code(g_config.language, &chosen) == DAEMOON_OK) {
        (void)daemoon_strlcpy(out, cap, daemoon_lang_name(chosen));
        return;
    }
    {
        const char *args[1];

        args[0] = daemoon_lang_name(console_language());
        (void)daemoon_strf(out, cap, DAEMOON_STR_SETTINGS_LANGUAGE_AUTO, args, 1);
    }
}

static void draw_settings(int selected)
{
    const daemoon_str_id_t *labels = k_settings_labels;
    const char *values[SETTINGS_ROWS];
    char masked[32];
    char language[64];
    float y;
    size_t i;

    /* The token is a credential and this screen gets photographed for bug
     * reports. Enough of it to tell two apart, and no more - plus where it is
     * kept, because "on the card" is a property this application claims and should
     * not quietly stop having. */
    if (g_config.token[0] == '\0') {
        (void)daemoon_strlcpy(masked, sizeof(masked), daemoon_str(DAEMOON_STR_SETTINGS_UNSET));
    } else {
        (void)snprintf(masked, sizeof(masked), "%.6s...  (%s)", g_config.token,
                       g_config.token_on_card ? "SD card" : "save archive");
    }
    language_value(language, sizeof(language));
    values[0] = g_config.server_url[0] != '\0' ? g_config.server_url
                                               : daemoon_str(DAEMOON_STR_SETTINGS_UNSET);
    values[1] = masked;
    values[2] = g_config.device_label;
    values[3] = language;
    /* The two pairing rows are actions rather than settings, so their value line
     * says what they are for rather than repeating the label. */
    values[4] = daemoon_str(DAEMOON_STR_PAIR_AIM);
    values[5] = daemoon_str(DAEMOON_STR_PAIR_ENTER_CODE);
    values[6] = daemoon_str(DAEMOON_STR_WELCOME_CONNECT_HOW);
    values[7] = daemoon_str(g_config.autosync ? DAEMOON_STR_SETTINGS_ON
                                              : DAEMOON_STR_SETTINGS_OFF);
    values[8] = daemoon_str(DAEMOON_STR_SETTINGS_SURVEY_HINT);

    daemoon_gfx_top();
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
    daemoon_gfx_text(12.0f, 6.0f, 0.55f, GFX_TEXT, daemoon_str(DAEMOON_STR_SETTINGS_TITLE));

    /* Only the selected row is spelled out on the top screen. Six rows of label
     * and value do not fit, and the one under the cursor is the one being read. */
    daemoon_gfx_text(14.0f, 52.0f, 0.45f, GFX_TEXT_DIM,
                     daemoon_str(labels[selected]));
    (void)daemoon_gfx_text_wrapped(14.0f, 76.0f, GFX_TOP_W - 28.0f, 0.5f, GFX_TEXT,
                                   values[selected]);
    y = 0.0f;
    daemoon_gfx_text(14.0f, GFX_SCREEN_H - 22.0f, 0.34f, GFX_TEXT_DIM,
                     DAEMOON_3DS_CONFIG_PATH);

    daemoon_gfx_bottom();
    /* The spacing comes from the row count rather than the row count having to fit
     * the spacing.
     *
     * Twice now a row has been added and drawn below 240: once at 214..244 and again
     * at 223..250, and both times it was a settings entry nobody could see or reach.
     * A screen is 240 pixels whatever the list is, so divide by the list. */
    {
        const float top = 6.0f;
        const float step = (GFX_SCREEN_H - top - 6.0f) / (float)SETTINGS_ROWS;
        const float height = step - 4.0f;

        y = top;
        for (i = 0; i < SETTINGS_ROWS; ++i) {
            daemoon_gfx_rect(8.0f, y, GFX_BOTTOM_W - 16.0f, height,
                             (int)i == selected ? GFX_ACCENT : GFX_PANEL);
            daemoon_gfx_text_fit(16.0f, y + (height - 14.0f) / 2.0f, GFX_BOTTOM_W - 32.0f,
                                 0.42f, GFX_TEXT, daemoon_str(labels[i]));
            y += step;
        }
    }
    daemoon_gfx_text(10.0f, GFX_SCREEN_H - 18.0f, 0.34f, GFX_TEXT_DIM,
                     daemoon_str(DAEMOON_STR_HINT_EDIT));
}

/* Picking a language, as a list.
 *
 * This stepped through the languages one press at a time until a console proved
 * why that is wrong: the font check refuses a language the console cannot draw,
 * and a refused entry in a cycle is a wall. Japanese was reachable, Chinese was
 * refused, and everything after Chinese was unreachable - including the way back.
 *
 * A list has no order to be trapped in. Every language is on screen at once, each
 * written in its own script, and the ones this console has no font for are shown
 * greyed rather than hidden: "my language is not here" is a worse answer than "my
 * language is here and this console cannot draw it".
 *
 * Those rows cannot be written in their own script either - that is what being
 * undrawable means - so they fall back to their language code, which is ASCII and
 * always renders.
 */
#define LANG_ROWS 9

static const daemoon_lang_t k_lang_order[LANG_ROWS - 1] = {
    DAEMOON_LANG_EN, DAEMOON_LANG_KO, DAEMOON_LANG_JA, DAEMOON_LANG_ZH_HANS,
    DAEMOON_LANG_ZH_HANT, DAEMOON_LANG_ES, DAEMOON_LANG_FR, DAEMOON_LANG_DE
};

/* Row 0 follows the console; rows 1.. are k_lang_order. */
static void language_row_text(size_t row, char *out, size_t cap, int *drawable)
{
    if (row == 0) {
        const char *args[1];

        args[0] = daemoon_lang_name(console_language());
        (void)daemoon_strf(out, cap, DAEMOON_STR_SETTINGS_LANGUAGE_AUTO, args, 1);
        *drawable = 1;
        return;
    }
    {
        daemoon_lang_t lang = k_lang_order[row - 1];

        *drawable = daemoon_gfx_language_drawable(lang);
        (void)daemoon_strlcpy(out, cap,
                              *drawable ? daemoon_lang_name(lang)
                                        : daemoon_lang_code(lang));
    }
}

static size_t language_current_row(void)
{
    daemoon_lang_t chosen;
    size_t i;

    if (g_config.language[0] == '\0' ||
        daemoon_i18n_language_from_code(g_config.language, &chosen) != DAEMOON_OK) {
        return 0;
    }
    for (i = 0; i < LANG_ROWS - 1; ++i) {
        if (k_lang_order[i] == chosen) {
            return i + 1;
        }
    }
    return 0;
}

/* Returns 1 when the setting changed. */
static int choose_language(void)
{
    size_t selected = language_current_row();
    int changed = 0;

    daemoon_3ds_trace("settings/language-open", NULL);

    while (aptMainLoop()) {
        u32 down;
        size_t i;
        float y;

        hidScanInput();
        down = hidKeysDown();

        daemoon_gfx_frame_begin();

        daemoon_gfx_top();
        daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 28.0f, GFX_ACCENT_D);
        daemoon_gfx_text(12.0f, 6.0f, 0.55f, GFX_TEXT,
                         daemoon_str(DAEMOON_STR_SETTINGS_LANGUAGE));
        {
            char text[96];
            int drawable = 1;

            language_row_text(selected, text, sizeof(text), &drawable);
            daemoon_gfx_text_fit(14.0f, 60.0f, GFX_TOP_W - 28.0f, 0.7f,
                                 drawable ? GFX_TEXT : GFX_TEXT_DIM, text);
            if (!drawable) {
                char body[320];
                const char *args[1];

                args[0] = daemoon_lang_code(k_lang_order[selected - 1]);
                (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_SETTINGS_NO_FONT,
                                   args, 1);
                (void)daemoon_gfx_text_wrapped(14.0f, 110.0f, GFX_TOP_W - 28.0f, 0.38f,
                                               GFX_WARN, body);
            }
        }

        daemoon_gfx_bottom();
        y = 6.0f;
        for (i = 0; i < LANG_ROWS; ++i) {
            char text[96];
            int drawable = 1;

            language_row_text(i, text, sizeof(text), &drawable);
            daemoon_gfx_rect(6.0f, y, GFX_BOTTOM_W - 12.0f, 22.0f,
                             i == selected ? GFX_ACCENT : GFX_PANEL);
            daemoon_gfx_text_fit(12.0f, y + 3.0f, GFX_BOTTOM_W - 24.0f, 0.4f,
                                 drawable ? GFX_TEXT : GFX_TEXT_DIM, text);
            y += 24.0f;
        }
        daemoon_gfx_text(8.0f, GFX_SCREEN_H - 16.0f, 0.32f, GFX_TEXT_DIM,
                         daemoon_str(DAEMOON_STR_HINT_CHOOSE));

        daemoon_gfx_frame_end();

        if (down & KEY_B) {
            break;
        }
        if (down & KEY_A) {
            if (selected == 0) {
                daemoon_lang_t sys = console_language();

                g_config.language[0] = '\0';
                (void)daemoon_gfx_set_language(sys);
                daemoon_i18n_set_language(sys);
                changed = 1;
                break;
            }
            {
                daemoon_lang_t lang = k_lang_order[selected - 1];

                /* Refused rather than accepted: every screen after this one would
                 * be blank, including this one. The reason is already on the top
                 * screen, so the press simply does nothing. */
                if (!daemoon_gfx_language_drawable(lang)) {
                    continue;
                }
                /* The font moves with the language. Changing one without the
                 * other is how a Korean console ended up drawing Hangul as
                 * replacement characters. */
                if (!daemoon_gfx_set_language(lang)) {
                    continue;
                }
                (void)daemoon_strlcpy(g_config.language, sizeof(g_config.language),
                                      daemoon_lang_code(lang));
                daemoon_i18n_set_language(lang);
                changed = 1;
                break;
            }
        }
        if ((down & KEY_UP) && selected > 0) {
            --selected;
        }
        if ((down & KEY_DOWN) && selected + 1 < LANG_ROWS) {
            ++selected;
        }
    }

    return changed;
}

/* What both pairing paths end at.
 *
 * A typed code and a scanned one differ only in where the six digits and the
 * server address came from; from here they are the same exchange. The token is
 * written to the same file the FTP push writes, so a console paired from the
 * screen and one paired from a desktop are in identical states afterwards.
 */
static int finish_pairing(const char *grant, const char *code)
{
    char token[DAEMOON_TOKEN_MAX];
    char device_id[DAEMOON_DEVICE_ID_MAX];
    daemoon_result_t r;

    if (g_config.server_url[0] == '\0') {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_PAIR_NO_SERVER), GFX_WARN);
        return 0;
    }

    /* The network may not have been opened at startup: a console with no server
     * configured has no reason to hold a soc:U session, and this is the moment it
     * gets one. */
    if (daemoon_net_curl_init() != DAEMOON_OK) {
        report(DAEMOON_STR_OP_SYNC, DAEMOON_ERR_NETWORK_ERROR);
        return 0;
    }

    /* Whether this console is claiming to be one the server already knows. It goes
     * out as an ordinary bearer header, and the server rotates that device instead
     * of minting another - so if a console keeps appearing twice, this line is the
     * first thing to look at. */
    daemoon_3ds_trace("pair/bearer",
                      (g_env.token != NULL && g_env.token[0] != '\0') ? "yes" : "no");
    daemoon_3ds_trace("pair/exchange", grant);
    draw_loading(DAEMOON_STR_PAIR_TITLE, 0, 0);

    r = daemoon_api_pair(&g_env, grant, code, g_config.device_label,
                         DAEMOON_PLATFORM_3DS, token, sizeof(token),
                         device_id, sizeof(device_id));
    daemoon_3ds_trace("pair/result", daemoon_result_code(r));
    if (r != DAEMOON_OK) {
        report(DAEMOON_STR_PAIR_TITLE, r);
        return 0;
    }
    /* The same id back means the server rotated this console's device. A different
     * one means it made another, and the panel will show two. */
    daemoon_3ds_trace("pair/device",
                      (g_config.device_id[0] != '\0' &&
                       strcmp(g_config.device_id, device_id) == 0)
                          ? "same"
                          : "new");

    /* The token this console was already holding went out with the request, as an
     * ordinary bearer header, and that is deliberate: it is how the server knows
     * this is the same console pairing again rather than a new one. It rotates the
     * existing device in place, so one console stays one row and the old credential
     * stops working the moment the new one is issued.
     *
     * A console with no token, or one the server does not know, becomes a new
     * device - which is right for a fresh SD card. */
    (void)daemoon_strlcpy(g_config.token, sizeof(g_config.token), token);
    (void)daemoon_strlcpy(g_config.device_id, sizeof(g_config.device_id), device_id);
    g_env.token = g_config.token;

    /* The archive first, because that is where the credential belongs. The file
     * only carries the address and the label now. */
    r = daemoon_3ds_secret_save(&g_env, g_config.token, g_config.device_id);
    daemoon_3ds_trace("secret/saved", daemoon_result_code(r));
    /* Where the token is kept must not decide whether a console can pair. If the
     * archive will not take it, it goes on the card as it always did, and the
     * console says which happened rather than quietly giving up a property it
     * claims to have. */
    g_config.token_on_card = (r != DAEMOON_OK);

    r = daemoon_3ds_config_save(DAEMOON_3DS_CONFIG_PATH, &g_config);
    if (r != DAEMOON_OK) {
        /* The token is live but only in memory. Saying so beats a console that
         * syncs today and is a stranger tomorrow. */
        report(DAEMOON_STR_PAIR_TITLE, r);
        return 1;
    }

    message(daemoon_str(DAEMOON_STR_APP_TITLE),
            daemoon_str(DAEMOON_STR_PAIR_DONE), GFX_OK);
    return 1;
}

static int pair_with_typed_code(void)
{
    char code[DAEMOON_PAIR_CODE_MAX];

    code[0] = '\0';
    if (!edit_field(DAEMOON_STR_PAIR_TITLE, "000000", code, sizeof(code))) {
        return 0;
    }
    if (code[0] == '\0') {
        return 0;
    }
    return finish_pairing("device_code", code);
}

/* Drawn once per camera frame while the scan runs. Returning 0 stops it, which is
 * the only way out of a screen that is otherwise waiting on hardware. */
static int scan_frame(void *user)
{
    const C2D_Image *preview;
    const daemoon_3ds_qr_stats_t *st;
    char line[128];
    u32 down;

    (void)user;
    if (!aptMainLoop()) {
        return 0;
    }
    hidScanInput();
    down = hidKeysDown();

    preview = daemoon_3ds_qr_preview();
    st = daemoon_3ds_qr_last_stats();

    daemoon_gfx_frame_begin();
    daemoon_gfx_top();
    if (preview != NULL && st->frames > 0) {
        /* What the camera sees, filling the screen. Without this a scan cannot be
         * aimed, and a scan that cannot be aimed does not work - which is exactly
         * how the first version of this failed. */
        C2D_DrawImageAt(*preview, 0.0f, 0.0f, 0.0f, NULL,
                        GFX_TOP_W / (float)DAEMOON_3DS_CAM_W,
                        GFX_SCREEN_H / (float)DAEMOON_3DS_CAM_H);
    } else {
        daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, GFX_SCREEN_H, GFX_PANEL);
    }
    daemoon_gfx_rect(0.0f, 0.0f, GFX_TOP_W, 22.0f, GFX_ACCENT_D);
    daemoon_gfx_text(10.0f, 4.0f, 0.45f, GFX_TEXT, daemoon_str(DAEMOON_STR_PAIR_SCAN));

    daemoon_gfx_bottom();
    (void)daemoon_gfx_text_wrapped(10.0f, 14.0f, GFX_BOTTOM_W - 20.0f, 0.42f, GFX_TEXT,
                                   daemoon_str(DAEMOON_STR_PAIR_AIM));
    /* The three numbers that tell the failures apart, on screen rather than only in
     * a file: no frames is a camera that never started, a mean near zero is a lens
     * covered, and codes seen without a decode is a code too far or out of focus. */
    (void)snprintf(line, sizeof(line),
                   "frames %u   light %u   codes %d   %s   %s",
                   st->frames, st->mean_luma, st->codes_seen,
                   st->camera ? "inner" : "outer",
                   daemoon_3ds_cam_layout_name(st->layout));
    daemoon_gfx_text(10.0f, GFX_SCREEN_H - 58.0f, 0.38f, GFX_TEXT_DIM, line);
    /* Where the time goes. Four candidates and no way to tell them apart by
     * reading, so the console reports which one is expensive. */
    (void)snprintf(line, sizeof(line),
                   "ms  cap %u  tile %u  draw %u  dec %u   buferr %u",
                   st->ms_capture, st->ms_tile, st->ms_draw, st->ms_decode,
                   st->buffer_errors);
    daemoon_gfx_text(10.0f, GFX_SCREEN_H - 40.0f, 0.38f, GFX_TEXT_DIM, line);
    daemoon_gfx_text(10.0f, GFX_SCREEN_H - 20.0f, 0.36f, GFX_TEXT_DIM,
                     daemoon_str(DAEMOON_STR_PAIR_SWITCH));
    daemoon_gfx_frame_end();

    if (down & KEY_B) {
        return 0;
    }
    if (down & (KEY_L | KEY_R)) {
        return 2;
    }
    if (down & (KEY_X | KEY_Y)) {
        return 3;
    }
    return 1;
}

static int pair_by_scanning(void)
{
    char payload[512];
    daemoon_pair_payload_t parsed;
    daemoon_result_t r;
    daemoon_3ds_trace("pair/scan", NULL);
    r = daemoon_3ds_qr_scan(scan_frame, NULL, payload, sizeof(payload));
    daemoon_3ds_trace("pair/scan-done", daemoon_result_code(r));

    if (r == DAEMOON_ERR_USER_CANCELLED) {
        return 0;
    }
    if (r == DAEMOON_ERR_BACKEND_ERROR) {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_PAIR_NO_CAMERA), GFX_DANGER);
        return 0;
    }
    if (r != DAEMOON_OK) {
        report(DAEMOON_STR_PAIR_TITLE, r);
        return 0;
    }

    if (daemoon_pair_parse(payload, strlen(payload), &parsed) != DAEMOON_OK) {
        /* Something was read and it was not ours. Said plainly, because "scan
         * failed" would send somebody back to hold the console steadier at a code
         * that was never going to work. */
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_PAIR_WRONG_CODE), GFX_WARN);
        return 0;
    }

    /* The address travels with the code, which is the whole reason for scanning
     * rather than typing. */
    (void)daemoon_strlcpy(g_config.server_url, sizeof(g_config.server_url),
                          parsed.server);
    g_env.server_url = g_config.server_url;
    return finish_pairing("qr", parsed.code);
}

/* The address, with the trailing slash rule applied.
 *
 * Shared by Settings and the first run rather than typed twice: a trailing slash
 * becomes a double slash in every path built from it, and some servers answer
 * those differently. Two copies of that rule is one copy that gets forgotten. */
static int edit_server_url(void)
{
    size_t len;

    if (!edit_field(DAEMOON_STR_SETTINGS_SERVER, "http://192.168.1.10:8080",
                    g_config.server_url, sizeof(g_config.server_url))) {
        return 0;
    }
    len = strlen(g_config.server_url);
    while (len > 0 && g_config.server_url[len - 1] == '/') {
        g_config.server_url[--len] = '\0';
    }
    g_env.server_url = g_config.server_url;
    return 1;
}

/* The typed route out of the first run: the address, then the six digits.
 *
 * Both, in that order, because pairing by code needs a server to send it to and a
 * console that has just been installed has none. The scanned route needs neither,
 * which is the entire argument for preferring it. */
static int welcome_pair_manual(void)
{
    if (!edit_server_url()) {
        return 0;
    }
    if (g_config.server_url[0] == '\0') {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_PAIR_NO_SERVER), GFX_WARN);
        return 0;
    }
    return pair_with_typed_code();
}

static void run_welcome(void)
{
    static const daemoon_3ds_welcome_actions_t acts = {
        pair_by_scanning, welcome_pair_manual
    };
    int paired = daemoon_3ds_welcome_run(&acts);

    /* Recorded whatever the outcome. The flag says these screens have had their
     * turn, not that they succeeded, and a console shown them again every launch
     * because the answer was Not now is an application arguing with a decision it
     * asked for. */
    g_config.welcomed = 1;
    {
        daemoon_result_t r = daemoon_3ds_config_save(DAEMOON_3DS_CONFIG_PATH, &g_config);

        daemoon_3ds_trace("welcome/save", daemoon_result_code(r));
    }

    message(daemoon_str(DAEMOON_STR_APP_TITLE),
            daemoon_str(paired ? DAEMOON_STR_WELCOME_READY : DAEMOON_STR_WELCOME_LATER),
            paired ? GFX_OK : GFX_ACCENT);
}

/* --------------------------------------------------------------- autosync */

/* Phase 5, from main.c's side: lend the autosync loop the four things it cannot do
 * itself, and let it decide the rest.
 *
 * Both libraries are indexed rather than "the one on screen", because at boot there
 * is no screen and the person who set this up did not set it up for half of their
 * saves. */
static size_t autosync_count(void *user, int library)
{
    (void)user;
    if (show_library(library == LIB_NDS) != DAEMOON_OK) {
        return 0;
    }
    return g_lib[library].count;
}

static const char *autosync_name(void *user, int library, size_t index)
{
    (void)user;
    return g_lib[library].titles[index].name;
}

static daemoon_result_t autosync_sync_one(void *user, int library, size_t index,
                                          const daemoon_sync_opts_t *opts,
                                          daemoon_sync_stats_t *stats)
{
    daemoon_result_t r;

    (void)user;
    /* The backend pairing follows the library, the same way it does for L and R.
     * Syncing a DS save through the savedata backend would fail in a way that reads
     * as a permission problem. */
    select_backend(library == LIB_NDS);

    daemoon_3ds_trace("autosync/title", g_lib[library].titles[index].id);
    r = daemoon_sync_title_with(&g_env, &g_archive, &g_lib[library].titles[index],
                                opts, stats);
    daemoon_3ds_trace("autosync/title-done", daemoon_result_code(r));
    return r;
}

static void autosync_when(void *user, char *buf, size_t len)
{
    (void)user;
    if (clock_iso8601(NULL, buf, len) != DAEMOON_OK) {
        (void)daemoon_strlcpy(buf, len, "unknown");
    }
}

/* Wi-Fi is not up the instant a console is.
 *
 * A cheap request against the server, retried, rather than asking the system whether
 * it thinks it has a link: what matters is whether this server answers, and a console
 * that has associated with an access point can still have no route. The title id is
 * one that cannot exist, so a success and a 404 are both "the server is there" and
 * neither touches a save. */
#define AUTOSYNC_NET_TRIES 10

static int autosync_wait_for_network(void *user)
{
    int attempt;

    (void)user;
    if (daemoon_net_curl_init() != DAEMOON_OK) {
        daemoon_3ds_trace("autosync/net-init", "failed");
        return 0;
    }

    for (attempt = 0; attempt < AUTOSYNC_NET_TRIES; ++attempt) {
        daemoon_remote_meta_t meta;
        daemoon_result_t r;
        char detail[32];

        if (!aptMainLoop()) {
            return 0;
        }
        r = daemoon_api_get_latest(&g_env, DAEMOON_PLATFORM_3DS,
                                   "0000000000000000", &meta);
        (void)snprintf(detail, sizeof(detail), "%d %s", attempt,
                       daemoon_result_code(r));
        daemoon_3ds_trace("autosync/net-probe", detail);

        /* Not found is the server answering. Unauthorized is the server answering
         * too, and a token that has been revoked is worth finding out about here
         * rather than once per title. */
        if (r == DAEMOON_OK || r == DAEMOON_ERR_NOT_FOUND) {
            return 1;
        }
        if (r == DAEMOON_ERR_UNAUTHORIZED || r == DAEMOON_ERR_DEVICE_REVOKED) {
            return 0;
        }
        svcSleepThread(1000000000LL); /* one second */
    }
    return 0;
}

/* Returns nonzero when the run went ahead, which is main.c's cue to head for HOME
 * rather than draw a library. */
static int run_autosync(void)
{
    daemoon_3ds_autosync_ctx_t ctx;

    memset(&ctx, 0, sizeof(ctx));
    ctx.env = &g_env;
    ctx.when = autosync_when;
    ctx.count = autosync_count;
    ctx.name = autosync_name;
    ctx.sync_one = autosync_sync_one;
    ctx.wait_for_network = autosync_wait_for_network;

    return daemoon_3ds_autosync_run(&ctx);
}

/* ------------------------------------------------------------------ batch */

/* What the batch screen borrows. Indices are into the library that is showing, so
 * batch.c never learns that there are two of them and switching with L or R before
 * opening it is the whole of "which library does this run over". */
/* Reading the other library is what makes a run cover both, and it is also what makes
 * opening this screen slow the first time: the list that is not on screen has never
 * been read. Paid once, before the confirmation, so the count in the question is the
 * number of things that will actually happen. */
static size_t batch_count(void *user, int library)
{
    (void)user;
    if (show_library(library == LIB_NDS) != DAEMOON_OK) {
        return 0;
    }
    return g_lib[library].count;
}

static const char *batch_name(void *user, int library, size_t index)
{
    (void)user;
    return g_lib[library].titles[index].name;
}

static void batch_backup_one(void *user, int library, size_t index)
{
    daemoon_result_t r;

    (void)user;
    /* The backend pairing follows the library, the same way it does for L and R.
     * Backing a DS save up through the savedata backend would fail in a way that
     * reads as a permission problem. */
    select_backend(library == LIB_NDS);

    daemoon_3ds_trace("batch/backup", g_lib[library].titles[index].id);
    r = daemoon_sync_backup_local(&g_env, &g_archive, &g_lib[library].titles[index],
                                  NULL, 0);
    daemoon_3ds_trace("batch/backup-done", daemoon_result_code(r));
    /* A title that fails is a line in the trace and not a dialog. Stopping a run
     * over forty titles to say that one of them has an empty archive is how a
     * person ends up holding A through the other thirty nine. */
    if (r == DAEMOON_OK) {
        ++g_batch.ok;
    } else if (r == DAEMOON_ERR_NOT_FOUND || r == DAEMOON_ERR_UNSUPPORTED) {
        ++g_batch.skipped;
    } else {
        ++g_batch.failed;
    }
}

static void batch_sync_one(void *user, int library, size_t index,
                           daemoon_conflict_policy_t policy)
{
    daemoon_sync_opts_t opts;
    daemoon_result_t r;

    (void)user;
    select_backend(library == LIB_NDS);

    memset(&opts, 0, sizeof(opts));
    opts.conflict = policy;
    /* Asked once, on the way in, with the count in it. Uploading changes nothing on
     * the console and the server keeps every version it had, so the question is
     * about intent - and forty more of the same dialog is a person pressing A, not a
     * person deciding. The restore confirmation is a different guarantee and is
     * still asked per title. */
    opts.upload_confirmed = 1;
    /* And the restore question, for the same run and on the same terms. The screen
     * that started this asked with the count in it and, when the answer was to take
     * the server's, said in that sentence that saves on this console would be
     * overwritten and that each is backed up to the card first.
     *
     * Rule 1 is untouched and is what makes this answerable: every restore below
     * still writes a package to the SD card before it writes to an archive, and
     * still aborts if that fails. What is replaced is a dialog, not a safeguard. */
    opts.restore_confirmed = 1;

    daemoon_3ds_trace("batch/sync", g_lib[library].titles[index].id);
    r = daemoon_sync_title_with(&g_env, &g_archive, &g_lib[library].titles[index],
                                &opts, &g_batch.sync);
    daemoon_3ds_trace("batch/sync-done", daemoon_result_code(r));
    if (r != DAEMOON_OK && r != DAEMOON_ERR_USER_CANCELLED) {
        ++g_batch.failed;
    }
}

static int batch_can_sync(void)
{
    return daemoon_3ds_config_can_sync(&g_config);
}

static int batch_confirm(const daemoon_str_ref_t *ask)
{
    return daemoon_3ds_ui_backend.confirm(&g_ui_ctx, ask);
}

static void batch_message(daemoon_str_id_t body, unsigned int accent)
{
    message(daemoon_str(DAEMOON_STR_APP_TITLE), daemoon_str(body), accent);
}

/* Nonzero when the run changed what is in a save archive on this console, which is
 * the only case where the list on screen has gone stale. */
static int action_batch(void)
{
    daemoon_3ds_batch_ctx_t ctx;
    char body[256];
    /* The run walks both libraries and leaves the backend pointed at the last one, so
     * the library the person was looking at is put back before this returns. */
    const int was_nds = g_source_nds;

    memset(&g_batch, 0, sizeof(g_batch));

    memset(&ctx, 0, sizeof(ctx));
    ctx.count = batch_count;
    ctx.name = batch_name;
    ctx.backup_one = batch_backup_one;
    ctx.sync_one = batch_sync_one;
    ctx.can_sync = batch_can_sync;
    ctx.confirm = batch_confirm;
    ctx.message = batch_message;

    if (!daemoon_3ds_batch_run(&ctx)) {
        /* Backed out before anything ran. Re-reading the library here was a minute
         * of loading as the price of pressing B, which is the one thing a person
         * does on this screen when they did not mean to open it. */
        (void)show_library(was_nds);
        return 0;
    }
    (void)show_library(was_nds);

    /* One tally at the end, in the same shape a single sync reports. */
    if (g_batch.sync.uploaded || g_batch.sync.downloaded || g_batch.sync.skipped ||
        g_batch.sync.conflicts) {
        char counts[4][12];
        const char *args[4];
        size_t i;
        const unsigned n[4] = { g_batch.sync.uploaded, g_batch.sync.downloaded,
                                g_batch.sync.skipped, g_batch.sync.conflicts };

        for (i = 0; i < 4; ++i) {
            (void)snprintf(counts[i], sizeof(counts[i]), "%u", n[i]);
            args[i] = counts[i];
        }
        (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_SYNC_RESULT, args, 4);
    } else {
        char counts[3][12];
        const char *args[3];
        size_t i;
        const unsigned n[3] = { g_batch.ok, g_batch.skipped, g_batch.failed };

        for (i = 0; i < 3; ++i) {
            (void)snprintf(counts[i], sizeof(counts[i]), "%u", n[i]);
            args[i] = counts[i];
        }
        (void)daemoon_strf(body, sizeof(body), DAEMOON_STR_BATCH_BACKUP_DONE, args, 3);
    }
    message(daemoon_str(DAEMOON_STR_APP_TITLE), body,
            g_batch.failed > 0 ? GFX_WARN : GFX_OK);

    /* Only a download wrote to a save archive. A batch backup reads every archive
     * and writes packages to the card, and an upload sends bytes to a server;
     * neither changes a single thing the grid or the details pane reads out. */
    return g_batch.sync.downloaded > 0;
}

/* Defined below, and reached from Settings now rather than from the grid. */
static void action_survey(void);

static void action_settings(void)
{
    const daemoon_str_id_t *labels = k_settings_labels;
    int selected = 0;
    int dirty = 0;

    daemoon_3ds_trace("settings/open", NULL);

    while (aptMainLoop()) {
        u32 down;
        int edited = 0;

        hidScanInput();
        down = hidKeysDown();

        daemoon_gfx_frame_begin();
        draw_settings(selected);
        daemoon_gfx_frame_end();

        if (down & KEY_B) {
            break;
        }
        if (down & KEY_A) {
            switch (selected) {
            case 0:
                edited = edit_server_url();
                break;
            case 1:
                edited = edit_field(labels[1], "daemoonctl pair", g_config.token,
                                    sizeof(g_config.token));
                if (edited) {
                    /* Typed by hand, and still a credential: it goes where the
                     * paired one goes, not onto the card. */
                    daemoon_result_t sr = daemoon_3ds_secret_save(&g_env,
                                                                  g_config.token,
                                                                  g_config.device_id);

                    daemoon_3ds_trace("secret/typed", daemoon_result_code(sr));
                    g_config.token_on_card = (sr != DAEMOON_OK);
                    g_env.token = g_config.token[0] != '\0' ? g_config.token : NULL;
                }
                break;
            case 2:
                edited = edit_field(labels[2], "3DS", g_config.device_label,
                                    sizeof(g_config.device_label));
                break;
            case 3:
                /* No keyboard for this one - it steps through the list, so the
                 * screen changes language under the cursor and the choice is
                 * judged by reading it. */
                edited = choose_language();
                break;
            case 4:
                edited = pair_by_scanning();
                break;
            case 5:
                edited = pair_with_typed_code();
                break;
            case 6:
                /* On purpose, and not only for somebody who skipped it: the pages
                 * are where the rule about not syncing while a game runs is
                 * written down, and that is worth being able to go back to. */
                run_welcome();
                edited = 1;
                break;
            case 7:
                /* A toggle rather than a screen. It only does anything when Luma is
                 * set to autoboot this title, and the row says which way it is
                 * pointing rather than describing what it would do. */
                g_config.autosync = !g_config.autosync;
                edited = 1;
                break;
            default:
                /* Moved off the grid, where it sat beside Back up and read like one.
                 * It is a diagnostic: it opens every archive, records what each step
                 * returned, and writes one text file. Nothing it does touches a save,
                 * and nothing that touches a save belongs next to it. */
                action_survey();
                break;
            }
            dirty = dirty || edited;
        }
        if ((down & KEY_UP) && selected > 0) {
            --selected;
        }
        if ((down & KEY_DOWN) && selected < SETTINGS_ROWS - 1) {
            ++selected;
        }
    }

    if (!dirty) {
        return;
    }

    {
        daemoon_result_t r = daemoon_3ds_config_save(DAEMOON_3DS_CONFIG_PATH, &g_config);

        daemoon_3ds_trace("settings/save", daemoon_result_code(r));
        if (r != DAEMOON_OK) {
            message(daemoon_str(DAEMOON_STR_APP_TITLE),
                    daemoon_str(DAEMOON_STR_SETTINGS_SAVE_FAILED), GFX_DANGER);
            return;
        }

        /* The environment points at these buffers, so the new values are already
         * in use. What is not is the network, which is opened once at startup and
         * may not have been opened at all. */
        g_env.token = g_config.token[0] != '\0' ? g_config.token : NULL;
        g_net_ctx.ca_bundle = g_config.ca_bundle;
        g_net_ctx.ca_blob = cacert_bin;
        g_net_ctx.ca_blob_len = cacert_bin_size;

    /* The token lives in this application's own save archive, not on the card.
     *
     * A console paired before that change has one in config.txt, so it is moved
     * across on the first run that finds it there and struck from the file. The
     * card stops being a credential from that moment, which is the whole point:
     * revocation answers a lost card, and revocation is a thing you have to notice
     * you need. */
    {
        char token[DAEMOON_TOKEN_MAX];
        char device_id[DAEMOON_DEVICE_ID_MAX];

        if (daemoon_3ds_secret_load(&g_env, token, sizeof(token), device_id,
                                    sizeof(device_id)) == DAEMOON_OK) {
            (void)daemoon_strlcpy(g_config.token, sizeof(g_config.token), token);
            (void)daemoon_strlcpy(g_config.device_id, sizeof(g_config.device_id),
                                  device_id);
            daemoon_3ds_trace("secret/loaded", device_id);
        } else if (g_config.token[0] != '\0') {
            daemoon_result_t mr = daemoon_3ds_secret_save(&g_env, g_config.token,
                                                          g_config.device_id);

            daemoon_3ds_trace("secret/migrated", daemoon_result_code(mr));
            /* A migration that cannot happen leaves the token where it already is
             * and working. It is retried on the next run. */
            g_config.token_on_card = (mr != DAEMOON_OK);
            if (mr == DAEMOON_OK) {
                /* Rewritten without it: config_save only emits a token when the
                 * archive refused, so this is what takes it off the card. */
                (void)daemoon_3ds_config_save(DAEMOON_3DS_CONFIG_PATH, &g_config);
            }
        }
    }
        if (daemoon_3ds_config_can_sync(&g_config)) {
            (void)daemoon_net_curl_init();
        }
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_SETTINGS_SAVED), GFX_OK);
    }
}

static void action_survey(void)
{
    daemoon_stream_t *out = NULL;
    daemoon_result_t r;
    size_t i;

    r = g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/survey.txt",
                       DAEMOON_OPEN_WRITE, &out);
    if (r != DAEMOON_OK) {
        report(DAEMOON_STR_OP_SURVEY, r);
        return;
    }

    {
        char header[160];
        daemoon_strbuf_t hb;

        daemoon_strbuf_init(&hb, header, sizeof(header));
        daemoon_strbuf_add(&hb, "# DaeMoon build ");
        daemoon_strbuf_add(&hb, DAEMOON_BUILD_STAMP);
        daemoon_strbuf_add(&hb, " font=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)daemoon_gfx_font_source());
        /* Which languages this console could draw at all, as one bit each. The
         * font question this project spent weeks on is a fact about the console,
         * so it belongs in the file that describes one. */
        daemoon_strbuf_add(&hb, " drawable=");
        {
            static const daemoon_lang_t k_all[] = {
                DAEMOON_LANG_EN, DAEMOON_LANG_KO, DAEMOON_LANG_JA,
                DAEMOON_LANG_ZH_HANS, DAEMOON_LANG_ZH_HANT, DAEMOON_LANG_ES,
                DAEMOON_LANG_FR, DAEMOON_LANG_DE
            };
            size_t li;

            for (li = 0; li < sizeof(k_all) / sizeof(k_all[0]); ++li) {
                if (!daemoon_gfx_language_drawable(k_all[li])) {
                    continue;
                }
                daemoon_strbuf_add(&hb, daemoon_lang_code(k_all[li]));
                daemoon_strbuf_addc(&hb, ',');
            }
        }
        daemoon_strbuf_add(&hb, " ascii_names=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)g_save_ctx.ascii_names);
        daemoon_strbuf_add(&hb, " smdh_lang=");
        daemoon_strbuf_add_uint(&hb, (unsigned long long)g_save_ctx.smdh_language);
        daemoon_strbuf_addc(&hb, '\n');
        (void)daemoon_stream_write(out, header, hb.len);
    }

    for (i = 0; i < CUR->count; ++i) {
        daemoon_title_t *t = &CUR->titles[i];
        daemoon_3ds_secure_value_t secure;
        daemoon_save_t *save = NULL;
        unsigned long long bytes = 0;
        char line[512];
        daemoon_strbuf_t sb;
        daemoon_result_t sr;
        daemoon_result_t or_;

        memset(&secure, 0, sizeof(secure));
        sr = daemoon_3ds_read_secure_value(t, &secure);

        or_ = g_env.save->open_save(g_env.save_ctx, t, &save);
        if (or_ == DAEMOON_OK) {
            (void)g_env.save->list_entries(g_env.save_ctx, save, survey_count_cb, &bytes);
            (void)g_env.save->close_save(g_env.save_ctx, save);
        }

        daemoon_strbuf_init(&sb, line, sizeof(line));
        daemoon_strbuf_add(&sb, t->id);
        daemoon_strbuf_add(&sb, "\tsave=");
        daemoon_strbuf_add(&sb, or_ == DAEMOON_OK ? "yes" : daemoon_result_code(or_));
        daemoon_strbuf_add(&sb, "\tbytes=");
        daemoon_strbuf_add_uint(&sb, bytes);
        daemoon_strbuf_add(&sb, "\tsecure=");
        if (sr != DAEMOON_OK) {
            daemoon_strbuf_add(&sb, daemoon_result_code(sr));
        } else if (secure.exists) {
            static const char digits[] = "0123456789ABCDEF";
            char hex[17];
            int k;

            for (k = 0; k < 16; ++k) {
                hex[k] = digits[(secure.value >> ((15 - k) * 4)) & 0xf];
            }
            hex[16] = '\0';
            daemoon_strbuf_add(&sb, hex);
        } else {
            daemoon_strbuf_add(&sb, "none");
        }

        daemoon_strbuf_add(&sb, "\ticon=");
        daemoon_strbuf_add(&sb, (i < MAX_ICONS && CUR->icons[i].loaded) ? "yes" : "no");

        /* Why the name is what it is, and the raw Result when it is not a name.
         * A wire code says "not supported"; a Result says which module said it,
         * and this question has already cost two trips to a console. */
        {
            char real[DAEMOON_NAME_MAX];
            daemoon_result_t nr = daemoon_3ds_title_name(g_save_ctx.media, tid_of(t),
                                                         g_save_ctx.smdh_language, 0,
                                                         real, sizeof(real));

            daemoon_strbuf_add(&sb, "\tname=");
            daemoon_strbuf_add(&sb, nr == DAEMOON_OK ? "smdh" : daemoon_result_code(nr));
            {
                const daemoon_3ds_name_probe_t *pr = daemoon_3ds_last_name_probe();

                daemoon_strbuf_add(&sb, " lang=");
                daemoon_strbuf_add_int(&sb, pr->name_lang);
                if (pr->rejected_non_ascii) {
                    /* A name was there and could not be drawn. That is the font,
                     * not the lookup. */
                    daemoon_strbuf_add(&sb, " undrawable");
                }
            }
            if (nr != DAEMOON_OK) {
                /* Every route and what it said. One coarse word covered three
                 * different causes and cost four trips to a console; this is the
                 * shape of a diagnostic that ends the guessing. */
                const daemoon_3ds_name_probe_t *pr = daemoon_3ds_last_name_probe();

                daemoon_strbuf_add(&sb, " direct=");
                append_hex32(&sb, (unsigned long)pr->open_direct);
                daemoon_strbuf_add(&sb, " direct2=");
                append_hex32(&sb, (unsigned long)pr->open_direct2);
                daemoon_strbuf_add(&sb, " archive=");
                append_hex32(&sb, (unsigned long)pr->open_archive);
                daemoon_strbuf_add(&sb, " file=");
                append_hex32(&sb, (unsigned long)pr->open_file);
                daemoon_strbuf_add(&sb, " read=");
                append_hex32(&sb, (unsigned long)pr->read);
                daemoon_strbuf_add(&sb, " got=");
                daemoon_strbuf_add_uint(&sb, pr->read_bytes);
            }
            daemoon_strbuf_add(&sb, "\treal=");
            daemoon_strbuf_add(&sb, nr == DAEMOON_OK ? real : "-");
        }

        /* The name as the console knows it, in whatever script that is. This file
         * is read on a machine with fonts. */
        daemoon_strbuf_add(&sb, "\t");
        daemoon_strbuf_add(&sb, t->name);
        daemoon_strbuf_addc(&sb, '\n');

        (void)daemoon_stream_write(out, line, sb.len);
    }

    r = daemoon_stream_close(out);

    /* Everything above went to the hardware rather than to the cache, so the cache
     * is now the older of the two answers. Throwing it away also makes this the
     * button to press when a name or an icon looks wrong: the next list is read
     * from the console again. */
    daemoon_3ds_cache_forget(g_save_ctx.cache);

    report(DAEMOON_STR_OP_SURVEY, r);
}

/* The conformance suite writes, clears and commits a real save archive. It exists
 * to prove this backend behaves the way core is entitled to assume, and running
 * it on a title someone plays would be indefensible. */
/* The self test used to be a button on the grid, run against whichever title the
 * cursor was on - and it clears that title's save archive to prove that clearing
 * works. It sat two rows above Back up, on a screen where the other five buttons
 * are things you do to a game you care about.
 *
 * The contract it checks has not gone anywhere: tools/test/backend_conformance.c
 * is still linked in, `make core-test` still runs it against the stub, and
 * run_autotest below still runs it on hardware - against this application's own
 * save archive, which is the only archive it has any business destroying. What is
 * gone is the one press between a real save and a wipe.
 */

/* Unattended, from a flag file, against this application's own save archive and
 * nothing else. See docs/3ds-workflow.md. */
static void run_autotest(void)
{
    daemoon_backend_under_test_t ut;
    daemoon_title_t self;
    daemoon_stream_t *out = NULL;
    char line[256];
    daemoon_strbuf_t sb;
    u64 program_id = 0;
    int failures;

    memset(&self, 0, sizeof(self));
    if (R_FAILED(APT_GetProgramID(&program_id))) {
        return;
    }
    daemoon_3ds_format_title_id(program_id, self.id, sizeof(self.id));
    (void)daemoon_strlcpy(self.name, sizeof(self.name),
                          daemoon_str(DAEMOON_STR_SELFTEST_SELF));
    self.platform = DAEMOON_PLATFORM_3DS;
    self.save_type = DAEMOON_SAVE_SAVEDATA;
    self.size_hint = (unsigned long long)MEDIATYPE_SD;
    self.has_save = 1;

    {
        daemoon_save_t *probe = NULL;

        if (daemoon_3ds_save_backend.open_save(&g_save_ctx, &self, &probe) == DAEMOON_OK) {
            (void)daemoon_3ds_save_backend.close_save(&g_save_ctx, probe);
        } else if (daemoon_3ds_format_own_save(&self, 128) != DAEMOON_OK) {
            message(daemoon_str(DAEMOON_STR_APP_TITLE),
                    daemoon_str(DAEMOON_STR_SELFTEST_NO_ARCHIVE), GFX_WARN);
            return;
        }
    }

    memset(&ut, 0, sizeof(ut));
    ut.name = "3ds";
    ut.backend = &daemoon_3ds_save_backend;
    ut.ctx = &g_save_ctx;
    ut.title = &self;
    ut.other = NULL;
    ut.scratch = g_scratch;
    ut.scratch_len = sizeof(g_scratch);

    failures = daemoon_test_failures;
    daemoon_backend_conformance(&ut);
    failures = daemoon_test_failures - failures;

    /* The suite clears the archive it is pointed at, and that archive is now where
     * the device token lives. Putting it back is not tidiness: without it, running
     * the self test unpairs the console, which is a surprising price for a
     * diagnostic. */
    if (g_config.token[0] != '\0') {
        daemoon_result_t sr = daemoon_3ds_secret_save(&g_env, g_config.token,
                                                      g_config.device_id);

        daemoon_3ds_trace("secret/restored", daemoon_result_code(sr));
    }

    if (g_config.token[0] != '\0') {
        (void)daemoon_3ds_secret_save(&g_env, g_config.token, g_config.device_id);
    }

    /* The screen that has twice gone wrong on hardware, drawn unattended. It
     * asserts nothing - a fault here takes the process down, which is the report. */
    daemoon_3ds_trace("autotest/picker-draw", NULL);
    daemoon_3ds_pick_backup_render_check(&self, 8);
    daemoon_3ds_trace("autotest/picker-drawn", NULL);

    daemoon_strbuf_init(&sb, line, sizeof(line));
    daemoon_strbuf_add(&sb, "build=");
    daemoon_strbuf_add(&sb, DAEMOON_BUILD_STAMP);
    daemoon_strbuf_add(&sb, " target=");
    daemoon_strbuf_add(&sb, self.id);
    daemoon_strbuf_add(&sb, " checks=");
    daemoon_strbuf_add_uint(&sb, (unsigned long long)daemoon_test_checks);
    daemoon_strbuf_add(&sb, " failures=");
    daemoon_strbuf_add_uint(&sb, (unsigned long long)failures);
    if (failures > 0 && daemoon_test_last_failure[0] != '\0') {
        daemoon_strbuf_add(&sb, " first: ");
        daemoon_strbuf_add(&sb, daemoon_test_last_failure);
    }
    daemoon_strbuf_addc(&sb, '\n');

    if (g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/selftest.txt",
                       DAEMOON_OPEN_WRITE, &out) == DAEMOON_OK) {
        (void)daemoon_stream_write(out, line, sb.len);
        (void)daemoon_stream_close(out);
    }

    message(daemoon_str(DAEMOON_STR_APP_TITLE), line, failures == 0 ? GFX_OK : GFX_DANGER);
}

/* Pairing, unattended, from a payload on the card.
 *
 * The camera is the only part of the QR path a desktop cannot stand in for. This
 * runs everything else as a real ARM binary against a real server: the same parser
 * the camera feeds, the same network backend, the same token write. What is left
 * for hardware is whether a 3DS camera can read a screen, which is a question about
 * optics rather than about this code.
 *
 * The flag file holds exactly what a scan would produce, so the emulator run and
 * the hardware run differ in one step and nothing else.
 */
static void run_autopair(void)
{
    char payload[512];
    daemoon_pair_payload_t parsed;
    daemoon_stream_t *in = NULL;
    daemoon_stream_t *out = NULL;
    daemoon_strbuf_t sb;
    char line[256];
    size_t got = 0;
    daemoon_result_t r;

    if (g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_AUTOPAIR_PATH, DAEMOON_OPEN_READ,
                       &in) != DAEMOON_OK) {
        return;
    }
    r = daemoon_stream_read(in, payload, sizeof(payload) - 1, &got);
    (void)daemoon_stream_close(in);
    if (r != DAEMOON_OK) {
        got = 0;
    }
    payload[got] = '\0';
    while (got > 0 && (payload[got - 1] == '\n' || payload[got - 1] == '\r')) {
        payload[--got] = '\0';
    }

    daemoon_strbuf_init(&sb, line, sizeof(line));
    daemoon_strbuf_add(&sb, "build=");
    daemoon_strbuf_add(&sb, DAEMOON_BUILD_STAMP);

    r = daemoon_pair_parse(payload, got, &parsed);
    daemoon_strbuf_add(&sb, " parse=");
    daemoon_strbuf_add(&sb, daemoon_result_code(r));

    if (r == DAEMOON_OK) {
        char token[DAEMOON_TOKEN_MAX];
        char device_id[DAEMOON_DEVICE_ID_MAX];

        (void)daemoon_strlcpy(g_config.server_url, sizeof(g_config.server_url),
                              parsed.server);
        g_env.server_url = g_config.server_url;

        r = daemoon_net_curl_init();
        daemoon_strbuf_add(&sb, " net=");
        daemoon_strbuf_add(&sb, daemoon_result_code(r));

        if (r == DAEMOON_OK) {
            r = daemoon_api_pair(&g_env, "qr", parsed.code, g_config.device_label,
                                 DAEMOON_PLATFORM_3DS, token, sizeof(token),
                                 device_id, sizeof(device_id));
            daemoon_strbuf_add(&sb, " pair=");
            daemoon_strbuf_add(&sb, daemoon_result_code(r));

            if (r == DAEMOON_OK) {
                (void)daemoon_strlcpy(g_config.token, sizeof(g_config.token), token);
                (void)daemoon_strlcpy(g_config.device_id, sizeof(g_config.device_id),
                                      device_id);
                g_env.token = g_config.token;
                r = daemoon_3ds_config_save(DAEMOON_3DS_CONFIG_PATH, &g_config);
                daemoon_strbuf_add(&sb, " save=");
                daemoon_strbuf_add(&sb, daemoon_result_code(r));
                daemoon_strbuf_add(&sb, " device=");
                daemoon_strbuf_add(&sb, device_id);
            }
        }
    }
    daemoon_strbuf_addc(&sb, '\n');

    if (g_env.fs->open(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/autopair.txt",
                       DAEMOON_OPEN_WRITE, &out) == DAEMOON_OK) {
        (void)daemoon_stream_write(out, line, sb.len);
        (void)daemoon_stream_close(out);
    }

    message(daemoon_str(DAEMOON_STR_APP_TITLE), line,
            r == DAEMOON_OK ? GFX_OK : GFX_DANGER);
}

/* --------------------------------------------------------------------- main */

int main(void)
{
    daemoon_lang_t lang = DAEMOON_LANG_EN;

    /* The settings come first because the language is one of them, and the
     * language decides which font is loaded. Reading the file needs nothing but
     * stdio, so it can happen before any service is up. */
    (void)daemoon_3ds_config_load(DAEMOON_3DS_CONFIG_PATH, &g_config);

    if (R_FAILED(cfguInit())) {
        g_save_ctx.smdh_language = 1;
    } else {
        lang = select_language();
    }

    if (!daemoon_gfx_init(lang)) {
        return 1;
    }

    /* The font decision, made at runtime rather than at build time.
     *
     * A console's system font is its own region's, so a Korean console draws
     * Hangul and a European one does not - and the selected language is a user
     * choice with nothing to do with the console's region. Rather than bundle a
     * font, ask the font in use whether it has a representative character of the
     * language, and fall back to English when it does not.
     *
     * English is a poor answer for somebody who does not read it. It is a better
     * one than a screen of blank boxes on a confirmation they have to answer, and
     * it is the option docs/fonts.md picked with the sizes written down. */
    /* daemoon_gfx_init already loaded the font for this language, or fell back.
     * When it could not, the UI language follows rather than drawing blanks. */
    if (!daemoon_gfx_language_drawable(lang)) {
        daemoon_3ds_trace("font/fallback", daemoon_lang_code(lang));
        (void)daemoon_gfx_set_language(DAEMOON_LANG_EN);
        daemoon_i18n_set_language(DAEMOON_LANG_EN);
    }
    (void)amInit();

    /* A line the trail can be read from. Without it two runs of the same action
     * are indistinguishable in the file, and "did it get further this time" is the
     * question the file exists to answer. */
    daemoon_3ds_trace("app/start", DAEMOON_BUILD_STAMP);
    {
        /* What survived the last run.
         *
         * Reinstalling a CIA does not touch the SD card, so a token that keeps
         * changing across installs means something is losing it rather than the
         * install replacing it - and the difference is not visible from a device
         * list. The token itself is never written here; a console screen and a
         * trace file both end up in bug reports. */
        /* Long enough for the longest of them. A device id is 22 characters and a
         * truncated diagnostic is one that says something other than what
         * happened. */
        char line[160];

        (void)snprintf(line, sizeof(line), "server=%s token=%s device=%s lang=%s",
                       g_config.server_url[0] != '\0' ? "yes" : "no",
                       g_config.token[0] != '\0' ? "yes" : "no",
                       g_config.device_id[0] != '\0' ? g_config.device_id : "-",
                       g_config.language[0] != '\0' ? g_config.language : "auto");
        daemoon_3ds_trace("app/config", line);
    }
    {
        /* Both clocks, because they are not the same one and only one of them
         * decides whether a certificate is valid. mbedtls reads the C library's,
         * so a console where that says 1970 cannot complete a handshake against
         * anything issued this decade no matter what the RTC says. */
        char when[64];

        if (clock_iso8601(NULL, when, sizeof(when)) != DAEMOON_OK) {
            (void)daemoon_strlcpy(when, sizeof(when), "time() unusable");
        }
        daemoon_3ds_trace("app/clock", when);
        (void)snprintf(when, sizeof(when), "osGetTime=%llu",
                       (unsigned long long)osGetTime());
        daemoon_3ds_trace("app/clock-rtc", when);
    }

    g_save_ctx.media = 1; /* MEDIATYPE_SD */
    g_save_ctx.only_with_saves = 1;
    /* Names in whatever script the title carries.
     *
     * This used to be tied to daemoon_gfx_has_language_font(), which answers a
     * narrower question: whether an *extra* region font was loaded. It never is,
     * so every non ASCII name fell back to a product code - and then hardware
     * showed Korean dialog text rendering perfectly. The system font a console
     * ships with is its own region's, and it is the font the HOME menu draws these
     * same names with. There was never a reason to refuse them.
     *
     * The survey still records the real name either way, so a title whose glyphs
     * are genuinely missing is a fact rather than a guess. */
    g_save_ctx.ascii_names = 0;

    daemoon_3ds_ui_init(&g_ui_ctx);
    g_archive.count = 0;

    /* The card's bundle if there is one, the built in roots otherwise. A person
     * setting ca_bundle has a private CA, and a private CA cannot be in a list
     * compiled into everybody's copy. */
    g_net_ctx.ca_bundle = g_config.ca_bundle;
    g_net_ctx.ca_blob = cacert_bin;
    g_net_ctx.ca_blob_len = cacert_bin_size;

    g_nds_ctx.rom_dir = DAEMOON_3DS_NDS_ROM_DIR;
    g_nds_ctx.save_dir = DAEMOON_3DS_NDS_SAVE_DIR;

    /* The network is opened once. Doing it per request would mean a soc:U session
     * per sync, and that service does not enjoy being churned. */
    if (daemoon_3ds_config_can_sync(&g_config)) {
        (void)daemoon_net_curl_init();
    }

    memset(&g_env, 0, sizeof(g_env));
    g_env.save = &daemoon_3ds_save_backend;
    g_env.fs = &daemoon_fs_newlib_backend;
    g_env.ui = &daemoon_3ds_ui_backend;
    g_env.net = &daemoon_net_curl_backend;
    g_env.net_ctx = &g_net_ctx;
    g_env.save_ctx = &g_save_ctx;
    g_env.fs_ctx = NULL;
    g_env.ui_ctx = &g_ui_ctx;
    g_env.device_label = g_config.device_label;
    g_env.server_url = g_config.server_url;
    g_env.token = g_config.token[0] != '\0' ? g_config.token : NULL;
    g_env.work_dir = DAEMOON_3DS_WORK_DIR;
    g_env.clock_iso8601 = clock_iso8601;
    g_env.scratch = g_scratch;
    g_env.scratch_len = sizeof(g_scratch);

    g_save_ctx.progress = loading_progress;

    /* Names and icons from the last launch, so the loading screen stops paying for
     * a decrypt per title every time. Failing to open it is not an error: without
     * one every lookup goes to the hardware, which is what happened before this
     * existed. */
    (void)g_env.fs->mkdir_p(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/cache");
    if (daemoon_3ds_cache_open(DAEMOON_3DS_CACHE_PATH, g_save_ctx.smdh_language,
                               &g_save_ctx.cache) != DAEMOON_OK) {
        g_save_ctx.cache = NULL;
    }

    {
        /* The unattended runs answer to a file rather than to a person, so neither
         * may stop at a screen waiting for A. Asked once and kept, because the
         * welcome needs the same answer as the two branches below and reading the
         * card twice for it would be two chances to disagree. */
        int unattended = g_env.fs->exists(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/AUTOTEST") ||
                         g_env.fs->exists(g_env.fs_ctx, DAEMOON_3DS_AUTOPAIR_PATH);

        /* Phase 5, and it is decided before the welcome for a reason: a console that
         * boots into a sync must not stop at an explanation waiting for A. Every
         * reason not to run is a separate one, which is why the decision is a pure
         * function with four arguments rather than a chain of ifs here. */
        hidScanInput();
        int autosync = daemoon_3ds_autosync_due(g_config.autosync,
                                                daemoon_3ds_config_can_sync(&g_config),
                                                (hidKeysHeld() & KEY_B) != 0,
                                                unattended);

        /* Before the library rather than after it. The first launch is the one with
         * no name and icon cache and so the slowest, and an explanation that
         * arrives after a minute of loading is one nobody reads. */
        if (!unattended && !autosync && daemoon_3ds_welcome_needed(&g_config)) {
            run_welcome();
        }

        if (autosync && run_autosync()) {
            /* Out, rather than into the grid. The console was switched on to play
             * something, and this application was in the way of the HOME menu for as
             * long as the sync took. */
            goto done;
        }
    }

    if (show_library(0) != DAEMOON_OK) {
        message(daemoon_str(DAEMOON_STR_APP_TITLE),
                daemoon_str(DAEMOON_STR_ERR_TITLE_LIST), GFX_DANGER);
    }

    if (g_env.fs->exists(g_env.fs_ctx, DAEMOON_3DS_WORK_DIR "/AUTOTEST")) {
        run_autotest();
        goto done;
    }
    if (g_env.fs->exists(g_env.fs_ctx, DAEMOON_3DS_AUTOPAIR_PATH)) {
        run_autopair();
        goto done;
    }

    while (aptMainLoop()) {
        touchPosition touch;
        int action = -1;
        u32 down;

        hidScanInput();
        down = hidKeysDown();
        hidTouchRead(&touch);

        if (down & KEY_START) {
            break;
        }
        if (down & (KEY_L | KEY_R)) {
            /* The other library, kept from last time: its list, its icons and
             * where the cursor was. Only the first press of each pays for a read. */
            (void)show_library(!g_source_nds);
            continue;
        }
        if (CUR->count > 0) {
            if ((down & KEY_RIGHT) && CUR->selected + 1 < (int)CUR->count) {
                ++CUR->selected;
            }
            if ((down & KEY_LEFT) && CUR->selected > 0) {
                --CUR->selected;
            }
            if ((down & KEY_DOWN) && CUR->selected + GRID_COLS < (int)CUR->count) {
                CUR->selected += GRID_COLS;
            }
            if ((down & KEY_UP) && CUR->selected - GRID_COLS >= 0) {
                CUR->selected -= GRID_COLS;
            }
            if (down & KEY_A) {
                action = 0; /* back up */
            }
            if (down & KEY_Y) {
                action = 1; /* restore */
            }
            if (down & KEY_X) {
                action = 3; /* survey */
            }

            /* Keep the selection on screen. */
            if (CUR->selected / GRID_COLS < CUR->scroll) {
                CUR->scroll = CUR->selected / GRID_COLS;
            }
            if (CUR->selected / GRID_COLS >= CUR->scroll + GRID_ROWS) {
                CUR->scroll = CUR->selected / GRID_COLS - GRID_ROWS + 1;
            }
        }

        daemoon_gfx_frame_begin();
        draw_grid();
        draw_details(down, touch, &action);
        daemoon_gfx_frame_end();

        switch (action) {
        case 0: action_backup(); break;
        case 1: action_restore(); break;
        case 2: action_sync(); break;
        case 4: action_settings(); break;
        case 3:
            /* Reloaded only when a save archive on this console actually changed.
             * The names and icons come from the cache either way, but re-reading the
             * list still opens every archive on the console, which is long enough to
             * look like a hang and far too long to spend on the way out of a screen
             * somebody opened by accident. */
            if (action_batch()) {
                (void)reload_titles();
            }
            break;
        default: break;
        }
    }

done:
    daemoon_3ds_trace("app/exit", NULL);
    free_library(&g_lib[LIB_3DS]);
    free_library(&g_lib[LIB_NDS]);
    (void)daemoon_3ds_cache_flush(g_save_ctx.cache, DAEMOON_3DS_CACHE_PATH);
    daemoon_3ds_cache_close(g_save_ctx.cache);
    daemoon_net_curl_exit();
    amExit();
    cfguExit();
    daemoon_gfx_exit();
    return 0;
}
